// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const EditColumn = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M3 4a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1zm0 1H1v10h2zM14.5 0a.5.5 0 0 1 .5.5V1h.5a.5.5 0 0 1 0 1H15v.5a.5.5 0 0 1-1 0V2h-.5a.5.5 0 0 1 0-1h.5V.5a.5.5 0 0 1 .5-.5M.5 1h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1M9 4a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1zm0 1H7v10h2zM13 4h.5a.5.5 0 0 1 0 1H13v.5a.5.5 0 0 1-1 0V5a1 1 0 0 1 1-1M12.5 10a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0v-1a.5.5 0 0 1 .5-.5M12.5 7a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0v-1a.5.5 0 0 1 .5-.5M12.5 13a.5.5 0 0 1 .5.5V16a1 1 0 0 1-1-1v-1.5a.5.5 0 0 1 .5-.5M15 4a1 1 0 0 1 1 1v1.5a.5.5 0 0 1-1 0zM15.5 8a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0v-1a.5.5 0 0 1 .5-.5M15.5 11a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0v-1a.5.5 0 0 1 .5-.5M14.5 15H16a1 1 0 0 1-1 1h-.5a.5.5 0 0 1 0-1m1-1a.5.5 0 0 1 .5.5v.5h-1v-.5a.5.5 0 0 1 .5-.5" />
  </svg>
);
const ForwardRef = forwardRef(EditColumn);
export default ForwardRef;
