// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Resize = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M6 8a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2zm0 1H2a1 1 0 0 0-.993.883L1 10v4a1 1 0 0 0 .883.993L2 15h4a1 1 0 0 0 .993-.883L7 14v-4a1 1 0 0 0-.883-.993zM10 3h3v3zM8 5l3 3H8zM15 14v-1h1v1a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1M15 2v1h1V2a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1M1 2v1H0V2a2 2 0 0 1 2-2h1v1H2a1 1 0 0 0-1 1M15 10h1v2h-1zM15 4h1v2h-1zM10 0h2v1h-2zM10 15h2v1h-2zM7 0h2v1H7z" />
    <path d="M7 15h2v1H7zM4 0h2v1H4zM15 7h1v2h-1zM0 7h1v2H0zM0 4h1v2H0z" />
  </svg>
);
const ForwardRef = forwardRef(Resize);
export default ForwardRef;
