// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const SiteParsing = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M15 9h1V3a2 2 0 0 0-2-2H2a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h6v-1H5V5h10zM4 5v9H2a1 1 0 0 1-1-1V5zm11-1H1V3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1z" />
    <path d="M10.5 8a.5.5 0 0 1 0 1h-3a.5.5 0 0 1 0-1zM12 8.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5M8.5 11a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zM15.5 14a.5.5 0 0 1 0 1h-1a.5.5 0 0 1 0-1zM10 11.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5M9 14.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5" />
  </svg>
);
const ForwardRef = forwardRef(SiteParsing);
export default ForwardRef;
