// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const SiteFill = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M0 6h5v9H2a2 2 0 0 1-2-2zm6 0h10v7a2 2 0 0 1-2 2H6zM0 3a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v2H0z" />
  </svg>
);
const ForwardRef = forwardRef(SiteFill);
export default ForwardRef;
