// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const SiteSetting = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M5 6H1V5h14v1H6v8H5z" />
    <path d="M15 8V3a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h6v1H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v5z" />
    <path d="M13 12a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
    <path d="M14.19 8.646c.397.229.588.7.461 1.141l-.234.817.826.207a1 1 0 0 1 .757.97v.438a1 1 0 0 1-.757.97l-.826.206.235.818a1 1 0 0 1-.461 1.141l-.38.219a1 1 0 0 1-1.219-.171L12 14.79l-.591.612a1 1 0 0 1-1.219.171l-.38-.219a1 1 0 0 1-.461-1.141l.234-.818-.825-.206a1 1 0 0 1-.757-.97v-.438a1 1 0 0 1 .757-.97l.826-.207-.235-.817a1 1 0 0 1 .461-1.141l.38-.219a1 1 0 0 1 1.219.171l.591.611.591-.611a1 1 0 0 1 1.219-.171zm-.5.866-.38-.219-.591.611h-1.437l-.592-.611-.38.218.235.817-.718 1.246-.827.207-.001.438.825.206.72 1.245-.234.819.379.22.591-.612 1.439-.001.592.612.38-.218-.235-.818.72-1.247.825-.205-.001-.439-.826-.207-.718-1.246z" />
  </svg>
);
const ForwardRef = forwardRef(SiteSetting);
export default ForwardRef;
