// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Width = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="m13.859 9.152.057.07 2.018 3.029.036.077.023.089.007.082-.007.082-.015.065-.024.062-.02.038-2.018 3.029a.5.5 0 0 1-.875-.475l.043-.079 1.481-2.223H1.434l1.482 2.223a.5.5 0 0 1-.776.625l-.057-.07-2-3a.5.5 0 0 1-.054-.107l-.023-.089L0 12.522l.006-.106.015-.065.024-.062.023-.045 2.015-3.023a.5.5 0 0 1 .875.475l-.043.079-1.482 2.223h13.132l-1.482-2.223a.5.5 0 0 1 .776-.625zM15 0a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1a1 1 0 0 1 1-1zm0 1H1v5h14z" />
  </svg>
);
const ForwardRef = forwardRef(Width);
export default ForwardRef;
