// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const DataAuthorize = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M2.5 2a1.5 1.5 0 0 0 0 3h9a1.5 1.5 0 0 0 0-3zm0-1h9a2.5 2.5 0 1 1 0 5h-9a2.5 2.5 0 1 1 0-5" />
    <path d="M2.5 3a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1m3 0a.5.5 0 0 1 0 1h-1a.5.5 0 0 1 0-1zm-3 4a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1m3 0a.5.5 0 0 1 0 1h-1a.5.5 0 0 1 0-1z" />
    <path d="M7 6V5H2.5a2.5 2.5 0 1 0 0 5h4V9h-4a1.5 1.5 0 0 1 0-3z" />
    <path d="M2.5 14a2.5 2.5 0 0 1-.164-4.995L2.5 9h4a.5.5 0 0 1 .09.992L6.5 10h-4a1.5 1.5 0 0 0-.144 2.993L2.5 13h4a.5.5 0 0 1 0 1z" />
    <path d="M2.5 11h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1 0-1M9 11v4h6v-4zm0-1h6a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1" />
    <path d="M12 12a1 1 0 1 1 0 2 1 1 0 0 1 0-2M13 10V8.8c0-.417-.426-.8-1-.8s-1 .383-1 .8V10h-1V8.8c0-.994.895-1.8 2-1.8s2 .806 2 1.8V10z" />
  </svg>
);
const ForwardRef = forwardRef(DataAuthorize);
export default ForwardRef;
