// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Explore = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14m0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16" />
    <path d="m9.238 9.238 1.858-4.334-4.334 1.858 2.477 2.477zM6 6l5.851-2.508a.5.5 0 0 1 .657.657L10 10l-5.851 2.508a.5.5 0 0 1-.657-.657z" />
  </svg>
);
const ForwardRef = forwardRef(Explore);
export default ForwardRef;
