// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Growth = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M4 6a2 2 0 1 0 .001-3.999A2 2 0 0 0 4 6m0 1a3 3 0 1 1 0-6 3 3 0 0 1 0 6m8 7a2 2 0 1 0 .001-3.999A2 2 0 0 0 12 14m0 1a3 3 0 1 1 0-6 3 3 0 0 1 0 6M.646 14.646l13-13c.471-.471 1.179.236.707.707l-13 13c-.471.471-1.179-.236-.707-.707" />
    <path d="M14.5 1a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V2h-3.5a.5.5 0 0 1 0-1z" />
  </svg>
);
const ForwardRef = forwardRef(Growth);
export default ForwardRef;
