// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Menu = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M2 1h12a1 1 0 0 1 0 2H2a1 1 0 0 1 0-2M2 7h12a1 1 0 0 1 0 2H2a1 1 0 0 1 0-2M2 13h12a1 1 0 0 1 0 2H2a1 1 0 0 1 0-2" />
  </svg>
);
const ForwardRef = forwardRef(Menu);
export default ForwardRef;
