// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Message = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M10.68 14.266a.5.5 0 1 1-.679.733L10 15l-2-2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2a.5.5 0 0 1 0-1h2a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h6.414z" />
    <path d="M3.5 5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1 0-1M3.5 8h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1" />
  </svg>
);
const ForwardRef = forwardRef(Message);
export default ForwardRef;
