// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PublicOpinion = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M4 13h7a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h.667L4 14zm1 1v2l-2.667-2H2a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2z" />
    <path d="M13.586 7H14a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v3H5V2a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2l-1 1V8h-.414z" />
    <path d="M9 8.242c.2-1.109-.107-1.243-.6-1.243-.244 0-.604.284-1.043 1.014a1 1 0 0 1-1.715 0c-.438-.73-.798-1.014-1.043-1.014-.493 0-.8.134-.6 1.243.112.623.795 1.54 2.5 2.593 1.705-1.053 2.388-1.972 2.5-2.593zM6.5 7.5C6.614 7.311 7 6 8.4 6c1 0 1.8.5 1.6 2.243C9.868 9.396 8.833 10.657 6.5 12 4.167 10.657 3.132 9.397 3 8.243 2.8 6.5 3.6 6 4.6 6 6 6 6.386 7.311 6.5 7.5" />
  </svg>
);
const ForwardRef = forwardRef(PublicOpinion);
export default ForwardRef;
