// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PushMessage = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M2 2a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1zm0-1h12a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2" />
    <path d="M3.5 4h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1 0-1M2.5 12h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1 0-1M4.5 15h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1M3.5 6h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1" />
  </svg>
);
const ForwardRef = forwardRef(PushMessage);
export default ForwardRef;
