// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Shield = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M2.927 10.618C4.09 12.909 5.766 14.34 8 14.966c2.234-.626 3.91-2.057 5.073-4.348.551-1.726.575-4.661.037-8.752l-5.109-.852-5.109.852c-.538 4.091-.515 7.026.037 8.752zM2 1l6-1 6 1q1 7 0 10-2 4-6 5-4-1-6-5Q1 8 2 1" />
    <path d="M4.571 4.995a.5.5 0 0 1-.142-.99l3.5-.5h.141l3.5.5a.5.5 0 1 1-.142.99l-3.429-.49-3.429.49z" />
  </svg>
);
const ForwardRef = forwardRef(Shield);
export default ForwardRef;
