// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Speaker = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M4 5.211v3.561l6.969 4.099a.684.684 0 0 0 1.031-.59V1.702a.685.685 0 0 0-1.031-.59zm-1-.572L10.462.25A1.684 1.684 0 0 1 13 1.702v10.579a1.684 1.684 0 0 1-2.538 1.452L3 9.344z" />
    <path d="M13.5 6h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1M14.06 9.353l1.414 1.414a.5.5 0 0 1-.707.707l-1.414-1.414a.5.5 0 0 1 .707-.707M13.353 2.768l1.414-1.414a.5.5 0 0 1 .707.707L14.06 3.475a.5.5 0 0 1-.707-.707M3 9.406 2 9v5.469C2 15.3 2.75 16 3.5 16S5 15.3 5 14.469v-4.25l-.927-.376a1 1 0 0 0-.073.376v4.25c0 .255-.278.531-.5.531s-.5-.276-.5-.531z" />
    <path d="M1 5v4h2V5zM.842 4H4v6H.842A.84.84 0 0 1 0 9.158V4.842C0 4.377.377 4 .842 4" />
  </svg>
);
const ForwardRef = forwardRef(Speaker);
export default ForwardRef;
