// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Tag = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M6.586 2H2v4.586l8 8L14.586 10zM7 1l8.293 8.293a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0L1 7V2a1 1 0 0 1 1-1z" />
    <path d="M6 5a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
  </svg>
);
const ForwardRef = forwardRef(Tag);
export default ForwardRef;
