// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const TagAuthorize = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M5 4a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
    <path d="M6.5 0a.5.5 0 0 1 .293.095l.06.051 5 5a.5.5 0 0 1-.638.765l-.069-.058L6.293.999H1.5a.5.5 0 0 0-.492.41L1 1.499v4.793l4.854 4.853a.5.5 0 0 1 .058.638l-.058.069a.5.5 0 0 1-.638.058l-.069-.058-5-5a.5.5 0 0 1-.14-.275l-.006-.079v-5A1.5 1.5 0 0 1 1.357.005l.144-.007h5z" />
    <path d="M16 9a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-2h-1v2H9V9z" />
    <path d="M15.175 10.12a.5.5 0 0 1 .651.759l-3.5 3a.5.5 0 0 1-.741-.102l-1-1.5a.5.5 0 1 1 .832-.554l.687 1.03z" />
  </svg>
);
const ForwardRef = forwardRef(TagAuthorize);
export default ForwardRef;
