// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const TagFilter = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M6.5 0a.5.5 0 0 1 .293.095l.06.051 4 4a.5.5 0 0 1-.638.765l-.069-.058L6.293.999H1.5a.5.5 0 0 0-.492.41L1 1.499v4.793l5.854 5.853a.5.5 0 0 1 .058.638l-.058.069a.5.5 0 0 1-.638.058l-.069-.058-6-6a.5.5 0 0 1-.14-.275l-.006-.079v-5A1.5 1.5 0 0 1 1.357.005l.144-.007h5z" />
    <path d="M5 4a1 1 0 1 1-2 0 1 1 0 0 1 2 0M13.5 7a.5.5 0 0 1 .09.992L13.5 8H8.587l2.293 2.675c.058.068.097.15.112.237L11 11v3.191l1 .5V11c0-.089.024-.177.069-.253l.052-.072 3-3.5a.5.5 0 0 1 .812.578l-.052.073-2.88 3.359v4.316a.5.5 0 0 1-.646.478l-.078-.031-2-1a.5.5 0 0 1-.268-.354L10 14.501v-3.315l-2.88-3.36a.5.5 0 0 1 .297-.819l.083-.006h6z" />
  </svg>
);
const ForwardRef = forwardRef(TagFilter);
export default ForwardRef;
