// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const TagNumber = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M1 6.293V1.5a.5.5 0 0 1 .5-.5h4.793l3.884 3.884a.5.5 0 0 0 .707-.707L6.707 0H1.5A1.5 1.5 0 0 0 0 1.5v5.207l.646.646a.5.5 0 0 0 .707-.707z" />
    <path d="M5 4a1 1 0 1 1-2 0 1 1 0 0 1 2 0M8 7a2 2 0 0 1 2 2v2a.5.5 0 0 1-.108.31l-.06.063-2.329 2.07a1.5 1.5 0 0 0-.495.962l-.008.16v.436L10 15v1H6v-1.435a2.5 2.5 0 0 1 .699-1.734l.14-.134L9 10.775V9.001c0-.5-.5-1-1-1-.464 0-.929.431-.993.893L7 9.001v1H6v-1l.005-.149a2 2 0 0 1 1.838-1.845zM4 7v9H3V9H2V8h1V7zM15 12a1 1 0 0 1 1 1v1l-.005.149a2 2 0 0 1-1.838 1.845L14 16a2 2 0 0 1-2-2v-1h1v1c0 .464.431.929.893.993L14 15c.464 0 .929-.431.993-.893L15 14zm0-1v1h-2v-1zm0-2c0-.5-.5-1-1-1-.464 0-.929.431-.993.893L13 9v1h-1V9l.005-.149a2 2 0 0 1 1.838-1.845L14 7a2 2 0 0 1 2 2v1a1 1 0 0 1-1 1z" />
  </svg>
);
const ForwardRef = forwardRef(TagNumber);
export default ForwardRef;
