// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Task = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M6.5 2h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1 0-1m0 12h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1 0-1m0-6h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1 0-1M1 7v2h2V7zm0-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1M4.093.209a.499.499 0 1 1 .813.581l-2.5 3.5a.5.5 0 0 1-.757.066L.136 2.869a.5.5 0 1 1 .701-.713l1.095 1.077L4.092.209zM1 13v2h2v-2zm0-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1" />
  </svg>
);
const ForwardRef = forwardRef(Task);
export default ForwardRef;
