// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import AiCalloutSvg from '@rsuite/icon-font/lib/device/AiCallout';

const AiCallout = createSvgIcon({
  as: AiCalloutSvg,
  ariaLabel: 'ai callout',
  category: 'device',
  displayName: 'AiCallout'
});

export default AiCallout;
