// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ArchiveSvg from '@rsuite/icon-font/lib/file/Archive';

const Archive = createSvgIcon({
  as: ArchiveSvg,
  ariaLabel: 'archive',
  category: 'file',
  displayName: 'Archive'
});

export default Archive;
