// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import AudioSvg from '@rsuite/icon-font/lib/av/Audio';

const Audio = createSvgIcon({
  as: AudioSvg,
  ariaLabel: 'audio',
  category: 'av',
  displayName: 'Audio'
});

export default Audio;
