// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import BatchPlusSvg from '@rsuite/icon-font/lib/action/BatchPlus';

const BatchPlus = createSvgIcon({
  as: BatchPlusSvg,
  ariaLabel: 'batch plus',
  category: 'action',
  displayName: 'BatchPlus'
});

export default BatchPlus;
