// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import BranchAuthorizeSvg from '@rsuite/icon-font/lib/flow/BranchAuthorize';

const BranchAuthorize = createSvgIcon({
  as: BranchAuthorizeSvg,
  ariaLabel: 'branch authorize',
  category: 'flow',
  displayName: 'BranchAuthorize'
});

export default BranchAuthorize;
