// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import BytedanceMicroappSvg from '@rsuite/icon-font/lib/platform/BytedanceMicroapp';

const BytedanceMicroapp = createSvgIcon({
  as: BytedanceMicroappSvg,
  ariaLabel: 'bytedance microapp',
  category: 'platform',
  displayName: 'BytedanceMicroapp'
});

export default BytedanceMicroapp;
