// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import EditColumnSvg from '@rsuite/icon-font/lib/layout/EditColumn';

const EditColumn = createSvgIcon({
  as: EditColumnSvg,
  ariaLabel: 'edit column',
  category: 'layout',
  displayName: 'EditColumn'
});

export default EditColumn;
