// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import FlowStartSvg from '@rsuite/icon-font/lib/flow/FlowStart';

const FlowStart = createSvgIcon({
  as: FlowStartSvg,
  ariaLabel: 'flow start',
  category: 'flow',
  displayName: 'FlowStart'
});

export default FlowStart;
