// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import FolderSpeakerSvg from '@rsuite/icon-font/lib/file/FolderSpeaker';

const FolderSpeaker = createSvgIcon({
  as: FolderSpeakerSvg,
  ariaLabel: 'folder speaker',
  category: 'file',
  displayName: 'FolderSpeaker'
});

export default FolderSpeaker;
