// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import GoogleSvg from '@rsuite/icon-font/lib/platform/Google';

const Google = createSvgIcon({
  as: GoogleSvg,
  ariaLabel: 'google',
  category: 'platform',
  displayName: 'Google'
});

export default Google;
