// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import IdRuleSvg from '@rsuite/icon-font/lib/people/IdRule';

const IdRule = createSvgIcon({
  as: IdRuleSvg,
  ariaLabel: 'id rule',
  category: 'people',
  displayName: 'IdRule'
});

export default IdRule;
