// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import IndirectSvg from '@rsuite/icon-font/lib/flow/Indirect';

const Indirect = createSvgIcon({
  as: IndirectSvg,
  ariaLabel: 'indirect',
  category: 'flow',
  displayName: 'Indirect'
});

export default Indirect;
