// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import InternetSearchSvg from '@rsuite/icon-font/lib/network/InternetSearch';

const InternetSearch = createSvgIcon({
  as: InternetSearchSvg,
  ariaLabel: 'internet search',
  category: 'network',
  displayName: 'InternetSearch'
});

export default InternetSearch;
