// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import KeySvg from '@rsuite/icon-font/lib/action/Key';

const Key = createSvgIcon({
  as: KeySvg,
  ariaLabel: 'key',
  category: 'action',
  displayName: 'Key'
});

export default Key;
