// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import LockSvg from '@rsuite/icon-font/lib/action/Lock';

const Lock = createSvgIcon({
  as: LockSvg,
  ariaLabel: 'lock',
  category: 'action',
  displayName: 'Lock'
});

export default Lock;
