// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import LogSvg from '@rsuite/icon-font/lib/file/Log';

const Log = createSvgIcon({
  as: LogSvg,
  ariaLabel: 'log',
  category: 'file',
  displayName: 'Log'
});

export default Log;
