// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import OffExportSvg from '@rsuite/icon-font/lib/action/OffExport';

const OffExport = createSvgIcon({
  as: OffExportSvg,
  ariaLabel: 'off export',
  category: 'action',
  displayName: 'OffExport'
});

export default OffExport;
