// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PcFillSvg from '@rsuite/icon-font/lib/device/PcFill';

const PcFill = createSvgIcon({
  as: PcFillSvg,
  ariaLabel: 'pc fill',
  category: 'device',
  displayName: 'PcFill'
});

export default PcFill;
