// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PeoplesTestSvg from '@rsuite/icon-font/lib/people/PeoplesTest';

const PeoplesTest = createSvgIcon({
  as: PeoplesTestSvg,
  ariaLabel: 'peoples test',
  category: 'people',
  displayName: 'PeoplesTest'
});

export default PeoplesTest;
