// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PeopleFolderPlusSvg from '@rsuite/icon-font/lib/people/PeopleFolderPlus';

const PeopleFolderPlus = createSvgIcon({
  as: PeopleFolderPlusSvg,
  ariaLabel: 'people folder plus',
  category: 'people',
  displayName: 'PeopleFolderPlus'
});

export default PeopleFolderPlus;
