// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PeoplesTargetSvg from '@rsuite/icon-font/lib/people/PeoplesTarget';

const PeoplesTarget = createSvgIcon({
  as: PeoplesTargetSvg,
  ariaLabel: 'peoples target',
  category: 'people',
  displayName: 'PeoplesTarget'
});

export default PeoplesTarget;
