// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PeopleRuleSvg from '@rsuite/icon-font/lib/people/PeopleRule';

const PeopleRule = createSvgIcon({
  as: PeopleRuleSvg,
  ariaLabel: 'people rule',
  category: 'people',
  displayName: 'PeopleRule'
});

export default PeopleRule;
