// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PeoplesTimeSvg from '@rsuite/icon-font/lib/people/PeoplesTime';

const PeoplesTime = createSvgIcon({
  as: PeoplesTimeSvg,
  ariaLabel: 'peoples time',
  category: 'people',
  displayName: 'PeoplesTime'
});

export default PeoplesTime;
