// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PeoplesSqlSvg from '@rsuite/icon-font/lib/people/PeoplesSql';

const PeoplesSql = createSvgIcon({
  as: PeoplesSqlSvg,
  ariaLabel: 'peoples sql',
  category: 'people',
  displayName: 'PeoplesSql'
});

export default PeoplesSql;
