// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SaveSvg from '@rsuite/icon-font/lib/action/Save';

const Save = createSvgIcon({
  as: SaveSvg,
  ariaLabel: 'save',
  category: 'action',
  displayName: 'Save'
});

export default Save;
