// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SearchDataLiveSvg from '@rsuite/icon-font/lib/file/SearchDataLive';

const SearchDataLive = createSvgIcon({
  as: SearchDataLiveSvg,
  ariaLabel: 'search data live',
  category: 'file',
  displayName: 'SearchDataLive'
});

export default SearchDataLive;
