// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SiteSettingSvg from '@rsuite/icon-font/lib/layout/SiteSetting';

const SiteSetting = createSvgIcon({
  as: SiteSettingSvg,
  ariaLabel: 'site setting',
  category: 'layout',
  displayName: 'SiteSetting'
});

export default SiteSetting;
