// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SiteParsingSvg from '@rsuite/icon-font/lib/layout/SiteParsing';

const SiteParsing = createSvgIcon({
  as: SiteParsingSvg,
  ariaLabel: 'site parsing',
  category: 'layout',
  displayName: 'SiteParsing'
});

export default SiteParsing;
