// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SortDescSvg from '@rsuite/icon-font/lib/direction/SortDesc';

const SortDesc = createSvgIcon({
  as: SortDescSvg,
  ariaLabel: 'sort desc',
  category: 'direction',
  displayName: 'SortDesc'
});

export default SortDesc;
