// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import UndoSvg from '@rsuite/icon-font/lib/action/Undo';

const Undo = createSvgIcon({
  as: UndoSvg,
  ariaLabel: 'undo',
  category: 'action',
  displayName: 'Undo'
});

export default Undo;
