// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import VerifySvg from '@rsuite/icon-font/lib/action/Verify';

const Verify = createSvgIcon({
  as: VerifySvg,
  ariaLabel: 'verify',
  category: 'action',
  displayName: 'Verify'
});

export default Verify;
