// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import WechatCustomerOutlineSvg from '@rsuite/icon-font/lib/platform/WechatCustomerOutline';

const WechatCustomerOutline = createSvgIcon({
  as: WechatCustomerOutlineSvg,
  ariaLabel: 'wechat customer outline',
  category: 'platform',
  displayName: 'WechatCustomerOutline'
});

export default WechatCustomerOutline;
