// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ZoominSvg from '@rsuite/icon-font/lib/action/Zoomin';

const Zoomin = createSvgIcon({
  as: ZoominSvg,
  ariaLabel: 'zoomin',
  category: 'action',
  displayName: 'Zoomin'
});

export default Zoomin;
