// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Audio = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M4.402 3.01 14.5 1a.5.5 0 0 1 .12.015l.087.03.04.02.059.039.071.067.048.065.041.082.013.036.011.046.01.09v9.508a2 2 0 1 1-.999-1.732L14 5.113l-9 1.89v5.995a2 2 0 1 1-.999-1.732L4 3.515a.5.5 0 0 1 .007-.103L4 3.498a.5.5 0 0 1 .015-.12l.03-.087.021-.04.039-.059.067-.071.052-.04.052-.03.08-.032.046-.011zM3 12a1 1 0 1 0 0 2 1 1 0 0 0 0-2m10-2a1 1 0 1 0 0 2 1 1 0 0 0 0-2m1-7.89-9 1.8v2.073l9-1.89z" />
  </svg>
);
const ForwardRef = forwardRef(Audio);
export default ForwardRef;
