// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Media = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M3 1v8h2v1H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v4h-1V4h-1v2H9V1zM2 7H1v1a1 1 0 0 0 1 1zm0-3H1v2h1zm0-3-.117.007A1 1 0 0 0 1 2v1h1zm8 2h1V2a1 1 0 0 0-1-1z" />
    <path d="M14 5a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2zM8 9.707l-3 2.999V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1.293l-1-1-1.646 1.646a.5.5 0 0 1-.707 0zM14 6H6a1 1 0 0 0-1 1v4.292l2.646-2.646a.5.5 0 0 1 .707 0l3.646 3.646 1.646-1.646a.5.5 0 0 1 .707 0l.646.647V7a1 1 0 0 0-1-1zm-2 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
  </svg>
);
const ForwardRef = forwardRef(Media);
export default ForwardRef;
