// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PauseOutline = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M12.323 1.268a.5.5 0 0 1-.541.841 7 7 0 1 0 2.497 2.793.5.5 0 0 1 .897-.443 8 8 0 1 1-2.852-3.191z" />
    <path d="M6.5 5a.5.5 0 0 1 .5.5v5a.5.5 0 0 1-1 0v-5a.5.5 0 0 1 .5-.5M9.5 5a.5.5 0 0 1 .5.5v5a.5.5 0 0 1-1 0v-5a.5.5 0 0 1 .5-.5" />
  </svg>
);
const ForwardRef = forwardRef(PauseOutline);
export default ForwardRef;
