// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PlayOutline = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M12.323 1.268a.5.5 0 0 1-.541.841 7 7 0 1 0 2.497 2.793.5.5 0 0 1 .897-.443 8 8 0 1 1-2.852-3.191z" />
    <path d="M7 5.993v4.015l3.118-2.007zm-1 0a1 1 0 0 1 1.541-.84l3.118 2.007q.182.117.299.299a1 1 0 0 1-.299 1.382l-3.118 2.007A1 1 0 0 1 6 10.007z" />
  </svg>
);
const ForwardRef = forwardRef(PlayOutline);
export default ForwardRef;
