// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Archive = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M1 1a1 1 0 0 0-1 1v5.5a.5.5 0 0 0 1 0V2h6.191l1.224 2.447A1 1 0 0 0 9.309 5H15v8h-4.5a.5.5 0 0 0 0 1H15a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H9.309L8.085 1.553A1 1 0 0 0 7.191 1z" />
    <path d="M.5 12a.5.5 0 0 1 0-1h6.793L5.147 8.854a.5.5 0 0 1 .707-.707l3 3a.5.5 0 0 1 0 .707l-3 3a.5.5 0 0 1-.707-.707l2.146-2.146z" />
  </svg>
);
const ForwardRef = forwardRef(Archive);
export default ForwardRef;
