// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const ChangeList = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M11.5 0A2.5 2.5 0 0 1 14 2.5v11.792l1.146-1.146a.5.5 0 0 1 .638-.058l.069.058a.5.5 0 0 1 0 .707l-2 2-.012.012q-.018.017-.039.033a1 1 0 0 1-.07.045l-.042.019-.039.014-.046.012-.033.006-.052.005h-.041l-.052-.005.072.005a.5.5 0 0 1-.191-.038l-.041-.019-.035-.02a.5.5 0 0 1-.087-.069l.051.045a.3.3 0 0 1-.039-.033l-.012-.012-2-2a.5.5 0 0 1 .707-.707l1.146 1.146V2.5a1.5 1.5 0 0 0-1.5-1.5h-4.5a.5.5 0 0 1 0-1h4.5zm-9 0h.012a.4.4 0 0 1 .062.005za.5.5 0 0 1 .191.038l.041.019.035.02q.047.028.087.069L2.803.101a.3.3 0 0 1 .039.033l.012.012 2 2a.5.5 0 0 1-.707.707L3.001 1.707v11.792a1.5 1.5 0 0 0 1.5 1.5h4.5a.5.5 0 0 1 0 1h-4.5a2.5 2.5 0 0 1-2.5-2.5V1.705L.855 2.853a.5.5 0 0 1-.638.058l-.069-.058a.5.5 0 0 1 0-.707l2-2L2.16.134q.018-.017.039-.033a1 1 0 0 1 .07-.045l.042-.019.039-.014a.4.4 0 0 1 .077-.018A1 1 0 0 1 2.491 0h.011z" />
    <path d="M5.5 5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1M5.5 8h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1M5.5 11h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1 0-1" />
  </svg>
);
const ForwardRef = forwardRef(ChangeList);
export default ForwardRef;
