// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Email = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M2 3a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1zm0-1h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2" />
    <path d="M15.393 2.691a.5.5 0 0 1-.019.64l-.066.062-5.157 4.052 3.702 3.701a.5.5 0 0 1-.638.765l-.069-.058L9.36 8.066l-1.051.826a.5.5 0 0 1-.536.052l-.082-.052-1.052-.826-3.785 3.787a.5.5 0 0 1-.765-.638l.058-.069 3.701-3.701L.692 3.393a.5.5 0 0 1 .542-.835l.076.049 6.691 5.257 6.691-5.257a.5.5 0 0 1 .702.084z" />
  </svg>
);
const ForwardRef = forwardRef(Email);
export default ForwardRef;
