// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const EmailFill = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="m0 4.605 7.717 5.307.076.043a.5.5 0 0 0 .398.007l.092-.05 7.716-5.306V12a2 2 0 0 1-2 2h-12a2 2 0 0 1-2-2V4.605zM14 2a2 2 0 0 1 1.923 1.447L7.999 8.892.078 3.446A2 2 0 0 1 2 2z" />
  </svg>
);
const ForwardRef = forwardRef(EmailFill);
export default ForwardRef;
