// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const FolderVerify = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M6.586 2c.349 0 .684.119.951.338l.11.1 1.414 1.419a.5.5 0 0 0 .274.137l.08.006h5.586c.728 0 .97.197.997.861l.003.139v.5a.5.5 0 0 1-.992.09l-.008-.09L15 5H9.415c-.349 0-.684-.119-.951-.338l-.11-.1-1.413-1.419a.5.5 0 0 0-.274-.137L6.587 3H1l.001 10h5.5a.5.5 0 0 1 .09.992l-.09.008h-5.5c-.728 0-.97-.197-.997-.861L.001 13V3c0-.728.197-.97.861-.997L1.001 2h5.586z" />
    <path d="M8.146 9.146a.5.5 0 0 1 .638-.058l.069.058 3 3a.5.5 0 0 1 .058.638l-.058.069-3 3a.5.5 0 0 1-.765-.638l.058-.069 2.647-2.646-2.647-2.646a.5.5 0 0 1-.058-.638zM15.854 7.146a.5.5 0 0 0-.638-.058l-.069.058-3 3a.5.5 0 0 0-.058.638l.058.069 3 3a.5.5 0 0 0 .765-.638l-.058-.069-2.647-2.646 2.647-2.646a.5.5 0 0 0 .058-.638l-.058-.069z" />
  </svg>
);
const ForwardRef = forwardRef(FolderVerify);
export default ForwardRef;
