// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const FolderSpeaker = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M6.586 2c.349 0 .684.119.951.338l.11.1 1.414 1.419a.5.5 0 0 0 .274.137l.08.006h5.586c.728 0 .97.197.997.861l.003.139v.5a.5.5 0 0 1-.992.09l-.008-.09L15 5H9.415c-.349 0-.684-.119-.951-.338l-.11-.1-1.413-1.419a.5.5 0 0 0-.274-.137L6.587 3H1l.001 10h4.5a.5.5 0 0 1 .09.992l-.09.008h-4.5c-.728 0-.97-.197-.997-.861L.001 13V3c0-.728.197-.97.861-.997L1.001 2h5.586z" />
    <path d="M15.867 7.751c.088.189.133.397.133.608v5.283c0 .75-.566 1.358-1.263 1.358-.196 0-.389-.049-.565-.143L12 13.689v.811c0 .782-.664 1.421-1.368 1.493L10.5 16c-.706 0-1.412-.592-1.492-1.355L9 14.5V13H7.842A.84.84 0 0 1 7 12.158V9.842C7 9.377 7.377 9 7.842 9h2.877l3.453-1.856c.624-.336 1.383-.064 1.695.608zM10.719 13H10v1.5c0 .216.21.443.421.491L10.5 15c.208 0 .441-.203.491-.419L11 14.5v-1.349zm3.982-4.996-.056.02-3.646 1.96v2.031l3.646 1.961a.2.2 0 0 0 .046.018l.046.006c.11 0 .225-.106.255-.271l.008-.087V8.359a.4.4 0 0 0-.018-.127l-.022-.059c-.062-.132-.164-.187-.259-.169M10 10H8v2h2z" />
  </svg>
);
const ForwardRef = forwardRef(FolderSpeaker);
export default ForwardRef;
