// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Page = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M9.586 16a1 1 0 0 0 .608-.206l.099-.087L14 12a1 1 0 0 0-1-1H9.5a.5.5 0 0 0-.5.5V15H3a1 1 0 0 1-.993-.883L2 14V2a1 1 0 0 1 .883-.993L3 1h9a1 1 0 0 1 .993.883L13 2v6.5a.5.5 0 0 0 .992.09L14 8.5V2A2 2 0 0 0 12.149.005L12 0H3a2 2 0 0 0-1.995 1.851L1 2v12c0 1.054.816 1.918 1.851 1.995L3 16zM10 14.585V12h2.585z" />
    <path d="M4.5 10h3a.5.5 0 0 0 0-1h-3a.5.5 0 0 0 0 1M4.5 13h3a.5.5 0 0 0 0-1h-3a.5.5 0 0 0 0 1M4.5 7h6a.5.5 0 0 0 0-1h-6a.5.5 0 0 0 0 1M4.5 4h6a.5.5 0 0 0 0-1h-6a.5.5 0 0 0 0 1" />
  </svg>
);
const ForwardRef = forwardRef(Page);
export default ForwardRef;
