// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Paragraph = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M1.5 1h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1M5.5 4h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1M1.5 7h12a.5.5 0 0 1 0 1h-12a.5.5 0 0 1 0-1M1.5 4h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1M1.5 10h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1M8.5 10h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1M8.5 13a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1M5.5 13h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1 0-1M1.5 13h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1" />
  </svg>
);
const ForwardRef = forwardRef(Paragraph);
export default ForwardRef;
