// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const SearchDataLive = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M12 4.5V2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h4.5a.5.5 0 0 1 0 1H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v2.5a.5.5 0 0 1-1 0" />
    <path d="M3 6.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .41.787A4.5 4.5 0 0 1 9.5 5c.764 0 1.484.191 2.115.527a.5.5 0 1 1-.471.882 3.5 3.5 0 1 0 1.745 2.215.5.5 0 1 1 .969-.249q.14.541.142 1.125a4.48 4.48 0 0 1-.984 2.809l2.838 2.838a.5.5 0 0 1-.707.707l-2.838-2.838A4.48 4.48 0 0 1 9.5 14a4.49 4.49 0 0 1-3.59-1.787.5.5 0 0 1-.41.787h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .39.187C5.331 11.437 5 10.507 5 9.5s.331-1.937.89-2.687A.5.5 0 0 1 5.5 7h-2a.5.5 0 0 1-.5-.5" />
    <path d="M5 9.5a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1 0-1h1a.5.5 0 0 1 .5.5M3.5 3a.5.5 0 0 0 0 1h6a.5.5 0 0 0 0-1zM10 7.5a.5.5 0 0 0-1 0v2a.5.5 0 0 0 .276.447l2 1a.5.5 0 0 0 .447-.895L9.999 9.19V7.499z" />
  </svg>
);
const ForwardRef = forwardRef(SearchDataLive);
export default ForwardRef;
