// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Calendar = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M4.5 7a.5.5 0 0 1 .5.5v5a.5.5 0 0 1-1 0v-5a.5.5 0 0 1 .5-.5M7.5 7a.5.5 0 0 1 .5.5v5a.5.5 0 0 1-1 0v-5a.5.5 0 0 1 .5-.5M10.5 7a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0v-1a.5.5 0 0 1 .5-.5" />
    <path d="M1 8h10.5a.5.5 0 0 1 0 1H1zm0 3h7.5a.5.5 0 0 1 0 1H1zM1 5h14v1H1z" />
    <path d="M4.5 1a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5M11.5 1a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5M14.5 11a.5.5 0 0 1 .492.41l.008.09v1a2.5 2.5 0 0 1-2.336 2.495L12.5 15h-3a.5.5 0 0 1-.09-.992L9.5 14h3a1.5 1.5 0 0 0 1.493-1.356L14 12.5v-1a.5.5 0 0 1 .5-.5" />
    <path d="M13 3a2 2 0 0 1 2 2v3c0 2-2 3-4 3q1 2-1 4H3a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2zm.117 1.007L13 4H3a1 1 0 0 0-.993.883L2 5v8a1 1 0 0 0 .883.993L3 14h6.566l.031-.033c.738-.856.9-1.608.575-2.375l-.067-.144a1 1 0 0 1 .894-1.447c1.692 0 2.9-.76 2.994-1.861l.006-.139v-3a1 1 0 0 0-.883-.993z" />
  </svg>
);
const ForwardRef = forwardRef(Calendar);
export default ForwardRef;
