// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const CalenderSimple = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M4.5 0a.5.5 0 0 1 .5.5V2h6V.5a.5.5 0 0 1 1 0V2h1.5A1.5 1.5 0 0 1 15 3.5V6H2v7.5a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 1 0v3a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 1 13.5v-10A1.5 1.5 0 0 1 2.5 2H4V.5a.5.5 0 0 1 .5-.5M14 5V3.5a.5.5 0 0 0-.5-.5H12v2zm-3 0V3H5v2zM4 5V3H2.5a.5.5 0 0 0-.5.5V5z" />
    <path d="M5 8v1H4V8zM8 8H7v1h1zM10 8h1v1h-1zM5 12v-1H4v1zM7 11h1v1H7zM11 11h-1v1h1z" />
  </svg>
);
const ForwardRef = forwardRef(CalenderSimple);
export default ForwardRef;
