// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const DateTask = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M3 .5a.5.5 0 0 1 1 0V2h6V.5a.5.5 0 0 1 1 0V2h1.5a1.5 1.5 0 0 1 1.493 1.356L14 3.5V7a.5.5 0 0 1-.992.09L13 7V5H1v7.5a.5.5 0 0 0 .41.492L1.5 13H3a.5.5 0 0 1 .09.992L3 14H1.5a1.5 1.5 0 0 1-1.493-1.355L0 12.5v-9a1.5 1.5 0 0 1 1.356-1.493L1.5 2H3zM10 3H4v.5a.5.5 0 0 1-1 0V3H1.5a.5.5 0 0 0-.492.41L1 3.5V4h12v-.5a.5.5 0 0 0-.41-.492L12.5 3H11v.5a.5.5 0 0 1-1 0z" />
    <path d="M10 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5M10.5 12a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1zM10 15.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5M6.5 15a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1zM8.854 8.146a.5.5 0 0 1 0 .707l-2 2a.5.5 0 0 1-.707 0l-1-1a.5.5 0 0 1 .707-.707l.646.646 1.646-1.646a.5.5 0 0 1 .707 0zM8.854 11.854a.5.5 0 0 0-.707-.707l-1.646 1.646-.646-.646a.5.5 0 0 0-.707.707l1 1a.5.5 0 0 0 .707 0z" />
  </svg>
);
const ForwardRef = forwardRef(DateTask);
export default ForwardRef;
