// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const HistoryTask = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M2 .5v1.601A7 7 0 0 1 14 7a.5.5 0 0 1-1 0A6 6 0 0 0 2.528 3H4.5a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5v-3a.5.5 0 0 1 1 0M1.071 7.924a.5.5 0 0 0-.988.152 7 7 0 0 0 2.61 4.441.5.5 0 1 0 .616-.788 6 6 0 0 1-2.237-3.806zM8.854 8.854a.5.5 0 0 0-.707-.707L6.501 9.793l-.646-.646a.5.5 0 0 0-.707.707l1 1a.5.5 0 0 0 .707 0zM10 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5M10 12.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5M10.5 15a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1zM6 15.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5M8.854 11.146a.5.5 0 0 1 0 .707l-2 2a.5.5 0 0 1-.707 0l-1-1a.5.5 0 0 1 .707-.707l.646.646 1.646-1.646a.5.5 0 0 1 .707 0z" />
    <path d="M10.825 4.88a.5.5 0 1 0-.651-.759L6.878 6.946 3.637 6.02a.5.5 0 1 0-.275.961l3.5 1a.5.5 0 0 0 .463-.101z" />
  </svg>
);
const ForwardRef = forwardRef(HistoryTask);
export default ForwardRef;
