// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const History = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M7.5 1a7.5 7.5 0 1 1-6.07 11.906.5.5 0 0 1 .808-.588 6.5 6.5 0 1 0 .154-7.839.5.5 0 1 1-.785-.619A7.49 7.49 0 0 1 7.5 1" />
    <path d="M1.5 0a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0v-4a.5.5 0 0 1 .5-.5" />
    <path d="M1.5 4h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1M7.597 9.999l-.053.008h-.075l-.04-.006a.5.5 0 0 1-.212-.089L4.224 7.915c-.555-.37 0-1.202.555-.832l2.659 1.772 3.711-3.71c.471-.471 1.179.236.707.707L7.869 9.84a.5.5 0 0 1-.197.137l-.073.021zM7.5 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2a.5.5 0 0 1 .5-.5M12.5 8h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1" />
  </svg>
);
const ForwardRef = forwardRef(History);
export default ForwardRef;
