// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Time = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M10.575.423a.5.5 0 0 1-.321.947 7 7 0 1 0 3.988 3.457.5.5 0 0 1 .891-.454 8 8 0 1 1-4.557-3.95z" />
    <path d="M7.5 9a.5.5 0 0 1-.5-.5v-5a.5.5 0 0 1 1 0V8h3.5a.5.5 0 0 1 0 1z" />
  </svg>
);
const ForwardRef = forwardRef(Time);
export default ForwardRef;
