// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const AlipayMini = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M7.175.226A1.65 1.65 0 0 1 8.683.153l.142.073 5.495 3.173c.468.27.771.75.819 1.283l.006.146v6.345c0 .54-.264 1.043-.702 1.35l-.123.079-5.495 3.173a1.65 1.65 0 0 1-1.508.073l-.142-.073-5.495-3.173a1.65 1.65 0 0 1-.819-1.283l-.006-.146V4.828c0-.54.264-1.043.702-1.35l.123-.079zm4.859 8.519-6.931 4.332 2.722 1.572a.35.35 0 0 0 .282.03l.068-.03 5.495-3.173a.35.35 0 0 0 .167-.23l.008-.074V9.859l-1.811-1.115zm-9.88-1.08.001 3.508c0 .1.043.194.115.26l.06.044 1.498.865 2.939-1.837-4.613-2.839zm5.849-1.4-2.801 1.75 2.795 1.72 2.801-1.75zm4.169-2.606L9.233 5.496l4.612 2.838V4.828c0-.1-.043-.194-.115-.26l-.06-.044zM8.175 1.352a.35.35 0 0 0-.282-.03l-.068.03L2.33 4.525a.35.35 0 0 0-.167.23l-.008.074-.001 1.311 1.812 1.115 6.931-4.331-2.722-1.571z" />
  </svg>
);
const ForwardRef = forwardRef(AlipayMini);
export default ForwardRef;
