// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Bytedance = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M13.209 1 16 1.747v12.6L13.209 15zM4.372 7.253 7.163 8v5.973l-2.791.653zM0 1.747l2.791.747v11.107L0 14.254zM11.721 5.48v7.373L8.93 12.2V6.227z" />
  </svg>
);
const ForwardRef = forwardRef(Bytedance);
export default ForwardRef;
