// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Google = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8.19 0c2.113 0 3.977.782 5.364 2.065l.046.043-2.319 2.299c-.808-.717-1.878-1.151-3.091-1.151C5.507 3.256 3.333 5.38 3.333 8s2.175 4.744 4.857 4.744c2.403 0 3.917-1.32 4.451-3.163H8.19v-3.07h6.667v.007l1.048-.007c.081.468.095.996.095 1.488 0 4.744-3.286 8-7.81 8S0 12.417 0 7.999s3.667-8 8.19-8z" />
  </svg>
);
const ForwardRef = forwardRef(Google);
export default ForwardRef;
