// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const IOs = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M10.53 2.553c.599-.676 1.005-1.616.896-2.553-.866.032-1.913.535-2.534 1.212-.556.599-1.043 1.556-.913 2.476.964.068 1.95-.457 2.551-1.132zM12.694 8.5c-.021-2.025 1.777-2.997 1.857-3.047-1.01-1.373-2.585-1.563-3.145-1.585-1.338-.124-2.611.735-3.292.735-.679 0-1.728-.715-2.839-.695A4.25 4.25 0 0 0 1.72 5.913c-1.518 2.448-.388 6.076 1.089 8.06.722.973 1.582 2.065 2.714 2.025 1.088-.04 1.499-.656 2.816-.656 1.318 0 1.687.656 2.839.636 1.171-.02 1.914-.991 2.631-1.967.83-1.128 1.169-2.219 1.191-2.275-.026-.011-2.286-.816-2.309-3.237h.003z" />
  </svg>
);
const ForwardRef = forwardRef(IOs);
export default ForwardRef;
