// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const MiniProgram = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0m5.645 4.472c-1.219-1.951-4.013-2.124-5.741-.032-.704.852-.912 1.756-.91 3.09 0 .138.002.247.006.488.024 1.315-.056 1.796-.446 2.268-.861 1.043-2.01.972-2.503.182-.252-.403-.361-1.123-.219-1.663C3.974 8.268 4.304 8 5 8a1 1 0 0 0 0-2c-1.625 0-2.733.898-3.101 2.293-.284 1.075-.088 2.363.456 3.234 1.219 1.951 4.013 2.124 5.741.032.797-.965.936-1.801.904-3.578l-.005-.308-.001-.147c-.001-.911.111-1.401.452-1.813.861-1.043 2.01-.972 2.503-.182.252.403.361 1.123.219 1.663-.142.537-.472.805-1.168.805a1 1 0 0 0 0 2c1.625 0 2.733-.898 3.101-2.293.284-1.075.088-2.363-.456-3.234" />
  </svg>
);
const ForwardRef = forwardRef(MiniProgram);
export default ForwardRef;
