// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Wechat = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M6 1c3.5 0 6 2 6 5-1.5 0-3.272.8-4 1.8-.686.943-1.2 2.389-.8 4-.4.2-.927.2-1.2.2a6.5 6.5 0 0 1-2.221-.389L1 13l.673-2.69C.637 9.322 0 7.979 0 6.5 0 3.462 2.5 1 6 1M3.75 4a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5m4 0a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5" />
    <path d="M12 7c2.231 0 4 1.5 4 3.75 0 .95-.436 2.095-1.208 2.754L15 15l-1.727-.681c-.406.12-.834.181-1.273.181-2.231 0-4-1.5-4-3.75S9.769 7 12 7m-1.25 2a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5m3 0a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5" />
  </svg>
);
const ForwardRef = forwardRef(Wechat);
export default ForwardRef;
