// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const WechatSubmessageOutline = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="m13.321 13.406.471-.402C14.564 12.345 15 11.45 15 10.5 15 8.592 13.231 7 11 7s-4 1.592-4 3.5S8.769 14 11 14c.439 0 .867-.062 1.273-.181l.378-.111.852.426-.182-.727zM15 16l-2.444-1.222A5.5 5.5 0 0 1 11 15c-2.761 0-5-2.015-5-4.5S8.239 6 11 6s5 2.015 5 4.5c0 1.285-.599 2.445-1.559 3.265zm-5.5-6a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1m3 0a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1" />
    <path d="M12 0a2 2 0 0 1 2 2v2.5a.5.5 0 0 1-1 0V2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h3.5a.5.5 0 0 1 0 1H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zM4.5 12a.5.5 0 0 1 0 1h-1a.5.5 0 0 1 0-1zm0-3a.5.5 0 0 1 0 1h-1a.5.5 0 0 1 0-1zm1-3a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm4-3a.5.5 0 0 1 0 1h-6a.5.5 0 0 1 0-1z" />
  </svg>
);
const ForwardRef = forwardRef(WechatSubmessageOutline);
export default ForwardRef;
