// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Export = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M4 15c-2.25-.276-4-2.184-4-4.5a4.5 4.5 0 0 1 3.006-4.246 5 5 0 0 1 9.899-1.231 3.5 3.5 0 0 1 3.09 3.286L16 8.5a.5.5 0 0 1-1 0 2.5 2.5 0 0 0-2.21-2.483l-.725-.083-.142-.716a4.002 4.002 0 0 0-7.924.783L4 6.103l.041.847-.704.248a3.5 3.5 0 0 0-2.338 3.303c0 1.768 1.32 3.258 3.065 3.5h1.435a.5.5 0 0 1 0 1z" />
    <path d="m11.854 8.146 3 3a.5.5 0 0 1 0 .707l-3 3a.5.5 0 0 1-.707-.707L13.293 12H6.501a.5.5 0 0 1 0-1h6.793l-2.147-2.146a.5.5 0 0 1 .707-.707z" />
  </svg>
);
const ForwardRef = forwardRef(Export);
export default ForwardRef;
