// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Import = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="m5.854 8.146 3 3a.5.5 0 0 1 0 .707l-3 3a.5.5 0 0 1-.707-.707L7.293 12H.501a.5.5 0 0 1 0-1h6.793L5.147 8.854a.5.5 0 0 1 .707-.707z" />
    <path d="M.005 8.309a3.5 3.5 0 0 1 3.09-3.286 5.002 5.002 0 0 1 9.899 1.231A4.5 4.5 0 0 1 16 10.5c0 2.244-1.642 4.104-3.791 4.469L12 15h-1.5a.5.5 0 0 1 0-1h1.435C13.68 13.758 15 12.268 15 10.5a3.5 3.5 0 0 0-2.159-3.234l-.179-.068-.704-.248.037-.746Q12 6.102 12 6a4 4 0 0 0-7.879-.98l-.044.197-.142.716-.725.083a2.5 2.5 0 0 0-2.204 2.319l-.005.165a.5.5 0 0 1-1 0l.005-.191z" />
  </svg>
);
const ForwardRef = forwardRef(Import);
export default ForwardRef;
