// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AdnSvg from '@rsuite/icon-font/lib/legacy/Adn';

const Adn = createSvgIcon({
  as: AdnSvg,
  ariaLabel: 'adn',
  category: 'legacy',
  displayName: 'Adn'
});

export default Adn;
