// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AmazonSvg from '@rsuite/icon-font/lib/legacy/Amazon';

const Amazon = createSvgIcon({
  as: AmazonSvg,
  ariaLabel: 'amazon',
  category: 'legacy',
  displayName: 'Amazon'
});

export default Amazon;
