// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AndroidSvg from '@rsuite/icon-font/lib/legacy/Android';

const Android = createSvgIcon({
  as: AndroidSvg,
  ariaLabel: 'android',
  category: 'legacy',
  displayName: 'Android'
});

export default Android;
