// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AngleDoubleUpSvg from '@rsuite/icon-font/lib/legacy/AngleDoubleUp';

const AngleDoubleUp = createSvgIcon({
  as: AngleDoubleUpSvg,
  ariaLabel: 'angle double up',
  category: 'legacy',
  displayName: 'AngleDoubleUp'
});

export default AngleDoubleUp;
