// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AreaChartSvg from '@rsuite/icon-font/lib/legacy/AreaChart';

const AreaChart = createSvgIcon({
  as: AreaChartSvg,
  ariaLabel: 'area chart',
  category: 'legacy',
  displayName: 'AreaChart'
});

export default AreaChart;
