// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowLeftSvg from '@rsuite/icon-font/lib/legacy/ArrowLeft';

const ArrowLeft = createSvgIcon({
  as: ArrowLeftSvg,
  ariaLabel: 'arrow left',
  category: 'legacy',
  displayName: 'ArrowLeft'
});

export default ArrowLeft;
