// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowCircleORightSvg from '@rsuite/icon-font/lib/legacy/ArrowCircleORight';

const ArrowCircleORight = createSvgIcon({
  as: ArrowCircleORightSvg,
  ariaLabel: 'arrow circle o right',
  category: 'legacy',
  displayName: 'ArrowCircleORight'
});

export default ArrowCircleORight;
