// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AttributionSvg from '@rsuite/icon-font/lib/legacy/Attribution';

const Attribution = createSvgIcon({
  as: AttributionSvg,
  ariaLabel: 'attribution',
  category: 'legacy',
  displayName: 'Attribution'
});

export default Attribution;
