// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BackArrowSvg from '@rsuite/icon-font/lib/legacy/BackArrow';

const BackArrow = createSvgIcon({
  as: BackArrowSvg,
  ariaLabel: 'back arrow',
  category: 'legacy',
  displayName: 'BackArrow'
});

export default BackArrow;
