// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BandcampSvg from '@rsuite/icon-font/lib/legacy/Bandcamp';

const Bandcamp = createSvgIcon({
  as: BandcampSvg,
  ariaLabel: 'bandcamp',
  category: 'legacy',
  displayName: 'Bandcamp'
});

export default Bandcamp;
