// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BankSvg from '@rsuite/icon-font/lib/legacy/Bank';

const Bank = createSvgIcon({
  as: BankSvg,
  ariaLabel: 'bank',
  category: 'legacy',
  displayName: 'Bank'
});

export default Bank;
