// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BarChartSvg from '@rsuite/icon-font/lib/legacy/BarChart';

const BarChart = createSvgIcon({
  as: BarChartSvg,
  ariaLabel: 'bar chart',
  category: 'legacy',
  displayName: 'BarChart'
});

export default BarChart;
