// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BedSvg from '@rsuite/icon-font/lib/legacy/Bed';

const Bed = createSvgIcon({
  as: BedSvg,
  ariaLabel: 'bed',
  category: 'legacy',
  displayName: 'Bed'
});

export default Bed;
