// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BehanceSvg from '@rsuite/icon-font/lib/legacy/Behance';

const Behance = createSvgIcon({
  as: BehanceSvg,
  ariaLabel: 'behance',
  category: 'legacy',
  displayName: 'Behance'
});

export default Behance;
