// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BellSlashOSvg from '@rsuite/icon-font/lib/legacy/BellSlashO';

const BellSlashO = createSvgIcon({
  as: BellSlashOSvg,
  ariaLabel: 'bell slash o',
  category: 'legacy',
  displayName: 'BellSlashO'
});

export default BellSlashO;
