// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BirthdayCakeSvg from '@rsuite/icon-font/lib/legacy/BirthdayCake';

const BirthdayCake = createSvgIcon({
  as: BirthdayCakeSvg,
  ariaLabel: 'birthday cake',
  category: 'legacy',
  displayName: 'BirthdayCake'
});

export default BirthdayCake;
