// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BluetoothSvg from '@rsuite/icon-font/lib/legacy/Bluetooth';

const Bluetooth = createSvgIcon({
  as: BluetoothSvg,
  ariaLabel: 'bluetooth',
  category: 'legacy',
  displayName: 'Bluetooth'
});

export default Bluetooth;
