// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BoltSvg from '@rsuite/icon-font/lib/legacy/Bolt';

const Bolt = createSvgIcon({
  as: BoltSvg,
  ariaLabel: 'bolt',
  category: 'legacy',
  displayName: 'Bolt'
});

export default Bolt;
