// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BombSvg from '@rsuite/icon-font/lib/legacy/Bomb';

const Bomb = createSvgIcon({
  as: BombSvg,
  ariaLabel: 'bomb',
  category: 'legacy',
  displayName: 'Bomb'
});

export default Bomb;
