// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BookSvg from '@rsuite/icon-font/lib/legacy/Book';

const Book = createSvgIcon({
  as: BookSvg,
  ariaLabel: 'book',
  category: 'legacy',
  displayName: 'Book'
});

export default Book;
