// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BookmarkOSvg from '@rsuite/icon-font/lib/legacy/BookmarkO';

const BookmarkO = createSvgIcon({
  as: BookmarkOSvg,
  ariaLabel: 'bookmark o',
  category: 'legacy',
  displayName: 'BookmarkO'
});

export default BookmarkO;
