// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BtcSvg from '@rsuite/icon-font/lib/legacy/Btc';

const Btc = createSvgIcon({
  as: BtcSvg,
  ariaLabel: 'btc',
  category: 'legacy',
  displayName: 'Btc'
});

export default Btc;
