// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CalendarCheckOSvg from '@rsuite/icon-font/lib/legacy/CalendarCheckO';

const CalendarCheckO = createSvgIcon({
  as: CalendarCheckOSvg,
  ariaLabel: 'calendar check o',
  category: 'legacy',
  displayName: 'CalendarCheckO'
});

export default CalendarCheckO;
