// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CaretDownSvg from '@rsuite/icon-font/lib/legacy/CaretDown';

const CaretDown = createSvgIcon({
  as: CaretDownSvg,
  ariaLabel: 'caret down',
  category: 'legacy',
  displayName: 'CaretDown'
});

export default CaretDown;
