// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ChevronCircleDownSvg from '@rsuite/icon-font/lib/legacy/ChevronCircleDown';

const ChevronCircleDown = createSvgIcon({
  as: ChevronCircleDownSvg,
  ariaLabel: 'chevron circle down',
  category: 'legacy',
  displayName: 'ChevronCircleDown'
});

export default ChevronCircleDown;
