// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ChromeSvg from '@rsuite/icon-font/lib/legacy/Chrome';

const Chrome = createSvgIcon({
  as: ChromeSvg,
  ariaLabel: 'chrome',
  category: 'legacy',
  displayName: 'Chrome'
});

export default Chrome;
