// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CircleOSvg from '@rsuite/icon-font/lib/legacy/CircleO';

const CircleO = createSvgIcon({
  as: CircleOSvg,
  ariaLabel: 'circle o',
  category: 'legacy',
  displayName: 'CircleO'
});

export default CircleO;
