// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CoffeeSvg from '@rsuite/icon-font/lib/legacy/Coffee';

const Coffee = createSvgIcon({
  as: CoffeeSvg,
  ariaLabel: 'coffee',
  category: 'legacy',
  displayName: 'Coffee'
});

export default Coffee;
