// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CogSvg from '@rsuite/icon-font/lib/legacy/Cog';

const Cog = createSvgIcon({
  as: CogSvg,
  ariaLabel: 'cog',
  category: 'legacy',
  displayName: 'Cog'
});

export default Cog;
