// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CommentOSvg from '@rsuite/icon-font/lib/legacy/CommentO';

const CommentO = createSvgIcon({
  as: CommentOSvg,
  ariaLabel: 'comment o',
  category: 'legacy',
  displayName: 'CommentO'
});

export default CommentO;
