// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CommentSvg from '@rsuite/icon-font/lib/legacy/Comment';

const Comment = createSvgIcon({
  as: CommentSvg,
  ariaLabel: 'comment',
  category: 'legacy',
  displayName: 'Comment'
});

export default Comment;
