// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CommentsSvg from '@rsuite/icon-font/lib/legacy/Comments';

const Comments = createSvgIcon({
  as: CommentsSvg,
  ariaLabel: 'comments',
  category: 'legacy',
  displayName: 'Comments'
});

export default Comments;
