// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CreditCardAltSvg from '@rsuite/icon-font/lib/legacy/CreditCardAlt';

const CreditCardAlt = createSvgIcon({
  as: CreditCardAltSvg,
  ariaLabel: 'credit card alt',
  category: 'legacy',
  displayName: 'CreditCardAlt'
});

export default CreditCardAlt;
