// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CrosshairsSvg from '@rsuite/icon-font/lib/legacy/Crosshairs';

const Crosshairs = createSvgIcon({
  as: CrosshairsSvg,
  ariaLabel: 'crosshairs',
  category: 'legacy',
  displayName: 'Crosshairs'
});

export default Crosshairs;
