// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CubesSvg from '@rsuite/icon-font/lib/legacy/Cubes';

const Cubes = createSvgIcon({
  as: CubesSvg,
  ariaLabel: 'cubes',
  category: 'legacy',
  displayName: 'Cubes'
});

export default Cubes;
