// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CutSvg from '@rsuite/icon-font/lib/legacy/Cut';

const Cut = createSvgIcon({
  as: CutSvg,
  ariaLabel: 'cut',
  category: 'legacy',
  displayName: 'Cut'
});

export default Cut;
