// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DashboardSvg from '@rsuite/icon-font/lib/legacy/Dashboard';

const Dashboard = createSvgIcon({
  as: DashboardSvg,
  ariaLabel: 'dashboard',
  category: 'legacy',
  displayName: 'Dashboard'
});

export default Dashboard;
