// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DatabaseSvg from '@rsuite/icon-font/lib/legacy/Database';

const Database = createSvgIcon({
  as: DatabaseSvg,
  ariaLabel: 'database',
  category: 'legacy',
  displayName: 'Database'
});

export default Database;
