// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DeafSvg from '@rsuite/icon-font/lib/legacy/Deaf';

const Deaf = createSvgIcon({
  as: DeafSvg,
  ariaLabel: 'deaf',
  category: 'legacy',
  displayName: 'Deaf'
});

export default Deaf;
