// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DownSvg from '@rsuite/icon-font/lib/legacy/Down';

const Down = createSvgIcon({
  as: DownSvg,
  ariaLabel: 'down',
  category: 'legacy',
  displayName: 'Down'
});

export default Down;
