// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import EditSvg from '@rsuite/icon-font/lib/legacy/Edit';

const Edit = createSvgIcon({
  as: EditSvg,
  ariaLabel: 'edit',
  category: 'legacy',
  displayName: 'Edit'
});

export default Edit;
