// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ExclamationSvg from '@rsuite/icon-font/lib/legacy/Exclamation';

const Exclamation = createSvgIcon({
  as: ExclamationSvg,
  ariaLabel: 'exclamation',
  category: 'legacy',
  displayName: 'Exclamation'
});

export default Exclamation;
