// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ExitSvg from '@rsuite/icon-font/lib/legacy/Exit';

const Exit = createSvgIcon({
  as: ExitSvg,
  ariaLabel: 'exit',
  category: 'legacy',
  displayName: 'Exit'
});

export default Exit;
