// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ExternalLinkSquareSvg from '@rsuite/icon-font/lib/legacy/ExternalLinkSquare';

const ExternalLinkSquare = createSvgIcon({
  as: ExternalLinkSquareSvg,
  ariaLabel: 'external link square',
  category: 'legacy',
  displayName: 'ExternalLinkSquare'
});

export default ExternalLinkSquare;
