// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FileImageOSvg from '@rsuite/icon-font/lib/legacy/FileImageO';

const FileImageO = createSvgIcon({
  as: FileImageOSvg,
  ariaLabel: 'file image o',
  category: 'legacy',
  displayName: 'FileImageO'
});

export default FileImageO;
