// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FilePdfOSvg from '@rsuite/icon-font/lib/legacy/FilePdfO';

const FilePdfO = createSvgIcon({
  as: FilePdfOSvg,
  ariaLabel: 'file pdf o',
  category: 'legacy',
  displayName: 'FilePdfO'
});

export default FilePdfO;
