// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FileZipOSvg from '@rsuite/icon-font/lib/legacy/FileZipO';

const FileZipO = createSvgIcon({
  as: FileZipOSvg,
  ariaLabel: 'file zip o',
  category: 'legacy',
  displayName: 'FileZipO'
});

export default FileZipO;
