// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FilmSvg from '@rsuite/icon-font/lib/legacy/Film';

const Film = createSvgIcon({
  as: FilmSvg,
  ariaLabel: 'film',
  category: 'legacy',
  displayName: 'Film'
});

export default Film;
