// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FireExtinguisherSvg from '@rsuite/icon-font/lib/legacy/FireExtinguisher';

const FireExtinguisher = createSvgIcon({
  as: FireExtinguisherSvg,
  ariaLabel: 'fire extinguisher',
  category: 'legacy',
  displayName: 'FireExtinguisher'
});

export default FireExtinguisher;
