// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FlaskSvg from '@rsuite/icon-font/lib/legacy/Flask';

const Flask = createSvgIcon({
  as: FlaskSvg,
  ariaLabel: 'flask',
  category: 'legacy',
  displayName: 'Flask'
});

export default Flask;
