// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FlickrSvg from '@rsuite/icon-font/lib/legacy/Flickr';

const Flickr = createSvgIcon({
  as: FlickrSvg,
  ariaLabel: 'flickr',
  category: 'legacy',
  displayName: 'Flickr'
});

export default Flickr;
