// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FolderOSvg from '@rsuite/icon-font/lib/legacy/FolderO';

const FolderO = createSvgIcon({
  as: FolderOSvg,
  ariaLabel: 'folder o',
  category: 'legacy',
  displayName: 'FolderO'
});

export default FolderO;
