// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FolderSvg from '@rsuite/icon-font/lib/legacy/Folder';

const Folder = createSvgIcon({
  as: FolderSvg,
  ariaLabel: 'folder',
  category: 'legacy',
  displayName: 'Folder'
});

export default Folder;
