// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ForumbeeSvg from '@rsuite/icon-font/lib/legacy/Forumbee';

const Forumbee = createSvgIcon({
  as: ForumbeeSvg,
  ariaLabel: 'forumbee',
  category: 'legacy',
  displayName: 'Forumbee'
});

export default Forumbee;
