// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GamepadSvg from '@rsuite/icon-font/lib/legacy/Gamepad';

const Gamepad = createSvgIcon({
  as: GamepadSvg,
  ariaLabel: 'gamepad',
  category: 'legacy',
  displayName: 'Gamepad'
});

export default Gamepad;
