// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GgCircleSvg from '@rsuite/icon-font/lib/legacy/GgCircle';

const GgCircle = createSvgIcon({
  as: GgCircleSvg,
  ariaLabel: 'gg circle',
  category: 'legacy',
  displayName: 'GgCircle'
});

export default GgCircle;
