// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GiftSvg from '@rsuite/icon-font/lib/legacy/Gift';

const Gift = createSvgIcon({
  as: GiftSvg,
  ariaLabel: 'gift',
  category: 'legacy',
  displayName: 'Gift'
});

export default Gift;
