// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GitSvg from '@rsuite/icon-font/lib/legacy/Git';

const Git = createSvgIcon({
  as: GitSvg,
  ariaLabel: 'git',
  category: 'legacy',
  displayName: 'Git'
});

export default Git;
