// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GoogleWalletSvg from '@rsuite/icon-font/lib/legacy/GoogleWallet';

const GoogleWallet = createSvgIcon({
  as: GoogleWalletSvg,
  ariaLabel: 'google wallet',
  category: 'legacy',
  displayName: 'GoogleWallet'
});

export default GoogleWallet;
