// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GravSvg from '@rsuite/icon-font/lib/legacy/Grav';

const Grav = createSvgIcon({
  as: GravSvg,
  ariaLabel: 'grav',
  category: 'legacy',
  displayName: 'Grav'
});

export default Grav;
