// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GroupSvg from '@rsuite/icon-font/lib/legacy/Group';

const Group = createSvgIcon({
  as: GroupSvg,
  ariaLabel: 'group',
  category: 'legacy',
  displayName: 'Group'
});

export default Group;
