// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HandScissorsOSvg from '@rsuite/icon-font/lib/legacy/HandScissorsO';

const HandScissorsO = createSvgIcon({
  as: HandScissorsOSvg,
  ariaLabel: 'hand scissors o',
  category: 'legacy',
  displayName: 'HandScissorsO'
});

export default HandScissorsO;
