// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HashtagSvg from '@rsuite/icon-font/lib/legacy/Hashtag';

const Hashtag = createSvgIcon({
  as: HashtagSvg,
  ariaLabel: 'hashtag',
  category: 'legacy',
  displayName: 'Hashtag'
});

export default Hashtag;
