// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HelpOSvg from '@rsuite/icon-font/lib/legacy/HelpO';

const HelpO = createSvgIcon({
  as: HelpOSvg,
  ariaLabel: 'help o',
  category: 'legacy',
  displayName: 'HelpO'
});

export default HelpO;
