// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import InstagramSvg from '@rsuite/icon-font/lib/legacy/Instagram';

const Instagram = createSvgIcon({
  as: InstagramSvg,
  ariaLabel: 'instagram',
  category: 'legacy',
  displayName: 'Instagram'
});

export default Instagram;
