// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import IosSvg from '@rsuite/icon-font/lib/legacy/Ios';

const Ios = createSvgIcon({
  as: IosSvg,
  ariaLabel: 'ios',
  category: 'legacy',
  displayName: 'Ios'
});

export default Ios;
