// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import IoxhostSvg from '@rsuite/icon-font/lib/legacy/Ioxhost';

const Ioxhost = createSvgIcon({
  as: IoxhostSvg,
  ariaLabel: 'ioxhost',
  category: 'legacy',
  displayName: 'Ioxhost'
});

export default Ioxhost;
