// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ItalicSvg from '@rsuite/icon-font/lib/legacy/Italic';

const Italic = createSvgIcon({
  as: ItalicSvg,
  ariaLabel: 'italic',
  category: 'legacy',
  displayName: 'Italic'
});

export default Italic;
