// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import JsfiddleSvg from '@rsuite/icon-font/lib/legacy/Jsfiddle';

const Jsfiddle = createSvgIcon({
  as: JsfiddleSvg,
  ariaLabel: 'jsfiddle',
  category: 'legacy',
  displayName: 'Jsfiddle'
});

export default Jsfiddle;
