// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import KrwSvg from '@rsuite/icon-font/lib/legacy/Krw';

const Krw = createSvgIcon({
  as: KrwSvg,
  ariaLabel: 'krw',
  category: 'legacy',
  displayName: 'Krw'
});

export default Krw;
