// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LanguageSvg from '@rsuite/icon-font/lib/legacy/Language';

const Language = createSvgIcon({
  as: LanguageSvg,
  ariaLabel: 'language',
  category: 'legacy',
  displayName: 'Language'
});

export default Language;
