// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LastfmSvg from '@rsuite/icon-font/lib/legacy/Lastfm';

const Lastfm = createSvgIcon({
  as: LastfmSvg,
  ariaLabel: 'lastfm',
  category: 'legacy',
  displayName: 'Lastfm'
});

export default Lastfm;
