// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LeftSvg from '@rsuite/icon-font/lib/legacy/Left';

const Left = createSvgIcon({
  as: LeftSvg,
  ariaLabel: 'left',
  category: 'legacy',
  displayName: 'Left'
});

export default Left;
