// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LinkSvg from '@rsuite/icon-font/lib/legacy/Link';

const Link = createSvgIcon({
  as: LinkSvg,
  ariaLabel: 'link',
  category: 'legacy',
  displayName: 'Link'
});

export default Link;
