// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LinkedinSquareSvg from '@rsuite/icon-font/lib/legacy/LinkedinSquare';

const LinkedinSquare = createSvgIcon({
  as: LinkedinSquareSvg,
  ariaLabel: 'linkedin square',
  category: 'legacy',
  displayName: 'LinkedinSquare'
});

export default LinkedinSquare;
