// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ListSvg from '@rsuite/icon-font/lib/legacy/List';

const List = createSvgIcon({
  as: ListSvg,
  ariaLabel: 'list',
  category: 'legacy',
  displayName: 'List'
});

export default List;
