// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MaleSvg from '@rsuite/icon-font/lib/legacy/Male';

const Male = createSvgIcon({
  as: MaleSvg,
  ariaLabel: 'male',
  category: 'legacy',
  displayName: 'Male'
});

export default Male;
