// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MarsStrokeSvg from '@rsuite/icon-font/lib/legacy/MarsStroke';

const MarsStroke = createSvgIcon({
  as: MarsStrokeSvg,
  ariaLabel: 'mars stroke',
  category: 'legacy',
  displayName: 'MarsStroke'
});

export default MarsStroke;
