// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MarsDoubleSvg from '@rsuite/icon-font/lib/legacy/MarsDouble';

const MarsDouble = createSvgIcon({
  as: MarsDoubleSvg,
  ariaLabel: 'mars double',
  category: 'legacy',
  displayName: 'MarsDouble'
});

export default MarsDouble;
