// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MehOSvg from '@rsuite/icon-font/lib/legacy/MehO';

const MehO = createSvgIcon({
  as: MehOSvg,
  ariaLabel: 'meh o',
  category: 'legacy',
  displayName: 'MehO'
});

export default MehO;
