// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MicrochipSvg from '@rsuite/icon-font/lib/legacy/Microchip';

const Microchip = createSvgIcon({
  as: MicrochipSvg,
  ariaLabel: 'microchip',
  category: 'legacy',
  displayName: 'Microchip'
});

export default Microchip;
