// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MinusSvg from '@rsuite/icon-font/lib/legacy/Minus';

const Minus = createSvgIcon({
  as: MinusSvg,
  ariaLabel: 'minus',
  category: 'legacy',
  displayName: 'Minus'
});

export default Minus;
