// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MixcloudSvg from '@rsuite/icon-font/lib/legacy/Mixcloud';

const Mixcloud = createSvgIcon({
  as: MixcloudSvg,
  ariaLabel: 'mixcloud',
  category: 'legacy',
  displayName: 'Mixcloud'
});

export default Mixcloud;
