// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MoneySvg from '@rsuite/icon-font/lib/legacy/Money';

const Money = createSvgIcon({
  as: MoneySvg,
  ariaLabel: 'money',
  category: 'legacy',
  displayName: 'Money'
});

export default Money;
