// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MoonOSvg from '@rsuite/icon-font/lib/legacy/MoonO';

const MoonO = createSvgIcon({
  as: MoonOSvg,
  ariaLabel: 'moon o',
  category: 'legacy',
  displayName: 'MoonO'
});

export default MoonO;
