// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ObjectGroupSvg from '@rsuite/icon-font/lib/legacy/ObjectGroup';

const ObjectGroup = createSvgIcon({
  as: ObjectGroupSvg,
  ariaLabel: 'object group',
  category: 'legacy',
  displayName: 'ObjectGroup'
});

export default ObjectGroup;
