// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import OffSvg from '@rsuite/icon-font/lib/legacy/Off';

const Off = createSvgIcon({
  as: OffSvg,
  ariaLabel: 'off',
  category: 'legacy',
  displayName: 'Off'
});

export default Off;
