// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import OpenidSvg from '@rsuite/icon-font/lib/legacy/Openid';

const Openid = createSvgIcon({
  as: OpenidSvg,
  ariaLabel: 'openid',
  category: 'legacy',
  displayName: 'Openid'
});

export default Openid;
