// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PageNextSvg from '@rsuite/icon-font/lib/legacy/PageNext';

const PageNext = createSvgIcon({
  as: PageNextSvg,
  ariaLabel: 'page next',
  category: 'legacy',
  displayName: 'PageNext'
});

export default PageNext;
