// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PagelinesSvg from '@rsuite/icon-font/lib/legacy/Pagelines';

const Pagelines = createSvgIcon({
  as: PagelinesSvg,
  ariaLabel: 'pagelines',
  category: 'legacy',
  displayName: 'Pagelines'
});

export default Pagelines;
