// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PagePreviousSvg from '@rsuite/icon-font/lib/legacy/PagePrevious';

const PagePrevious = createSvgIcon({
  as: PagePreviousSvg,
  ariaLabel: 'page previous',
  category: 'legacy',
  displayName: 'PagePrevious'
});

export default PagePrevious;
