// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PaperclipSvg from '@rsuite/icon-font/lib/legacy/Paperclip';

const Paperclip = createSvgIcon({
  as: PaperclipSvg,
  ariaLabel: 'paperclip',
  category: 'legacy',
  displayName: 'Paperclip'
});

export default Paperclip;
