// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ParagraphSvg from '@rsuite/icon-font/lib/legacy/Paragraph';

const Paragraph = createSvgIcon({
  as: ParagraphSvg,
  ariaLabel: 'paragraph',
  category: 'legacy',
  displayName: 'Paragraph'
});

export default Paragraph;
