// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PauseCircleSvg from '@rsuite/icon-font/lib/legacy/PauseCircle';

const PauseCircle = createSvgIcon({
  as: PauseCircleSvg,
  ariaLabel: 'pause circle',
  category: 'legacy',
  displayName: 'PauseCircle'
});

export default PauseCircle;
