// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PeoplesMapSvg from '@rsuite/icon-font/lib/legacy/PeoplesMap';

const PeoplesMap = createSvgIcon({
  as: PeoplesMapSvg,
  ariaLabel: 'peoples map',
  category: 'legacy',
  displayName: 'PeoplesMap'
});

export default PeoplesMap;
