// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PeopleGroupSvg from '@rsuite/icon-font/lib/legacy/PeopleGroup';

const PeopleGroup = createSvgIcon({
  as: PeopleGroupSvg,
  ariaLabel: 'people group',
  category: 'legacy',
  displayName: 'PeopleGroup'
});

export default PeopleGroup;
