// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PercentSvg from '@rsuite/icon-font/lib/legacy/Percent';

const Percent = createSvgIcon({
  as: PercentSvg,
  ariaLabel: 'percent',
  category: 'legacy',
  displayName: 'Percent'
});

export default Percent;
