// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PinterestSquareSvg from '@rsuite/icon-font/lib/legacy/PinterestSquare';

const PinterestSquare = createSvgIcon({
  as: PinterestSquareSvg,
  ariaLabel: 'pinterest square',
  category: 'legacy',
  displayName: 'PinterestSquare'
});

export default PinterestSquare;
