// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PlaySvg from '@rsuite/icon-font/lib/legacy/Play';

const Play = createSvgIcon({
  as: PlaySvg,
  ariaLabel: 'play',
  category: 'legacy',
  displayName: 'Play'
});

export default Play;
