// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PlusSquareSvg from '@rsuite/icon-font/lib/legacy/PlusSquare';

const PlusSquare = createSvgIcon({
  as: PlusSquareSvg,
  ariaLabel: 'plus square',
  category: 'legacy',
  displayName: 'PlusSquare'
});

export default PlusSquare;
