// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PodcastSvg from '@rsuite/icon-font/lib/legacy/Podcast';

const Podcast = createSvgIcon({
  as: PodcastSvg,
  ariaLabel: 'podcast',
  category: 'legacy',
  displayName: 'Podcast'
});

export default Podcast;
