// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PrintSvg from '@rsuite/icon-font/lib/legacy/Print';

const Print = createSvgIcon({
  as: PrintSvg,
  ariaLabel: 'print',
  category: 'legacy',
  displayName: 'Print'
});

export default Print;
