// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import QuestionSvg from '@rsuite/icon-font/lib/legacy/Question';

const Question = createSvgIcon({
  as: QuestionSvg,
  ariaLabel: 'question',
  category: 'legacy',
  displayName: 'Question'
});

export default Question;
