// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RandomSvg from '@rsuite/icon-font/lib/legacy/Random';

const Random = createSvgIcon({
  as: RandomSvg,
  ariaLabel: 'random',
  category: 'legacy',
  displayName: 'Random'
});

export default Random;
