// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RealtimeSvg from '@rsuite/icon-font/lib/legacy/Realtime';

const Realtime = createSvgIcon({
  as: RealtimeSvg,
  ariaLabel: 'realtime',
  category: 'legacy',
  displayName: 'Realtime'
});

export default Realtime;
