// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RecycleSvg from '@rsuite/icon-font/lib/legacy/Recycle';

const Recycle = createSvgIcon({
  as: RecycleSvg,
  ariaLabel: 'recycle',
  category: 'legacy',
  displayName: 'Recycle'
});

export default Recycle;
