// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RedditSvg from '@rsuite/icon-font/lib/legacy/Reddit';

const Reddit = createSvgIcon({
  as: RedditSvg,
  ariaLabel: 'reddit',
  category: 'legacy',
  displayName: 'Reddit'
});

export default Reddit;
