// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RelatedMapSvg from '@rsuite/icon-font/lib/legacy/RelatedMap';

const RelatedMap = createSvgIcon({
  as: RelatedMapSvg,
  ariaLabel: 'related map',
  category: 'legacy',
  displayName: 'RelatedMap'
});

export default RelatedMap;
