// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RemindSvg from '@rsuite/icon-font/lib/legacy/Remind';

const Remind = createSvgIcon({
  as: RemindSvg,
  ariaLabel: 'remind',
  category: 'legacy',
  displayName: 'Remind'
});

export default Remind;
