// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RetentionSvg from '@rsuite/icon-font/lib/legacy/Retention';

const Retention = createSvgIcon({
  as: RetentionSvg,
  ariaLabel: 'retention',
  category: 'legacy',
  displayName: 'Retention'
});

export default Retention;
