// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SafariSvg from '@rsuite/icon-font/lib/legacy/Safari';

const Safari = createSvgIcon({
  as: SafariSvg,
  ariaLabel: 'safari',
  category: 'legacy',
  displayName: 'Safari'
});

export default Safari;
