// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SalesSvg from '@rsuite/icon-font/lib/legacy/Sales';

const Sales = createSvgIcon({
  as: SalesSvg,
  ariaLabel: 'sales',
  category: 'legacy',
  displayName: 'Sales'
});

export default Sales;
