// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SendOSvg from '@rsuite/icon-font/lib/legacy/SendO';

const SendO = createSvgIcon({
  as: SendOSvg,
  ariaLabel: 'send o',
  category: 'legacy',
  displayName: 'SendO'
});

export default SendO;
