// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SequenceDownSvg from '@rsuite/icon-font/lib/legacy/SequenceDown';

const SequenceDown = createSvgIcon({
  as: SequenceDownSvg,
  ariaLabel: 'sequence down',
  category: 'legacy',
  displayName: 'SequenceDown'
});

export default SequenceDown;
