// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SettingSvg from '@rsuite/icon-font/lib/legacy/Setting';

const Setting = createSvgIcon({
  as: SettingSvg,
  ariaLabel: 'setting',
  category: 'legacy',
  displayName: 'Setting'
});

export default Setting;
