// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ShirtsinbulkSvg from '@rsuite/icon-font/lib/legacy/Shirtsinbulk';

const Shirtsinbulk = createSvgIcon({
  as: ShirtsinbulkSvg,
  ariaLabel: 'shirtsinbulk',
  category: 'legacy',
  displayName: 'Shirtsinbulk'
});

export default Shirtsinbulk;
