// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ShowerSvg from '@rsuite/icon-font/lib/legacy/Shower';

const Shower = createSvgIcon({
  as: ShowerSvg,
  ariaLabel: 'shower',
  category: 'legacy',
  displayName: 'Shower'
});

export default Shower;
