// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SignInSvg from '@rsuite/icon-font/lib/legacy/SignIn';

const SignIn = createSvgIcon({
  as: SignInSvg,
  ariaLabel: 'sign in',
  category: 'legacy',
  displayName: 'SignIn'
});

export default SignIn;
