// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SitemapSvg from '@rsuite/icon-font/lib/legacy/Sitemap';

const Sitemap = createSvgIcon({
  as: SitemapSvg,
  ariaLabel: 'sitemap',
  category: 'legacy',
  displayName: 'Sitemap'
});

export default Sitemap;
