// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SlackSvg from '@rsuite/icon-font/lib/legacy/Slack';

const Slack = createSvgIcon({
  as: SlackSvg,
  ariaLabel: 'slack',
  category: 'legacy',
  displayName: 'Slack'
});

export default Slack;
