// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SlideshareSvg from '@rsuite/icon-font/lib/legacy/Slideshare';

const Slideshare = createSvgIcon({
  as: SlideshareSvg,
  ariaLabel: 'slideshare',
  category: 'legacy',
  displayName: 'Slideshare'
});

export default Slideshare;
