// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SortAmountAscSvg from '@rsuite/icon-font/lib/legacy/SortAmountAsc';

const SortAmountAsc = createSvgIcon({
  as: SortAmountAscSvg,
  ariaLabel: 'sort amount asc',
  category: 'legacy',
  displayName: 'SortAmountAsc'
});

export default SortAmountAsc;
