// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SpeakerSvg from '@rsuite/icon-font/lib/legacy/Speaker';

const Speaker = createSvgIcon({
  as: SpeakerSvg,
  ariaLabel: 'speaker',
  category: 'legacy',
  displayName: 'Speaker'
});

export default Speaker;
