// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StarOSvg from '@rsuite/icon-font/lib/legacy/StarO';

const StarO = createSvgIcon({
  as: StarOSvg,
  ariaLabel: 'star o',
  category: 'legacy',
  displayName: 'StarO'
});

export default StarO;
