// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StepBackwardSvg from '@rsuite/icon-font/lib/legacy/StepBackward';

const StepBackward = createSvgIcon({
  as: StepBackwardSvg,
  ariaLabel: 'step backward',
  category: 'legacy',
  displayName: 'StepBackward'
});

export default StepBackward;
