// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StopCircleOSvg from '@rsuite/icon-font/lib/legacy/StopCircleO';

const StopCircleO = createSvgIcon({
  as: StopCircleOSvg,
  ariaLabel: 'stop circle o',
  category: 'legacy',
  displayName: 'StopCircleO'
});

export default StopCircleO;
