// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StopSvg from '@rsuite/icon-font/lib/legacy/Stop';

const Stop = createSvgIcon({
  as: StopSvg,
  ariaLabel: 'stop',
  category: 'legacy',
  displayName: 'Stop'
});

export default Stop;
