// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StrikethroughSvg from '@rsuite/icon-font/lib/legacy/Strikethrough';

const Strikethrough = createSvgIcon({
  as: StrikethroughSvg,
  ariaLabel: 'strikethrough',
  category: 'legacy',
  displayName: 'Strikethrough'
});

export default Strikethrough;
