// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SubwaySvg from '@rsuite/icon-font/lib/legacy/Subway';

const Subway = createSvgIcon({
  as: SubwaySvg,
  ariaLabel: 'subway',
  category: 'legacy',
  displayName: 'Subway'
});

export default Subway;
