// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SunOSvg from '@rsuite/icon-font/lib/legacy/SunO';

const SunO = createSvgIcon({
  as: SunOSvg,
  ariaLabel: 'sun o',
  category: 'legacy',
  displayName: 'SunO'
});

export default SunO;
