// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SupportSvg from '@rsuite/icon-font/lib/legacy/Support';

const Support = createSvgIcon({
  as: SupportSvg,
  ariaLabel: 'support',
  category: 'legacy',
  displayName: 'Support'
});

export default Support;
