// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TableSvg from '@rsuite/icon-font/lib/legacy/Table';

const Table = createSvgIcon({
  as: TableSvg,
  ariaLabel: 'table',
  category: 'legacy',
  displayName: 'Table'
});

export default Table;
