// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TencentWeiboSvg from '@rsuite/icon-font/lib/legacy/TencentWeibo';

const TencentWeibo = createSvgIcon({
  as: TencentWeiboSvg,
  ariaLabel: 'tencent weibo',
  category: 'legacy',
  displayName: 'TencentWeibo'
});

export default TencentWeibo;
