// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ThSvg from '@rsuite/icon-font/lib/legacy/Th';

const Th = createSvgIcon({
  as: ThSvg,
  ariaLabel: 'th',
  category: 'legacy',
  displayName: 'Th'
});

export default Th;
