// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ThemeisleSvg from '@rsuite/icon-font/lib/legacy/Themeisle';

const Themeisle = createSvgIcon({
  as: ThemeisleSvg,
  ariaLabel: 'themeisle',
  category: 'legacy',
  displayName: 'Themeisle'
});

export default Themeisle;
