// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ThumbsODownSvg from '@rsuite/icon-font/lib/legacy/ThumbsODown';

const ThumbsODown = createSvgIcon({
  as: ThumbsODownSvg,
  ariaLabel: 'thumbs o down',
  category: 'legacy',
  displayName: 'ThumbsODown'
});

export default ThumbsODown;
