// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TicketSvg from '@rsuite/icon-font/lib/legacy/Ticket';

const Ticket = createSvgIcon({
  as: TicketSvg,
  ariaLabel: 'ticket',
  category: 'legacy',
  displayName: 'Ticket'
});

export default Ticket;
