// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ToggleLeftSvg from '@rsuite/icon-font/lib/legacy/ToggleLeft';

const ToggleLeft = createSvgIcon({
  as: ToggleLeftSvg,
  ariaLabel: 'toggle left',
  category: 'legacy',
  displayName: 'ToggleLeft'
});

export default ToggleLeft;
