// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TtySvg from '@rsuite/icon-font/lib/legacy/Tty';

const Tty = createSvgIcon({
  as: TtySvg,
  ariaLabel: 'tty',
  category: 'legacy',
  displayName: 'Tty'
});

export default Tty;
