// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TumblrSquareSvg from '@rsuite/icon-font/lib/legacy/TumblrSquare';

const TumblrSquare = createSvgIcon({
  as: TumblrSquareSvg,
  ariaLabel: 'tumblr square',
  category: 'legacy',
  displayName: 'TumblrSquare'
});

export default TumblrSquare;
