// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TwinkleStarSvg from '@rsuite/icon-font/lib/legacy/TwinkleStar';

const TwinkleStar = createSvgIcon({
  as: TwinkleStarSvg,
  ariaLabel: 'twinkle star',
  category: 'legacy',
  displayName: 'TwinkleStar'
});

export default TwinkleStar;
