// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UmbrellaSvg from '@rsuite/icon-font/lib/legacy/Umbrella';

const Umbrella = createSvgIcon({
  as: UmbrellaSvg,
  ariaLabel: 'umbrella',
  category: 'legacy',
  displayName: 'Umbrella'
});

export default Umbrella;
