// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UndoSvg from '@rsuite/icon-font/lib/legacy/Undo';

const Undo = createSvgIcon({
  as: UndoSvg,
  ariaLabel: 'undo',
  category: 'legacy',
  displayName: 'Undo'
});

export default Undo;
