// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UnlinkSvg from '@rsuite/icon-font/lib/legacy/Unlink';

const Unlink = createSvgIcon({
  as: UnlinkSvg,
  ariaLabel: 'unlink',
  category: 'legacy',
  displayName: 'Unlink'
});

export default Unlink;
