// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UnlockSvg from '@rsuite/icon-font/lib/legacy/Unlock';

const Unlock = createSvgIcon({
  as: UnlockSvg,
  ariaLabel: 'unlock',
  category: 'legacy',
  displayName: 'Unlock'
});

export default Unlock;
