// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UsdSvg from '@rsuite/icon-font/lib/legacy/Usd';

const Usd = createSvgIcon({
  as: UsdSvg,
  ariaLabel: 'usd',
  category: 'legacy',
  displayName: 'Usd'
});

export default Usd;
