// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UserInfoSvg from '@rsuite/icon-font/lib/legacy/UserInfo';

const UserInfo = createSvgIcon({
  as: UserInfoSvg,
  ariaLabel: 'user info',
  category: 'legacy',
  displayName: 'UserInfo'
});

export default UserInfo;
