// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UserTimesSvg from '@rsuite/icon-font/lib/legacy/UserTimes';

const UserTimes = createSvgIcon({
  as: UserTimesSvg,
  ariaLabel: 'user times',
  category: 'legacy',
  displayName: 'UserTimes'
});

export default UserTimes;
