// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UserSecretSvg from '@rsuite/icon-font/lib/legacy/UserSecret';

const UserSecret = createSvgIcon({
  as: UserSecretSvg,
  ariaLabel: 'user secret',
  category: 'legacy',
  displayName: 'UserSecret'
});

export default UserSecret;
