// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import VenusSvg from '@rsuite/icon-font/lib/legacy/Venus';

const Venus = createSvgIcon({
  as: VenusSvg,
  ariaLabel: 'venus',
  category: 'legacy',
  displayName: 'Venus'
});

export default Venus;
