// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import VineSvg from '@rsuite/icon-font/lib/legacy/Vine';

const Vine = createSvgIcon({
  as: VineSvg,
  ariaLabel: 'vine',
  category: 'legacy',
  displayName: 'Vine'
});

export default Vine;
