// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WarningSvg from '@rsuite/icon-font/lib/legacy/Warning';

const Warning = createSvgIcon({
  as: WarningSvg,
  ariaLabel: 'warning',
  category: 'legacy',
  displayName: 'Warning'
});

export default Warning;
