// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WeiboSvg from '@rsuite/icon-font/lib/legacy/Weibo';

const Weibo = createSvgIcon({
  as: WeiboSvg,
  ariaLabel: 'weibo',
  category: 'legacy',
  displayName: 'Weibo'
});

export default Weibo;
