// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WindowMinimizeSvg from '@rsuite/icon-font/lib/legacy/WindowMinimize';

const WindowMinimize = createSvgIcon({
  as: WindowMinimizeSvg,
  ariaLabel: 'window minimize',
  category: 'legacy',
  displayName: 'WindowMinimize'
});

export default WindowMinimize;
