// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WindowMaximizeSvg from '@rsuite/icon-font/lib/legacy/WindowMaximize';

const WindowMaximize = createSvgIcon({
  as: WindowMaximizeSvg,
  ariaLabel: 'window maximize',
  category: 'legacy',
  displayName: 'WindowMaximize'
});

export default WindowMaximize;
