// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WindowsSvg from '@rsuite/icon-font/lib/legacy/Windows';

const Windows = createSvgIcon({
  as: WindowsSvg,
  ariaLabel: 'windows',
  category: 'legacy',
  displayName: 'Windows'
});

export default Windows;
