// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WindowRestoreSvg from '@rsuite/icon-font/lib/legacy/WindowRestore';

const WindowRestore = createSvgIcon({
  as: WindowRestoreSvg,
  ariaLabel: 'window restore',
  category: 'legacy',
  displayName: 'WindowRestore'
});

export default WindowRestore;
