// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WpbeginnerSvg from '@rsuite/icon-font/lib/legacy/Wpbeginner';

const Wpbeginner = createSvgIcon({
  as: WpbeginnerSvg,
  ariaLabel: 'wpbeginner',
  category: 'legacy',
  displayName: 'Wpbeginner'
});

export default Wpbeginner;
