// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WpexplorerSvg from '@rsuite/icon-font/lib/legacy/Wpexplorer';

const Wpexplorer = createSvgIcon({
  as: WpexplorerSvg,
  ariaLabel: 'wpexplorer',
  category: 'legacy',
  displayName: 'Wpexplorer'
});

export default Wpexplorer;
