// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import XingSvg from '@rsuite/icon-font/lib/legacy/Xing';

const Xing = createSvgIcon({
  as: XingSvg,
  ariaLabel: 'xing',
  category: 'legacy',
  displayName: 'Xing'
});

export default Xing;
