// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const BlockRound = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="m6.707 10.707 4-4a3 3 0 0 1-4 4.001l.001-.001zM5.292 9.293a3 3 0 0 1 4.001-4.001zM8 16A8 8 0 1 1 8 0a8 8 0 0 1 0 16m0-3a5 5 0 1 0-.001-10.001A5 5 0 0 0 8 13" />
  </svg>
);
const ForwardRef = forwardRef(BlockRound);
export default ForwardRef;
