// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const EditRound = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0m3.5 12h-7a.5.5 0 0 0-.09.992L4.5 13h7a.5.5 0 0 0 .09-.992zM7.725 3.15a.5.5 0 0 0-.631.109l-.052.074-3.056 5.292q-.296 2.011.138 2.261.408.236 1.843-.868l.184-.143 3.056-5.292a.5.5 0 0 0-.109-.631L9.024 3.9zM11.5 9h-2a.5.5 0 0 0-.09.992L9.5 10h2a.5.5 0 0 0 .09-.992zm0-2h-1a.5.5 0 0 0-.09.992L10.5 8h1a.5.5 0 0 0 .09-.992z" />
  </svg>
);
const ForwardRef = forwardRef(EditRound);
export default ForwardRef;
