// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const EyeClose = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M14.5 5c.25 0 .5.224.5.5 0 .907-.527 1.749-1.341 2.452l1.195 1.194a.5.5 0 0 1-.707.707l-1.301-1.301a9.6 9.6 0 0 1-2.685 1.15l.787 1.574a.5.5 0 0 1-.895.447l-.907-1.812c-.391.058-.776.088-1.146.088s-.755-.03-1.146-.088l-.907 1.812a.5.5 0 0 1-.895-.447l.787-1.574a9.7 9.7 0 0 1-2.685-1.15L1.853 9.853a.5.5 0 0 1-.707-.707l1.195-1.194C1.526 7.248 1 6.407 1 5.5a.5.5 0 0 1 1 0C2 7.126 5.172 9 8 9s6-1.874 6-3.5c0-.25.25-.5.5-.5" />
  </svg>
);
const ForwardRef = forwardRef(EyeClose);
export default ForwardRef;
