// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const EyeRound = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0m0 4C5 4 3 7 3 8s2 4 5 4 5-3 5-4-2-4-5-4m0 2a2 2 0 1 1 .001 3.999A2 2 0 0 1 8 6" />
  </svg>
);
const ForwardRef = forwardRef(EyeRound);
export default ForwardRef;
