// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const LockRound = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M2.343 13.657A8 8 0 1 0 13.657 2.342 8 8 0 0 0 2.343 13.657M8 3a2 2 0 0 1 2 2v2a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1V5a2 2 0 0 1 2-2m0 1 .117.007A1 1 0 0 1 9 5v2H7V5l.007-.117A1 1 0 0 1 8 4" />
  </svg>
);
const ForwardRef = forwardRef(LockRound);
export default ForwardRef;
