// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Notice = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 0a1 1 0 0 1 1 1v1l-.006.111a4.47 4.47 0 0 1 3.448 3.864L13 10.999l2 2a.5.5 0 0 1 0 1H1a.5.5 0 0 1 0-1l2-2 .558-5.024a4.47 4.47 0 0 1 3.448-3.864A1 1 0 0 1 7 2V1a1 1 0 0 1 1-1m0 3a3.47 3.47 0 0 0-3.448 3.086l-.597 5.373L2.414 13h11.172l-1.541-1.541-.597-5.373A3.47 3.47 0 0 0 8 3M6.5 15h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1 0-1M4.418 1.007a.5.5 0 0 1 .164.986C2.85 2.282 2 3.557 2 6a.5.5 0 0 1-1 0c0-2.891 1.15-4.615 3.418-4.993M11.582 1.007a.5.5 0 0 0-.164.986C13.15 2.282 14 3.557 14 6a.5.5 0 0 0 1 0c0-2.891-1.15-4.615-3.418-4.993" />
  </svg>
);
const ForwardRef = forwardRef(Notice);
export default ForwardRef;
