// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Pin = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="m11.389.373 4.243 4.243a1 1 0 0 1 0 1.414l-.707.707a1 1 0 0 1-1.414 0l-.404-.404-2.425 3.232.512 1.535a1 1 0 0 1-.242 1.023l-.977.977-3.182-3.183L3.9 12.811q-2.057 2.057-2.411 1.703c-.354-.354.332-1.039 1.703-2.411L6.085 9.21 2.903 6.029l.977-.977a1 1 0 0 1 1.023-.242l1.535.512L9.67 2.897l-.404-.404a1 1 0 0 1 0-1.414l.707-.707a1 1 0 0 1 1.414 0zm-.708.707-.707.707.404.404a1 1 0 0 1-.107 1.507L7.039 6.123a1 1 0 0 1-.916.149L4.588 5.76l-.27.27 5.657 5.657.27-.27-.512-1.535a1 1 0 0 1 .149-.916l2.425-3.232a1 1 0 0 1 1.507-.107l.404.404.707-.707z" />
  </svg>
);
const ForwardRef = forwardRef(Pin);
export default ForwardRef;
