// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Pined = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M11 2a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1l-.49-.001L11 8l1.447.724a1 1 0 0 1 .553.894V11H8.682v2.999L14.5 14a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1l5.768-.001V11H3V9.618c0-.379.214-.725.553-.894L5 8l.463-3.001L5 5a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1zm0 1H5v1l.461-.001a1 1 0 0 1 .99 1.152l-.463 3.001a1 1 0 0 1-.541.742L4 9.618V10h8v-.382l-1.447-.724a1 1 0 0 1-.54-.733l-.49-3.001a1 1 0 0 1 .989-1.161L11 4z" />
  </svg>
);
const ForwardRef = forwardRef(Pined);
export default ForwardRef;
