// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const ReadyRound = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M6.6 4.2a1 1 0 0 0-1.2 1.6L8.333 8 5.4 10.2a1 1 0 0 0 1.2 1.6l4-3a1 1 0 0 0 0-1.6z" />
  </svg>
);
const ForwardRef = forwardRef(ReadyRound);
export default ForwardRef;
