// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const RunningRound = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 16A8 8 0 1 1 8 0a8 8 0 0 1 0 16m.793-6.207a.999.999 0 1 0 1.414 1.414l2.5-2.5a1 1 0 0 0 0-1.414l-2.5-2.5a.999.999 0 1 0-1.414 1.414L10.586 8zM5.586 8 3.793 9.793a.999.999 0 1 0 1.414 1.414l2.5-2.5a1 1 0 0 0 0-1.414l-2.5-2.5a.999.999 0 1 0-1.414 1.414z" />
  </svg>
);
const ForwardRef = forwardRef(RunningRound);
export default ForwardRef;
