// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const SendRound = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0m5 8L5 9l-.751 3.005-.014.089a.5.5 0 0 0 .624.516l.078-.027 7.149-3.178.136-.068c.394-.224.667-.609.751-1.05l.021-.149zM4.694 3.375l-.082.013a.5.5 0 0 0-.378.517l.014.089.751 3.005 8 1-.006-.139a1.54 1.54 0 0 0-.772-1.198l-.136-.068-7.149-3.178a.5.5 0 0 0-.242-.042z" />
  </svg>
);
const ForwardRef = forwardRef(SendRound);
export default ForwardRef;
