// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Unvisible = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M16 8q-3.581 5-8 5-2.067 0-3.95-1.094l.657-.777C5.767 11.713 6.864 12 8 12c2.419 0 4.662-1.303 6.753-4-1.066-1.374-2.17-2.386-3.318-3.048l.018.03a4 4 0 0 1-5.919 5.169l.647-.764a3 3 0 0 0 3.87-4.575l.994-1.175q2.65 1.147 4.954 4.364zM8 3a7.5 7.5 0 0 1 2.041.279l-.827.977a3 3 0 0 0-3.719 4.395l-.666.788A3.98 3.98 0 0 1 4 7.001c0-.749.206-1.449.563-2.048-1.146.662-2.251 1.674-3.317 3.048q1.266 1.632 2.608 2.59l-.648.765q-1.68-1.223-3.207-3.355 3.582-5 8-5z" />
    <path d="M13.823 1.118a.5.5 0 0 0-.64-.005l-.064.063-11 13a.5.5 0 0 0 .699.71l.064-.063 11-13a.5.5 0 0 0-.059-.705" />
  </svg>
);
const ForwardRef = forwardRef(Unvisible);
export default ForwardRef;
