// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const UpdateRound = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 16A8 8 0 1 1 8 0a8 8 0 0 1 0 16M5.555 6.832 8 5.202l2.445 1.63a1.001 1.001 0 0 0 1.11-1.664l-3-2a1 1 0 0 0-1.109 0l-3 2a1 1 0 1 0 1.11 1.664zm0 5L8 10.202l2.445 1.63a1.001 1.001 0 0 0 1.11-1.664l-3-2a1 1 0 0 0-1.109 0l-3 2a1 1 0 1 0 1.11 1.664z" />
  </svg>
);
const ForwardRef = forwardRef(UpdateRound);
export default ForwardRef;
