// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const VerifyRound = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M5.555 7.168a1.001 1.001 0 0 0-1.11 1.664L6.197 10l-1.752 1.168a1 1 0 1 0 1.11 1.664l3-2a1 1 0 0 0 0-1.664zm4.89-4-3 2a1 1 0 0 0 0 1.664l3 2a1.001 1.001 0 0 0 1.11-1.664L9.803 6l1.752-1.168a1 1 0 1 0-1.11-1.664" />
  </svg>
);
const ForwardRef = forwardRef(VerifyRound);
export default ForwardRef;
