// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const BarLineChart = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M.5 9a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 .5 9M5.5 10a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2a.5.5 0 0 1 .5-.5M10.5 7a.5.5 0 0 1 .5.5v5a.5.5 0 0 1-1 0v-5a.5.5 0 0 1 .5-.5M15.5 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M.5 15h15a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1M10.116.18a.5.5 0 0 1 .482-.17l.088.026 5 2a.498.498 0 0 1-.284.954l-.086-.026-4.662-1.865L5.886 6.82a.5.5 0 0 1-.482.17l-.088-.026-5-2A.498.498 0 0 1 .6 4.01l.086.026L5.348 5.9z" />
  </svg>
);
const ForwardRef = forwardRef(BarLineChart);
export default ForwardRef;
