// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const DonutChart = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="m5.993.254 1.016 4.914a3 3 0 1 0 3.747 4.018l.068-.171 4.923.988A8 8 0 1 1 5.748.321zm-.751 1.309-.189.085a7 7 0 1 0 9.3 9.297l.082-.186-3.06-.614-.078.122a4 4 0 0 1-3.085 1.728L8 12.001a4 4 0 0 1-2.211-7.334l.083-.054z" />
    <path d="M8 0a8 8 0 0 1 7.996 7.751L16 8h-5a3 3 0 0 0-2.824-2.995L8 5zm1 1.071v3.055l.155.043a4.01 4.01 0 0 1 2.675 2.675l.042.155h3.055l-.027-.182a7.01 7.01 0 0 0-5.719-5.719l-.182-.028z" />
  </svg>
);
const ForwardRef = forwardRef(DonutChart);
export default ForwardRef;
