// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const FunnelSteps = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M.5 6a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0v-8A.5.5 0 0 1 .5 6M7.5 10a.5.5 0 0 0-.5.5v4a.5.5 0 0 0 1 0v-4a.5.5 0 0 0-.5-.5M4 1l2 1.5L4 4H.5a.5.5 0 0 1-.5-.5v-2A.5.5 0 0 1 .5 1zm-.333 1H1v1h2.667l.666-.5zM9 5l2 1.5L9 8H5.5a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 1 .5-.5zm-.333 1H6v1h2.667l.666-.5zM14 9l2 1.5-2 1.5h-3.5a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 1 .5-.5zm-.333 1H11v1h2.667l.666-.5zM14.5 13a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 1 0v-1a.5.5 0 0 0-.5-.5" />
  </svg>
);
const ForwardRef = forwardRef(FunnelSteps);
export default ForwardRef;
