// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const FunnelTime = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M5.5 2h10a.5.5 0 0 1 0 1h-10a.5.5 0 0 1 0-1M5.5 6h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1M5.5 10h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1M5.5 14a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1M.146 1.146a.5.5 0 0 1 .638-.058l.069.058.646.647.646-.647a.5.5 0 0 1 .638-.058l.069.058a.5.5 0 0 1 .058.638l-.058.069-1 1a.5.5 0 0 1-.638.058l-.069-.058-1-1a.5.5 0 0 1 0-.707zm0 4a.5.5 0 0 1 .638-.058l.069.058.646.647.646-.647a.5.5 0 0 1 .638-.058l.069.058a.5.5 0 0 1 .058.638l-.058.069-1 1a.5.5 0 0 1-.638.058l-.069-.058-1-1a.5.5 0 0 1 0-.707zm0 4a.5.5 0 0 1 .638-.058l.069.058.646.647.646-.647a.5.5 0 0 1 .638-.058l.069.058a.5.5 0 0 1 .058.638l-.058.069-1 1a.5.5 0 0 1-.638.058l-.069-.058-1-1a.5.5 0 0 1 0-.707zm0 4a.5.5 0 0 1 .638-.058l.069.058.646.647.646-.647a.5.5 0 0 1 .638-.058l.069.058a.5.5 0 0 1 .058.638l-.058.069-1 1a.5.5 0 0 1-.638.058l-.069-.058-1-1a.5.5 0 0 1 0-.707z" />
  </svg>
);
const ForwardRef = forwardRef(FunnelTime);
export default ForwardRef;
