// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const LineChart = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M.5 15h15a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1M15.093.209a.499.499 0 0 1 .859.504l-.046.078-5 7a.5.5 0 0 1-.511.198l-.081-.025-4.662-1.865L.884 11.82a.5.5 0 0 1-.63.115l-.074-.051a.5.5 0 0 1-.115-.63l.051-.074 5-6a.5.5 0 0 1 .482-.17l.088.026 4.635 1.853z" />
  </svg>
);
const ForwardRef = forwardRef(LineChart);
export default ForwardRef;
