// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const RelatedMap = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="m15.409 8.512.09.004a.5.5 0 0 1 .429.562 8 8 0 0 1-7.349 6.901.5.5 0 1 1-.071-.997 7 7 0 0 0 6.429-6.037.5.5 0 0 1 .385-.421zM7.428.02a.5.5 0 0 1 .071.997 7 7 0 0 0-6.428 5.985.5.5 0 1 1-.99-.142A8.004 8.004 0 0 1 7.428.018zm4.956 8.673.089.016a.5.5 0 0 1 .35.614 5.005 5.005 0 0 1-4.244 3.644.5.5 0 0 1-.115-.993 4 4 0 0 0 3.394-2.914.5.5 0 0 1 .438-.366h.088zM7.291 3.527a.5.5 0 0 1-.35.614 4.005 4.005 0 0 0-2.918 3.426.5.5 0 1 1-.994-.106 5 5 0 0 1 3.648-4.284.5.5 0 0 1 .614.35M8 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2m0 1a2 2 0 1 1-.001-3.999A2 2 0 0 1 8 10M11 3a1 1 0 1 1-2 0 1 1 0 0 1 2 0M6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0M15 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0M3 10a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
  </svg>
);
const ForwardRef = forwardRef(RelatedMap);
export default ForwardRef;
