// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Table = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M14 0a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm0 1H2a1 1 0 0 0-.993.883L1 2v12a1 1 0 0 0 .883.993L2 15h12a1 1 0 0 0 .993-.883L15 14V2a1 1 0 0 0-.883-.993z" />
    <path d="M0 3h16v1H0z" />
    <path d="M5 1h1v14H5zM10 1h1v14h-1z" />
    <path d="M0 7h16v1H0zM0 11h16v1H0z" />
  </svg>
);
const ForwardRef = forwardRef(Table);
export default ForwardRef;
