// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const BranchAuthorize = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M16 9a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-2h-1v2H9V9z" />
    <path d="M15.175 10.12a.5.5 0 0 1 .651.759l-3.5 3a.5.5 0 0 1-.741-.102l-1-1.5a.5.5 0 1 1 .832-.554l.687 1.03zM12.5 0a1.5 1.5 0 1 1-1.414 2.001L8.805 2a2.94 2.94 0 0 0-2.579 1.529l-.09.18-.394.855a2.5 2.5 0 0 1-.259.437L8.085 5a1.5 1.5 0 1 1 .001 1.001L2.886 6q.148.218.245.472l.056.168L3.7 8.4a.83.83 0 0 0 .422.509 1.499 1.499 0 1 1-.054 1.04 1.83 1.83 0 0 1-1.28-1.125L2.74 8.68l-.513-1.76A1.28 1.28 0 0 0 1 6H.5a.5.5 0 0 1-.09-.992L.5 5h3c.525 0 1.007-.28 1.268-.728l.066-.126.394-.855a3.94 3.94 0 0 1 3.369-2.285l.209-.005h2.28a1.5 1.5 0 0 1 1.415-1zm-7 9a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1m4-4a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1m3-4a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1" />
  </svg>
);
const ForwardRef = forwardRef(BranchAuthorize);
export default ForwardRef;
