// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const BranchLock = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M9 11v4h6v-4zm0-1h6a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1" />
    <path d="M12 12a1 1 0 1 1 0 2 1 1 0 0 1 0-2M13 10V8.8c0-.417-.426-.8-1-.8s-1 .383-1 .8V10h-1V8.8c0-.994.895-1.8 2-1.8s2 .806 2 1.8V10zM12.5 0a1.5 1.5 0 1 1-1.414 2.001L8.805 2a2.94 2.94 0 0 0-2.579 1.529l-.09.18-.394.855a2.5 2.5 0 0 1-.259.437L8.085 5a1.5 1.5 0 1 1 .001 1.001L2.886 6q.148.218.245.472l.056.168.373 1.28A1.5 1.5 0 0 0 5 9l.083.007a1.5 1.5 0 1 1 0 .986L5 10a2.5 2.5 0 0 1-2.345-1.634L2.6 8.2l-.373-1.28A1.28 1.28 0 0 0 1 6H.5a.5.5 0 0 1-.09-.992L.5 5h3c.525 0 1.007-.28 1.268-.728l.066-.126.394-.855a3.94 3.94 0 0 1 3.369-2.285l.209-.005h2.28a1.5 1.5 0 0 1 1.415-1zm-6 9a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1m3-4a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1m3-4a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1" />
  </svg>
);
const ForwardRef = forwardRef(BranchLock);
export default ForwardRef;
