// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Direct = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M2.5 7h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1 0-1" />
    <path d="M14.5 6a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 14.5 6m0 1a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1m-13-1a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 1.5 6m0 1a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1" />
  </svg>
);
const ForwardRef = forwardRef(Direct);
export default ForwardRef;
