// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const FlowStop = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M9 4a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1zm0 1H5v4h4z" />
    <path d="M14.5 8a1.5 1.5 0 1 1-1.408 2.02 1.51 1.51 0 0 0-1.082.74l-.095.15a2.5 2.5 0 0 1-1.664 1.058q.075.077.146.163l.121.157.801 1.108c.195.27.473.461.786.549a1.5 1.5 0 1 1-.033 1.015 2.44 2.44 0 0 1-1.451-.836l-.111-.143-.801-1.108A2.1 2.1 0 0 0 8 11.999H6.5a.5.5 0 0 1 0-1h3.351l.144-.007a1.5 1.5 0 0 0 1.156-.745l.095-.151a2.52 2.52 0 0 1 1.835-1.086A1.5 1.5 0 0 1 14.5 7.998zm-1 6a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1m1-5a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1" />
    <path d="M7 0a7 7 0 0 1 7 7 .5.5 0 0 1-1 0 6 6 0 1 0-6 6 .5.5 0 0 1 0 1A7 7 0 1 1 7 0" />
  </svg>
);
const ForwardRef = forwardRef(FlowStop);
export default ForwardRef;
