// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Random = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M9.86 10.255a5.5 5.5 0 0 0 3.75 1.739l.269.007h1.12a.5.5 0 0 1 .09.992l-.09.008h-1.12a6.5 6.5 0 0 1-4.75-2.063.5.5 0 1 1 .731-.683M1.62 2a6.5 6.5 0 0 1 5.538 3.096.5.5 0 0 1-.852.524 5.5 5.5 0 0 0-4.437-2.614L1.62 3H.5a.5.5 0 0 1-.09-.992L.5 2z" />
    <path d="M13.146 10.146a.5.5 0 0 1 .638-.058l.069.058 2 2a.5.5 0 0 1 .058.638l-.058.069-2 2a.5.5 0 0 1-.765-.638l.058-.069 1.647-1.646-1.647-1.646a.5.5 0 0 1-.058-.638zM1.62 14a6.5 6.5 0 0 0 5.818-3.602l.109-.23 1.316-2.924a5.5 5.5 0 0 1 4.776-3.238l.24-.005h1.12a.5.5 0 0 0 .09-.992l-.09-.008h-1.12a6.5 6.5 0 0 0-5.818 3.602l-.109.23-1.316 2.924a5.5 5.5 0 0 1-4.776 3.238L1.62 13H.5a.5.5 0 0 0-.09.992L.5 14z" />
    <path d="M13.146 5.854a.5.5 0 0 0 .638.058l.069-.058 2-2a.5.5 0 0 0 .058-.638l-.058-.069-2-2a.5.5 0 0 0-.765.638l.058.069L14.793 3.5l-1.647 1.646a.5.5 0 0 0-.058.638l.058.069z" />
  </svg>
);
const ForwardRef = forwardRef(Random);
export default ForwardRef;
