// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const ReviewPass = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="m4.863 8.921.281-1.464-1.196-2.452-.632.007a2 2 0 1 1 1.54-.751l.782.624a2.999 2.999 0 1 0-5.04-.558 3 3 0 0 0 2.729 1.685L4.33 8.069.606 9.885c-.425.208-.668.912-.46 1.337l.438.899c.438.899 1.776 1.359 2.674.921l.899-.438-.438-.899-.899.438c-.402.196-1.141-.058-1.337-.46l-.438-.899zM1.5 15h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1 0-1" />
    <path d="M15.909 11.042a6 6 0 1 1-4.867-6.951.5.5 0 1 1-.173.985 5 5 0 0 0-5.792 4.056 5 5 0 1 0 9.848 1.736.5.5 0 1 1 .985.173z" />
    <path d="m9.55 11.673 5.57-6.499a.5.5 0 1 1 .759.651l-5.991 6.989a.532.532 0 0 1-.175.137.5.5 0 0 1-.433-.002l-.012-.006a.5.5 0 0 1-.163-.135q-.016-.02-.029-.041l-1.993-2.99a.5.5 0 1 1 .832-.554l1.634 2.451z" />
  </svg>
);
const ForwardRef = forwardRef(ReviewPass);
export default ForwardRef;
