// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Split = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M13.146 11.146a.5.5 0 0 1 .638-.058l.069.058 2 2a.5.5 0 0 1 .058.638l-.058.069-2 2a.5.5 0 0 1-.765-.638l.058-.069 1.647-1.646-1.647-1.646a.5.5 0 0 1-.058-.638zm0-11a.5.5 0 0 1 .638-.058l.069.058 2 2a.5.5 0 0 1 .058.638l-.058.069-2 2a.5.5 0 0 1-.765-.638l.058-.069L14.793 2.5 13.146.854a.5.5 0 0 1-.058-.638l.058-.069z" />
    <path d="M4.84 7c.553 0 1.088-.183 1.523-.518l.158-.132 3.784-3.44a3.5 3.5 0 0 1 2.137-.903L12.659 2h1.84a.5.5 0 0 1 .09.992l-.09.008h-1.84c-.553 0-1.088.183-1.523.518l-.158.132-3.784 3.44a3.5 3.5 0 0 1-.851.571c.411.249.784.568 1.101.944l.155.195 2.1 2.8a3.5 3.5 0 0 0 2.581 1.393l.219.007h2a.5.5 0 0 1 .09.992l-.09.008h-2a4.5 4.5 0 0 1-3.445-1.605l-.155-.195-2.1-2.8a3.5 3.5 0 0 0-2.581-1.393L3.999 8h-3.5a.5.5 0 0 1-.09-.992L.499 7z" />
  </svg>
);
const ForwardRef = forwardRef(Split);
export default ForwardRef;
