// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Wait = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M2.5 0h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1 0-1M2.5 15h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1 0-1" />
    <path d="M5 1v3c0 .944.445 1.833 1.2 2.4l1.2.9a1 1 0 0 0 1.2 0l1.2-.9A3 3 0 0 0 11 4V1zM4 0h8v4a4 4 0 0 1-1.6 3.2l-1.2.9a2 2 0 0 1-2.4 0l-1.2-.9A4 4 0 0 1 4 4z" />
    <path d="M5 15.002h6v-2.343c0-.796-.316-1.559-.879-2.121L8.707 9.124a1 1 0 0 0-1.414 0l-1.414 1.414A3 3 0 0 0 5 12.659zm-1 1v-3.343c0-1.061.421-2.078 1.172-2.828l1.414-1.414a2 2 0 0 1 2.828 0l1.414 1.414A4 4 0 0 1 12 12.659v3.343zM4.5 3h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1" />
    <path d="M4.5 13h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1M10.5 13h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1 0-1" />
  </svg>
);
const ForwardRef = forwardRef(Wait);
export default ForwardRef;
