// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AddressBookOSvg from '@rsuite/icon-font/lib/legacy/AddressBookO';

/**
 * @deprecated Will be removed in the next major version.
 */
const AddressBookO = createSvgIcon({
  as: AddressBookOSvg,
  ariaLabel: 'address book o',
  category: '',
  displayName: 'AddressBookO'
});

export default AddressBookO;
