// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AdjustSvg from '@rsuite/icon-font/lib/legacy/Adjust';

/**
 * @deprecated Will be removed in the next major version.
 */
const Adjust = createSvgIcon({
  as: AdjustSvg,
  ariaLabel: 'adjust',
  category: '',
  displayName: 'Adjust'
});

export default Adjust;
