// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AdnSvg from '@rsuite/icon-font/lib/legacy/Adn';

/**
 * @deprecated Will be removed in the next major version.
 */
const Adn = createSvgIcon({
  as: AdnSvg,
  ariaLabel: 'adn',
  category: '',
  displayName: 'Adn'
});

export default Adn;
