// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AlignCenterSvg from '@rsuite/icon-font/lib/legacy/AlignCenter';

/**
 * @deprecated Will be removed in the next major version.
 */
const AlignCenter = createSvgIcon({
  as: AlignCenterSvg,
  ariaLabel: 'align center',
  category: '',
  displayName: 'AlignCenter'
});

export default AlignCenter;
