// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AlipaySvg from '@rsuite/icon-font/lib/legacy/Alipay';

/**
 * @deprecated Will be removed in the next major version.
 */
const Alipay = createSvgIcon({
  as: AlipaySvg,
  ariaLabel: 'alipay',
  category: '',
  displayName: 'Alipay'
});

export default Alipay;
