// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AmazonSvg from '@rsuite/icon-font/lib/legacy/Amazon';

/**
 * @deprecated Will be removed in the next major version.
 */
const Amazon = createSvgIcon({
  as: AmazonSvg,
  ariaLabel: 'amazon',
  category: '',
  displayName: 'Amazon'
});

export default Amazon;
