// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AnchorSvg from '@rsuite/icon-font/lib/legacy/Anchor';

/**
 * @deprecated Will be removed in the next major version.
 */
const Anchor = createSvgIcon({
  as: AnchorSvg,
  ariaLabel: 'anchor',
  category: '',
  displayName: 'Anchor'
});

export default Anchor;
