// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AngellistSvg from '@rsuite/icon-font/lib/legacy/Angellist';

/**
 * @deprecated Will be removed in the next major version.
 */
const Angellist = createSvgIcon({
  as: AngellistSvg,
  ariaLabel: 'angellist',
  category: '',
  displayName: 'Angellist'
});

export default Angellist;
