// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AngleDoubleRightSvg from '@rsuite/icon-font/lib/legacy/AngleDoubleRight';

/**
 * @deprecated Will be removed in the next major version.
 */
const AngleDoubleRight = createSvgIcon({
  as: AngleDoubleRightSvg,
  ariaLabel: 'angle double right',
  category: '',
  displayName: 'AngleDoubleRight'
});

export default AngleDoubleRight;
