// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AngleDoubleUpSvg from '@rsuite/icon-font/lib/legacy/AngleDoubleUp';

/**
 * @deprecated Will be removed in the next major version.
 */
const AngleDoubleUp = createSvgIcon({
  as: AngleDoubleUpSvg,
  ariaLabel: 'angle double up',
  category: '',
  displayName: 'AngleDoubleUp'
});

export default AngleDoubleUp;
