// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AngleDoubleLeftSvg from '@rsuite/icon-font/lib/legacy/AngleDoubleLeft';

/**
 * @deprecated Will be removed in the next major version.
 */
const AngleDoubleLeft = createSvgIcon({
  as: AngleDoubleLeftSvg,
  ariaLabel: 'angle double left',
  category: '',
  displayName: 'AngleDoubleLeft'
});

export default AngleDoubleLeft;
