// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AppleSvg from '@rsuite/icon-font/lib/legacy/Apple';

/**
 * @deprecated Will be removed in the next major version.
 */
const Apple = createSvgIcon({
  as: AppleSvg,
  ariaLabel: 'apple',
  category: '',
  displayName: 'Apple'
});

export default Apple;
