// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArchiveSvg from '@rsuite/icon-font/lib/legacy/Archive';

/**
 * @deprecated Will be removed in the next major version.
 */
const Archive = createSvgIcon({
  as: ArchiveSvg,
  ariaLabel: 'archive',
  category: '',
  displayName: 'Archive'
});

export default Archive;
