// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowCircleUpSvg from '@rsuite/icon-font/lib/legacy/ArrowCircleUp';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowCircleUp = createSvgIcon({
  as: ArrowCircleUpSvg,
  ariaLabel: 'arrow circle up',
  category: '',
  displayName: 'ArrowCircleUp'
});

export default ArrowCircleUp;
