// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowRightSvg from '@rsuite/icon-font/lib/legacy/ArrowRight';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowRight = createSvgIcon({
  as: ArrowRightSvg,
  ariaLabel: 'arrow right',
  category: '',
  displayName: 'ArrowRight'
});

export default ArrowRight;
