// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowDownLineSvg from '@rsuite/icon-font/lib/legacy/ArrowDownLine';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowDownLine = createSvgIcon({
  as: ArrowDownLineSvg,
  ariaLabel: 'arrow down line',
  category: '',
  displayName: 'ArrowDownLine'
});

export default ArrowDownLine;
