// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowUp2Svg from '@rsuite/icon-font/lib/legacy/ArrowUp2';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowUp2 = createSvgIcon({
  as: ArrowUp2Svg,
  ariaLabel: 'arrow up 2',
  category: '',
  displayName: 'ArrowUp2'
});

export default ArrowUp2;
