// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowCircleORightSvg from '@rsuite/icon-font/lib/legacy/ArrowCircleORight';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowCircleORight = createSvgIcon({
  as: ArrowCircleORightSvg,
  ariaLabel: 'arrow circle o right',
  category: '',
  displayName: 'ArrowCircleORight'
});

export default ArrowCircleORight;
