// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowLeftSvg from '@rsuite/icon-font/lib/legacy/ArrowLeft';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowLeft = createSvgIcon({
  as: ArrowLeftSvg,
  ariaLabel: 'arrow left',
  category: '',
  displayName: 'ArrowLeft'
});

export default ArrowLeft;
