// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowCircleDownSvg from '@rsuite/icon-font/lib/legacy/ArrowCircleDown';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowCircleDown = createSvgIcon({
  as: ArrowCircleDownSvg,
  ariaLabel: 'arrow circle down',
  category: '',
  displayName: 'ArrowCircleDown'
});

export default ArrowCircleDown;
