// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowCircleODownSvg from '@rsuite/icon-font/lib/legacy/ArrowCircleODown';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowCircleODown = createSvgIcon({
  as: ArrowCircleODownSvg,
  ariaLabel: 'arrow circle o down',
  category: '',
  displayName: 'ArrowCircleODown'
});

export default ArrowCircleODown;
