// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowUpSvg from '@rsuite/icon-font/lib/legacy/ArrowUp';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowUp = createSvgIcon({
  as: ArrowUpSvg,
  ariaLabel: 'arrow up',
  category: '',
  displayName: 'ArrowUp'
});

export default ArrowUp;
