// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowsVSvg from '@rsuite/icon-font/lib/legacy/ArrowsV';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowsV = createSvgIcon({
  as: ArrowsVSvg,
  ariaLabel: 'arrows v',
  category: '',
  displayName: 'ArrowsV'
});

export default ArrowsV;
