// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowLeftLineSvg from '@rsuite/icon-font/lib/legacy/ArrowLeftLine';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowLeftLine = createSvgIcon({
  as: ArrowLeftLineSvg,
  ariaLabel: 'arrow left line',
  category: '',
  displayName: 'ArrowLeftLine'
});

export default ArrowLeftLine;
