// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowUpLineSvg from '@rsuite/icon-font/lib/legacy/ArrowUpLine';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowUpLine = createSvgIcon({
  as: ArrowUpLineSvg,
  ariaLabel: 'arrow up line',
  category: '',
  displayName: 'ArrowUpLine'
});

export default ArrowUpLine;
