// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ArrowCircleLeftSvg from '@rsuite/icon-font/lib/legacy/ArrowCircleLeft';

/**
 * @deprecated Will be removed in the next major version.
 */
const ArrowCircleLeft = createSvgIcon({
  as: ArrowCircleLeftSvg,
  ariaLabel: 'arrow circle left',
  category: '',
  displayName: 'ArrowCircleLeft'
});

export default ArrowCircleLeft;
