// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AslInterpretingSvg from '@rsuite/icon-font/lib/legacy/AslInterpreting';

/**
 * @deprecated Will be removed in the next major version.
 */
const AslInterpreting = createSvgIcon({
  as: AslInterpretingSvg,
  ariaLabel: 'asl interpreting',
  category: '',
  displayName: 'AslInterpreting'
});

export default AslInterpreting;
