// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AsteriskSvg from '@rsuite/icon-font/lib/legacy/Asterisk';

/**
 * @deprecated Will be removed in the next major version.
 */
const Asterisk = createSvgIcon({
  as: AsteriskSvg,
  ariaLabel: 'asterisk',
  category: '',
  displayName: 'Asterisk'
});

export default Asterisk;
