// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import AttributionSvg from '@rsuite/icon-font/lib/legacy/Attribution';

/**
 * @deprecated Will be removed in the next major version.
 */
const Attribution = createSvgIcon({
  as: AttributionSvg,
  ariaLabel: 'attribution',
  category: '',
  displayName: 'Attribution'
});

export default Attribution;
