// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BackArrowSvg from '@rsuite/icon-font/lib/legacy/BackArrow';

/**
 * @deprecated Will be removed in the next major version.
 */
const BackArrow = createSvgIcon({
  as: BackArrowSvg,
  ariaLabel: 'back arrow',
  category: '',
  displayName: 'BackArrow'
});

export default BackArrow;
