// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BackwardSvg from '@rsuite/icon-font/lib/legacy/Backward';

/**
 * @deprecated Will be removed in the next major version.
 */
const Backward = createSvgIcon({
  as: BackwardSvg,
  ariaLabel: 'backward',
  category: '',
  displayName: 'Backward'
});

export default Backward;
