// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BalanceScaleSvg from '@rsuite/icon-font/lib/legacy/BalanceScale';

/**
 * @deprecated Will be removed in the next major version.
 */
const BalanceScale = createSvgIcon({
  as: BalanceScaleSvg,
  ariaLabel: 'balance scale',
  category: '',
  displayName: 'BalanceScale'
});

export default BalanceScale;
