// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BanSvg from '@rsuite/icon-font/lib/legacy/Ban';

/**
 * @deprecated Will be removed in the next major version.
 */
const Ban = createSvgIcon({
  as: BanSvg,
  ariaLabel: 'ban',
  category: '',
  displayName: 'Ban'
});

export default Ban;
