// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BandcampSvg from '@rsuite/icon-font/lib/legacy/Bandcamp';

/**
 * @deprecated Will be removed in the next major version.
 */
const Bandcamp = createSvgIcon({
  as: BandcampSvg,
  ariaLabel: 'bandcamp',
  category: '',
  displayName: 'Bandcamp'
});

export default Bandcamp;
