// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BarChartSvg from '@rsuite/icon-font/lib/legacy/BarChart';

/**
 * @deprecated Will be removed in the next major version.
 */
const BarChart = createSvgIcon({
  as: BarChartSvg,
  ariaLabel: 'bar chart',
  category: '',
  displayName: 'BarChart'
});

export default BarChart;
