// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BarChartRankingSvg from '@rsuite/icon-font/lib/legacy/BarChartRanking';

/**
 * @deprecated Will be removed in the next major version.
 */
const BarChartRanking = createSvgIcon({
  as: BarChartRankingSvg,
  ariaLabel: 'bar chart ranking',
  category: '',
  displayName: 'BarChartRanking'
});

export default BarChartRanking;
