// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BarsSvg from '@rsuite/icon-font/lib/legacy/Bars';

/**
 * @deprecated Will be removed in the next major version.
 */
const Bars = createSvgIcon({
  as: BarsSvg,
  ariaLabel: 'bars',
  category: '',
  displayName: 'Bars'
});

export default Bars;
