// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Battery0Svg from '@rsuite/icon-font/lib/legacy/Battery0';

/**
 * @deprecated Will be removed in the next major version.
 */
const Battery0 = createSvgIcon({
  as: Battery0Svg,
  ariaLabel: 'battery 0',
  category: '',
  displayName: 'Battery0'
});

export default Battery0;
