// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BeerSvg from '@rsuite/icon-font/lib/legacy/Beer';

/**
 * @deprecated Will be removed in the next major version.
 */
const Beer = createSvgIcon({
  as: BeerSvg,
  ariaLabel: 'beer',
  category: '',
  displayName: 'Beer'
});

export default Beer;
