// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BehanceSvg from '@rsuite/icon-font/lib/legacy/Behance';

/**
 * @deprecated Will be removed in the next major version.
 */
const Behance = createSvgIcon({
  as: BehanceSvg,
  ariaLabel: 'behance',
  category: '',
  displayName: 'Behance'
});

export default Behance;
