// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BehanceSquareSvg from '@rsuite/icon-font/lib/legacy/BehanceSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const BehanceSquare = createSvgIcon({
  as: BehanceSquareSvg,
  ariaLabel: 'behance square',
  category: '',
  displayName: 'BehanceSquare'
});

export default BehanceSquare;
