// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BellSvg from '@rsuite/icon-font/lib/legacy/Bell';

/**
 * @deprecated Will be removed in the next major version.
 */
const Bell = createSvgIcon({
  as: BellSvg,
  ariaLabel: 'bell',
  category: '',
  displayName: 'Bell'
});

export default Bell;
