// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BellSlashOSvg from '@rsuite/icon-font/lib/legacy/BellSlashO';

/**
 * @deprecated Will be removed in the next major version.
 */
const BellSlashO = createSvgIcon({
  as: BellSlashOSvg,
  ariaLabel: 'bell slash o',
  category: '',
  displayName: 'BellSlashO'
});

export default BellSlashO;
