// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BellSlashSvg from '@rsuite/icon-font/lib/legacy/BellSlash';

/**
 * @deprecated Will be removed in the next major version.
 */
const BellSlash = createSvgIcon({
  as: BellSlashSvg,
  ariaLabel: 'bell slash',
  category: '',
  displayName: 'BellSlash'
});

export default BellSlash;
