// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BinocularsSvg from '@rsuite/icon-font/lib/legacy/Binoculars';

/**
 * @deprecated Will be removed in the next major version.
 */
const Binoculars = createSvgIcon({
  as: BinocularsSvg,
  ariaLabel: 'binoculars',
  category: '',
  displayName: 'Binoculars'
});

export default Binoculars;
