// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BirthdayCakeSvg from '@rsuite/icon-font/lib/legacy/BirthdayCake';

/**
 * @deprecated Will be removed in the next major version.
 */
const BirthdayCake = createSvgIcon({
  as: BirthdayCakeSvg,
  ariaLabel: 'birthday cake',
  category: '',
  displayName: 'BirthdayCake'
});

export default BirthdayCake;
