// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BluetoothBSvg from '@rsuite/icon-font/lib/legacy/BluetoothB';

/**
 * @deprecated Will be removed in the next major version.
 */
const BluetoothB = createSvgIcon({
  as: BluetoothBSvg,
  ariaLabel: 'bluetooth b',
  category: '',
  displayName: 'BluetoothB'
});

export default BluetoothB;
