// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BoldSvg from '@rsuite/icon-font/lib/legacy/Bold';

/**
 * @deprecated Will be removed in the next major version.
 */
const Bold = createSvgIcon({
  as: BoldSvg,
  ariaLabel: 'bold',
  category: '',
  displayName: 'Bold'
});

export default Bold;
