// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BombSvg from '@rsuite/icon-font/lib/legacy/Bomb';

/**
 * @deprecated Will be removed in the next major version.
 */
const Bomb = createSvgIcon({
  as: BombSvg,
  ariaLabel: 'bomb',
  category: '',
  displayName: 'Bomb'
});

export default Bomb;
