// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BookSvg from '@rsuite/icon-font/lib/legacy/Book';

/**
 * @deprecated Will be removed in the next major version.
 */
const Book = createSvgIcon({
  as: BookSvg,
  ariaLabel: 'book',
  category: '',
  displayName: 'Book'
});

export default Book;
