// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BookmarkOSvg from '@rsuite/icon-font/lib/legacy/BookmarkO';

/**
 * @deprecated Will be removed in the next major version.
 */
const BookmarkO = createSvgIcon({
  as: BookmarkOSvg,
  ariaLabel: 'bookmark o',
  category: '',
  displayName: 'BookmarkO'
});

export default BookmarkO;
