// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BrailleSvg from '@rsuite/icon-font/lib/legacy/Braille';

/**
 * @deprecated Will be removed in the next major version.
 */
const Braille = createSvgIcon({
  as: BrailleSvg,
  ariaLabel: 'braille',
  category: '',
  displayName: 'Braille'
});

export default Braille;
