// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BtcSvg from '@rsuite/icon-font/lib/legacy/Btc';

/**
 * @deprecated Will be removed in the next major version.
 */
const Btc = createSvgIcon({
  as: BtcSvg,
  ariaLabel: 'btc',
  category: '',
  displayName: 'Btc'
});

export default Btc;
