// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BtnOffSvg from '@rsuite/icon-font/lib/legacy/BtnOff';

/**
 * @deprecated Will be removed in the next major version.
 */
const BtnOff = createSvgIcon({
  as: BtnOffSvg,
  ariaLabel: 'btn off',
  category: '',
  displayName: 'BtnOff'
});

export default BtnOff;
