// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BtnOnSvg from '@rsuite/icon-font/lib/legacy/BtnOn';

/**
 * @deprecated Will be removed in the next major version.
 */
const BtnOn = createSvgIcon({
  as: BtnOnSvg,
  ariaLabel: 'btn on',
  category: '',
  displayName: 'BtnOn'
});

export default BtnOn;
