// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BugSvg from '@rsuite/icon-font/lib/legacy/Bug';

/**
 * @deprecated Will be removed in the next major version.
 */
const Bug = createSvgIcon({
  as: BugSvg,
  ariaLabel: 'bug',
  category: '',
  displayName: 'Bug'
});

export default Bug;
