// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Building2Svg from '@rsuite/icon-font/lib/legacy/Building2';

/**
 * @deprecated Will be removed in the next major version.
 */
const Building2 = createSvgIcon({
  as: Building2Svg,
  ariaLabel: 'building 2',
  category: '',
  displayName: 'Building2'
});

export default Building2;
