// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BuildingOSvg from '@rsuite/icon-font/lib/legacy/BuildingO';

/**
 * @deprecated Will be removed in the next major version.
 */
const BuildingO = createSvgIcon({
  as: BuildingOSvg,
  ariaLabel: 'building o',
  category: '',
  displayName: 'BuildingO'
});

export default BuildingO;
