// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BullseyeSvg from '@rsuite/icon-font/lib/legacy/Bullseye';

/**
 * @deprecated Will be removed in the next major version.
 */
const Bullseye = createSvgIcon({
  as: BullseyeSvg,
  ariaLabel: 'bullseye',
  category: '',
  displayName: 'Bullseye'
});

export default Bullseye;
