// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import BusSvg from '@rsuite/icon-font/lib/legacy/Bus';

/**
 * @deprecated Will be removed in the next major version.
 */
const Bus = createSvgIcon({
  as: BusSvg,
  ariaLabel: 'bus',
  category: '',
  displayName: 'Bus'
});

export default Bus;
