// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CabSvg from '@rsuite/icon-font/lib/legacy/Cab';

/**
 * @deprecated Will be removed in the next major version.
 */
const Cab = createSvgIcon({
  as: CabSvg,
  ariaLabel: 'cab',
  category: '',
  displayName: 'Cab'
});

export default Cab;
