// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CalendarOSvg from '@rsuite/icon-font/lib/legacy/CalendarO';

/**
 * @deprecated Will be removed in the next major version.
 */
const CalendarO = createSvgIcon({
  as: CalendarOSvg,
  ariaLabel: 'calendar o',
  category: '',
  displayName: 'CalendarO'
});

export default CalendarO;
