// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CalendarMinusOSvg from '@rsuite/icon-font/lib/legacy/CalendarMinusO';

/**
 * @deprecated Will be removed in the next major version.
 */
const CalendarMinusO = createSvgIcon({
  as: CalendarMinusOSvg,
  ariaLabel: 'calendar minus o',
  category: '',
  displayName: 'CalendarMinusO'
});

export default CalendarMinusO;
