// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CalendarPlusOSvg from '@rsuite/icon-font/lib/legacy/CalendarPlusO';

/**
 * @deprecated Will be removed in the next major version.
 */
const CalendarPlusO = createSvgIcon({
  as: CalendarPlusOSvg,
  ariaLabel: 'calendar plus o',
  category: '',
  displayName: 'CalendarPlusO'
});

export default CalendarPlusO;
