// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CalendarSvg from '@rsuite/icon-font/lib/legacy/Calendar';

/**
 * @deprecated Will be removed in the next major version.
 */
const Calendar = createSvgIcon({
  as: CalendarSvg,
  ariaLabel: 'calendar',
  category: '',
  displayName: 'Calendar'
});

export default Calendar;
