// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CalendarCheckOSvg from '@rsuite/icon-font/lib/legacy/CalendarCheckO';

/**
 * @deprecated Will be removed in the next major version.
 */
const CalendarCheckO = createSvgIcon({
  as: CalendarCheckOSvg,
  ariaLabel: 'calendar check o',
  category: '',
  displayName: 'CalendarCheckO'
});

export default CalendarCheckO;
