// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CameraRetroSvg from '@rsuite/icon-font/lib/legacy/CameraRetro';

/**
 * @deprecated Will be removed in the next major version.
 */
const CameraRetro = createSvgIcon({
  as: CameraRetroSvg,
  ariaLabel: 'camera retro',
  category: '',
  displayName: 'CameraRetro'
});

export default CameraRetro;
