// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CaretLeftSvg from '@rsuite/icon-font/lib/legacy/CaretLeft';

/**
 * @deprecated Will be removed in the next major version.
 */
const CaretLeft = createSvgIcon({
  as: CaretLeftSvg,
  ariaLabel: 'caret left',
  category: '',
  displayName: 'CaretLeft'
});

export default CaretLeft;
