// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CaretRightSvg from '@rsuite/icon-font/lib/legacy/CaretRight';

/**
 * @deprecated Will be removed in the next major version.
 */
const CaretRight = createSvgIcon({
  as: CaretRightSvg,
  ariaLabel: 'caret right',
  category: '',
  displayName: 'CaretRight'
});

export default CaretRight;
