// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CartArrowDownSvg from '@rsuite/icon-font/lib/legacy/CartArrowDown';

/**
 * @deprecated Will be removed in the next major version.
 */
const CartArrowDown = createSvgIcon({
  as: CartArrowDownSvg,
  ariaLabel: 'cart arrow down',
  category: '',
  displayName: 'CartArrowDown'
});

export default CartArrowDown;
