// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CcSvg from '@rsuite/icon-font/lib/legacy/Cc';

/**
 * @deprecated Will be removed in the next major version.
 */
const Cc = createSvgIcon({
  as: CcSvg,
  ariaLabel: 'cc',
  category: '',
  displayName: 'Cc'
});

export default Cc;
