// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CcAmexSvg from '@rsuite/icon-font/lib/legacy/CcAmex';

/**
 * @deprecated Will be removed in the next major version.
 */
const CcAmex = createSvgIcon({
  as: CcAmexSvg,
  ariaLabel: 'cc amex',
  category: '',
  displayName: 'CcAmex'
});

export default CcAmex;
