// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CcDinersClubSvg from '@rsuite/icon-font/lib/legacy/CcDinersClub';

/**
 * @deprecated Will be removed in the next major version.
 */
const CcDinersClub = createSvgIcon({
  as: CcDinersClubSvg,
  ariaLabel: 'cc diners club',
  category: '',
  displayName: 'CcDinersClub'
});

export default CcDinersClub;
