// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CcDiscoverSvg from '@rsuite/icon-font/lib/legacy/CcDiscover';

/**
 * @deprecated Will be removed in the next major version.
 */
const CcDiscover = createSvgIcon({
  as: CcDiscoverSvg,
  ariaLabel: 'cc discover',
  category: '',
  displayName: 'CcDiscover'
});

export default CcDiscover;
