// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CcJcbSvg from '@rsuite/icon-font/lib/legacy/CcJcb';

/**
 * @deprecated Will be removed in the next major version.
 */
const CcJcb = createSvgIcon({
  as: CcJcbSvg,
  ariaLabel: 'cc jcb',
  category: '',
  displayName: 'CcJcb'
});

export default CcJcb;
