// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CcMastercardSvg from '@rsuite/icon-font/lib/legacy/CcMastercard';

/**
 * @deprecated Will be removed in the next major version.
 */
const CcMastercard = createSvgIcon({
  as: CcMastercardSvg,
  ariaLabel: 'cc mastercard',
  category: '',
  displayName: 'CcMastercard'
});

export default CcMastercard;
