// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CcVisaSvg from '@rsuite/icon-font/lib/legacy/CcVisa';

/**
 * @deprecated Will be removed in the next major version.
 */
const CcVisa = createSvgIcon({
  as: CcVisaSvg,
  ariaLabel: 'cc visa',
  category: '',
  displayName: 'CcVisa'
});

export default CcVisa;
