// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CertificateSvg from '@rsuite/icon-font/lib/legacy/Certificate';

/**
 * @deprecated Will be removed in the next major version.
 */
const Certificate = createSvgIcon({
  as: CertificateSvg,
  ariaLabel: 'certificate',
  category: '',
  displayName: 'Certificate'
});

export default Certificate;
