// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CharacterAreaSvg from '@rsuite/icon-font/lib/legacy/CharacterArea';

/**
 * @deprecated Will be removed in the next major version.
 */
const CharacterArea = createSvgIcon({
  as: CharacterAreaSvg,
  ariaLabel: 'character area',
  category: '',
  displayName: 'CharacterArea'
});

export default CharacterArea;
