// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CharacterAuthorizeSvg from '@rsuite/icon-font/lib/legacy/CharacterAuthorize';

/**
 * @deprecated Will be removed in the next major version.
 */
const CharacterAuthorize = createSvgIcon({
  as: CharacterAuthorizeSvg,
  ariaLabel: 'character authorize',
  category: '',
  displayName: 'CharacterAuthorize'
});

export default CharacterAuthorize;
