// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ChartsLineSvg from '@rsuite/icon-font/lib/legacy/ChartsLine';

/**
 * @deprecated Will be removed in the next major version.
 */
const ChartsLine = createSvgIcon({
  as: ChartsLineSvg,
  ariaLabel: 'charts line',
  category: '',
  displayName: 'ChartsLine'
});

export default ChartsLine;
