// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ChartsSvg from '@rsuite/icon-font/lib/legacy/Charts';

/**
 * @deprecated Will be removed in the next major version.
 */
const Charts = createSvgIcon({
  as: ChartsSvg,
  ariaLabel: 'charts',
  category: '',
  displayName: 'Charts'
});

export default Charts;
