// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CheckSvg from '@rsuite/icon-font/lib/legacy/Check';

/**
 * @deprecated Will be removed in the next major version.
 */
const Check = createSvgIcon({
  as: CheckSvg,
  ariaLabel: 'check',
  category: '',
  displayName: 'Check'
});

export default Check;
