// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ChevronUpSvg from '@rsuite/icon-font/lib/legacy/ChevronUp';

/**
 * @deprecated Will be removed in the next major version.
 */
const ChevronUp = createSvgIcon({
  as: ChevronUpSvg,
  ariaLabel: 'chevron up',
  category: '',
  displayName: 'ChevronUp'
});

export default ChevronUp;
