// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ChevronCircleDownSvg from '@rsuite/icon-font/lib/legacy/ChevronCircleDown';

/**
 * @deprecated Will be removed in the next major version.
 */
const ChevronCircleDown = createSvgIcon({
  as: ChevronCircleDownSvg,
  ariaLabel: 'chevron circle down',
  category: '',
  displayName: 'ChevronCircleDown'
});

export default ChevronCircleDown;
