// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ChevronDownSvg from '@rsuite/icon-font/lib/legacy/ChevronDown';

/**
 * @deprecated Will be removed in the next major version.
 */
const ChevronDown = createSvgIcon({
  as: ChevronDownSvg,
  ariaLabel: 'chevron down',
  category: '',
  displayName: 'ChevronDown'
});

export default ChevronDown;
