// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ChevronCircleRightSvg from '@rsuite/icon-font/lib/legacy/ChevronCircleRight';

/**
 * @deprecated Will be removed in the next major version.
 */
const ChevronCircleRight = createSvgIcon({
  as: ChevronCircleRightSvg,
  ariaLabel: 'chevron circle right',
  category: '',
  displayName: 'ChevronCircleRight'
});

export default ChevronCircleRight;
