// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ChevronRightSvg from '@rsuite/icon-font/lib/legacy/ChevronRight';

/**
 * @deprecated Will be removed in the next major version.
 */
const ChevronRight = createSvgIcon({
  as: ChevronRightSvg,
  ariaLabel: 'chevron right',
  category: '',
  displayName: 'ChevronRight'
});

export default ChevronRight;
