// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ChevronLeftSvg from '@rsuite/icon-font/lib/legacy/ChevronLeft';

/**
 * @deprecated Will be removed in the next major version.
 */
const ChevronLeft = createSvgIcon({
  as: ChevronLeftSvg,
  ariaLabel: 'chevron left',
  category: '',
  displayName: 'ChevronLeft'
});

export default ChevronLeft;
