// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ChildSvg from '@rsuite/icon-font/lib/legacy/Child';

/**
 * @deprecated Will be removed in the next major version.
 */
const Child = createSvgIcon({
  as: ChildSvg,
  ariaLabel: 'child',
  category: '',
  displayName: 'Child'
});

export default Child;
