// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ChromeSvg from '@rsuite/icon-font/lib/legacy/Chrome';

/**
 * @deprecated Will be removed in the next major version.
 */
const Chrome = createSvgIcon({
  as: ChromeSvg,
  ariaLabel: 'chrome',
  category: '',
  displayName: 'Chrome'
});

export default Chrome;
