// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ClockOSvg from '@rsuite/icon-font/lib/legacy/ClockO';

/**
 * @deprecated Will be removed in the next major version.
 */
const ClockO = createSvgIcon({
  as: ClockOSvg,
  ariaLabel: 'clock o',
  category: '',
  displayName: 'ClockO'
});

export default ClockO;
