// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CloneSvg from '@rsuite/icon-font/lib/legacy/Clone';

/**
 * @deprecated Will be removed in the next major version.
 */
const Clone = createSvgIcon({
  as: CloneSvg,
  ariaLabel: 'clone',
  category: '',
  displayName: 'Clone'
});

export default Clone;
