// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CloudSvg from '@rsuite/icon-font/lib/legacy/Cloud';

/**
 * @deprecated Will be removed in the next major version.
 */
const Cloud = createSvgIcon({
  as: CloudSvg,
  ariaLabel: 'cloud',
  category: '',
  displayName: 'Cloud'
});

export default Cloud;
