// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CodeSvg from '@rsuite/icon-font/lib/legacy/Code';

/**
 * @deprecated Will be removed in the next major version.
 */
const Code = createSvgIcon({
  as: CodeSvg,
  ariaLabel: 'code',
  category: '',
  displayName: 'Code'
});

export default Code;
