// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CogSvg from '@rsuite/icon-font/lib/legacy/Cog';

/**
 * @deprecated Will be removed in the next major version.
 */
const Cog = createSvgIcon({
  as: CogSvg,
  ariaLabel: 'cog',
  category: '',
  displayName: 'Cog'
});

export default Cog;
