// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CoincideSvg from '@rsuite/icon-font/lib/legacy/Coincide';

/**
 * @deprecated Will be removed in the next major version.
 */
const Coincide = createSvgIcon({
  as: CoincideSvg,
  ariaLabel: 'coincide',
  category: '',
  displayName: 'Coincide'
});

export default Coincide;
