// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CollaspedSvg from '@rsuite/icon-font/lib/legacy/Collasped';

/**
 * @deprecated Will be removed in the next major version.
 */
const Collasped = createSvgIcon({
  as: CollaspedSvg,
  ariaLabel: 'collasped',
  category: '',
  displayName: 'Collasped'
});

export default Collasped;
