// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CollaspedOSvg from '@rsuite/icon-font/lib/legacy/CollaspedO';

/**
 * @deprecated Will be removed in the next major version.
 */
const CollaspedO = createSvgIcon({
  as: CollaspedOSvg,
  ariaLabel: 'collasped o',
  category: '',
  displayName: 'CollaspedO'
});

export default CollaspedO;
