// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CommentingOSvg from '@rsuite/icon-font/lib/legacy/CommentingO';

/**
 * @deprecated Will be removed in the next major version.
 */
const CommentingO = createSvgIcon({
  as: CommentingOSvg,
  ariaLabel: 'commenting o',
  category: '',
  displayName: 'CommentingO'
});

export default CommentingO;
