// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CommentingSvg from '@rsuite/icon-font/lib/legacy/Commenting';

/**
 * @deprecated Will be removed in the next major version.
 */
const Commenting = createSvgIcon({
  as: CommentingSvg,
  ariaLabel: 'commenting',
  category: '',
  displayName: 'Commenting'
});

export default Commenting;
