// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CommentSvg from '@rsuite/icon-font/lib/legacy/Comment';

/**
 * @deprecated Will be removed in the next major version.
 */
const Comment = createSvgIcon({
  as: CommentSvg,
  ariaLabel: 'comment',
  category: '',
  displayName: 'Comment'
});

export default Comment;
