// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CommentsSvg from '@rsuite/icon-font/lib/legacy/Comments';

/**
 * @deprecated Will be removed in the next major version.
 */
const Comments = createSvgIcon({
  as: CommentsSvg,
  ariaLabel: 'comments',
  category: '',
  displayName: 'Comments'
});

export default Comments;
