// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CommentOSvg from '@rsuite/icon-font/lib/legacy/CommentO';

/**
 * @deprecated Will be removed in the next major version.
 */
const CommentO = createSvgIcon({
  as: CommentOSvg,
  ariaLabel: 'comment o',
  category: '',
  displayName: 'CommentO'
});

export default CommentO;
