// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ContaoSvg from '@rsuite/icon-font/lib/legacy/Contao';

/**
 * @deprecated Will be removed in the next major version.
 */
const Contao = createSvgIcon({
  as: ContaoSvg,
  ariaLabel: 'contao',
  category: '',
  displayName: 'Contao'
});

export default Contao;
