// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CopyrightSvg from '@rsuite/icon-font/lib/legacy/Copyright';

/**
 * @deprecated Will be removed in the next major version.
 */
const Copyright = createSvgIcon({
  as: CopyrightSvg,
  ariaLabel: 'copyright',
  category: '',
  displayName: 'Copyright'
});

export default Copyright;
