// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CopyOSvg from '@rsuite/icon-font/lib/legacy/CopyO';

/**
 * @deprecated Will be removed in the next major version.
 */
const CopyO = createSvgIcon({
  as: CopyOSvg,
  ariaLabel: 'copy o',
  category: '',
  displayName: 'CopyO'
});

export default CopyO;
