// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CopySvg from '@rsuite/icon-font/lib/legacy/Copy';

/**
 * @deprecated Will be removed in the next major version.
 */
const Copy = createSvgIcon({
  as: CopySvg,
  ariaLabel: 'copy',
  category: '',
  displayName: 'Copy'
});

export default Copy;
