// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CreativeCommonsSvg from '@rsuite/icon-font/lib/legacy/CreativeCommons';

/**
 * @deprecated Will be removed in the next major version.
 */
const CreativeCommons = createSvgIcon({
  as: CreativeCommonsSvg,
  ariaLabel: 'creative commons',
  category: '',
  displayName: 'CreativeCommons'
});

export default CreativeCommons;
