// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CreditCardAltSvg from '@rsuite/icon-font/lib/legacy/CreditCardAlt';

/**
 * @deprecated Will be removed in the next major version.
 */
const CreditCardAlt = createSvgIcon({
  as: CreditCardAltSvg,
  ariaLabel: 'credit card alt',
  category: '',
  displayName: 'CreditCardAlt'
});

export default CreditCardAlt;
