// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CreditCardSvg from '@rsuite/icon-font/lib/legacy/CreditCard';

/**
 * @deprecated Will be removed in the next major version.
 */
const CreditCard = createSvgIcon({
  as: CreditCardSvg,
  ariaLabel: 'credit card',
  category: '',
  displayName: 'CreditCard'
});

export default CreditCard;
