// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CubeSvg from '@rsuite/icon-font/lib/legacy/Cube';

/**
 * @deprecated Will be removed in the next major version.
 */
const Cube = createSvgIcon({
  as: CubeSvg,
  ariaLabel: 'cube',
  category: '',
  displayName: 'Cube'
});

export default Cube;
