// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CutSvg from '@rsuite/icon-font/lib/legacy/Cut';

/**
 * @deprecated Will be removed in the next major version.
 */
const Cut = createSvgIcon({
  as: CutSvg,
  ariaLabel: 'cut',
  category: '',
  displayName: 'Cut'
});

export default Cut;
