// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import CutlerySvg from '@rsuite/icon-font/lib/legacy/Cutlery';

/**
 * @deprecated Will be removed in the next major version.
 */
const Cutlery = createSvgIcon({
  as: CutlerySvg,
  ariaLabel: 'cutlery',
  category: '',
  displayName: 'Cutlery'
});

export default Cutlery;
