// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DataAuthorizeSvg from '@rsuite/icon-font/lib/legacy/DataAuthorize';

/**
 * @deprecated Will be removed in the next major version.
 */
const DataAuthorize = createSvgIcon({
  as: DataAuthorizeSvg,
  ariaLabel: 'data authorize',
  category: '',
  displayName: 'DataAuthorize'
});

export default DataAuthorize;
