// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DataIncreaseSvg from '@rsuite/icon-font/lib/legacy/DataIncrease';

/**
 * @deprecated Will be removed in the next major version.
 */
const DataIncrease = createSvgIcon({
  as: DataIncreaseSvg,
  ariaLabel: 'data increase',
  category: '',
  displayName: 'DataIncrease'
});

export default DataIncrease;
