// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DatabaseSvg from '@rsuite/icon-font/lib/legacy/Database';

/**
 * @deprecated Will be removed in the next major version.
 */
const Database = createSvgIcon({
  as: DatabaseSvg,
  ariaLabel: 'database',
  category: '',
  displayName: 'Database'
});

export default Database;
