// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DeafSvg from '@rsuite/icon-font/lib/legacy/Deaf';

/**
 * @deprecated Will be removed in the next major version.
 */
const Deaf = createSvgIcon({
  as: DeafSvg,
  ariaLabel: 'deaf',
  category: '',
  displayName: 'Deaf'
});

export default Deaf;
