// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DedentSvg from '@rsuite/icon-font/lib/legacy/Dedent';

/**
 * @deprecated Will be removed in the next major version.
 */
const Dedent = createSvgIcon({
  as: DedentSvg,
  ariaLabel: 'dedent',
  category: '',
  displayName: 'Dedent'
});

export default Dedent;
