// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DesktopSvg from '@rsuite/icon-font/lib/legacy/Desktop';

/**
 * @deprecated Will be removed in the next major version.
 */
const Desktop = createSvgIcon({
  as: DesktopSvg,
  ariaLabel: 'desktop',
  category: '',
  displayName: 'Desktop'
});

export default Desktop;
