// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DetailSvg from '@rsuite/icon-font/lib/legacy/Detail';

/**
 * @deprecated Will be removed in the next major version.
 */
const Detail = createSvgIcon({
  as: DetailSvg,
  ariaLabel: 'detail',
  category: '',
  displayName: 'Detail'
});

export default Detail;
