// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DiggSvg from '@rsuite/icon-font/lib/legacy/Digg';

/**
 * @deprecated Will be removed in the next major version.
 */
const Digg = createSvgIcon({
  as: DiggSvg,
  ariaLabel: 'digg',
  category: '',
  displayName: 'Digg'
});

export default Digg;
