// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DotCircleOSvg from '@rsuite/icon-font/lib/legacy/DotCircleO';

/**
 * @deprecated Will be removed in the next major version.
 */
const DotCircleO = createSvgIcon({
  as: DotCircleOSvg,
  ariaLabel: 'dot circle o',
  category: '',
  displayName: 'DotCircleO'
});

export default DotCircleO;
