// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DownloadSvg from '@rsuite/icon-font/lib/legacy/Download';

/**
 * @deprecated Will be removed in the next major version.
 */
const Download = createSvgIcon({
  as: DownloadSvg,
  ariaLabel: 'download',
  category: '',
  displayName: 'Download'
});

export default Download;
