// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Download2Svg from '@rsuite/icon-font/lib/legacy/Download2';

/**
 * @deprecated Will be removed in the next major version.
 */
const Download2 = createSvgIcon({
  as: Download2Svg,
  ariaLabel: 'download 2',
  category: '',
  displayName: 'Download2'
});

export default Download2;
