// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DropboxSvg from '@rsuite/icon-font/lib/legacy/Dropbox';

/**
 * @deprecated Will be removed in the next major version.
 */
const Dropbox = createSvgIcon({
  as: DropboxSvg,
  ariaLabel: 'dropbox',
  category: '',
  displayName: 'Dropbox'
});

export default Dropbox;
