// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import DrupalSvg from '@rsuite/icon-font/lib/legacy/Drupal';

/**
 * @deprecated Will be removed in the next major version.
 */
const Drupal = createSvgIcon({
  as: DrupalSvg,
  ariaLabel: 'drupal',
  category: '',
  displayName: 'Drupal'
});

export default Drupal;
