// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import EdgeSvg from '@rsuite/icon-font/lib/legacy/Edge';

/**
 * @deprecated Will be removed in the next major version.
 */
const Edge = createSvgIcon({
  as: EdgeSvg,
  ariaLabel: 'edge',
  category: '',
  displayName: 'Edge'
});

export default Edge;
