// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import EnvelopeSvg from '@rsuite/icon-font/lib/legacy/Envelope';

/**
 * @deprecated Will be removed in the next major version.
 */
const Envelope = createSvgIcon({
  as: EnvelopeSvg,
  ariaLabel: 'envelope',
  category: '',
  displayName: 'Envelope'
});

export default Envelope;
