// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import EnvelopeSquareSvg from '@rsuite/icon-font/lib/legacy/EnvelopeSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const EnvelopeSquare = createSvgIcon({
  as: EnvelopeSquareSvg,
  ariaLabel: 'envelope square',
  category: '',
  displayName: 'EnvelopeSquare'
});

export default EnvelopeSquare;
