// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import EnvelopeOpenSvg from '@rsuite/icon-font/lib/legacy/EnvelopeOpen';

/**
 * @deprecated Will be removed in the next major version.
 */
const EnvelopeOpen = createSvgIcon({
  as: EnvelopeOpenSvg,
  ariaLabel: 'envelope open',
  category: '',
  displayName: 'EnvelopeOpen'
});

export default EnvelopeOpen;
