// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import EraserSvg from '@rsuite/icon-font/lib/legacy/Eraser';

/**
 * @deprecated Will be removed in the next major version.
 */
const Eraser = createSvgIcon({
  as: EraserSvg,
  ariaLabel: 'eraser',
  category: '',
  displayName: 'Eraser'
});

export default Eraser;
