// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ExclamationSvg from '@rsuite/icon-font/lib/legacy/Exclamation';

/**
 * @deprecated Will be removed in the next major version.
 */
const Exclamation = createSvgIcon({
  as: ExclamationSvg,
  ariaLabel: 'exclamation',
  category: '',
  displayName: 'Exclamation'
});

export default Exclamation;
