// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ExclamationTriangleSvg from '@rsuite/icon-font/lib/legacy/ExclamationTriangle';

/**
 * @deprecated Will be removed in the next major version.
 */
const ExclamationTriangle = createSvgIcon({
  as: ExclamationTriangleSvg,
  ariaLabel: 'exclamation triangle',
  category: '',
  displayName: 'ExclamationTriangle'
});

export default ExclamationTriangle;
