// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ExitSvg from '@rsuite/icon-font/lib/legacy/Exit';

/**
 * @deprecated Will be removed in the next major version.
 */
const Exit = createSvgIcon({
  as: ExitSvg,
  ariaLabel: 'exit',
  category: '',
  displayName: 'Exit'
});

export default Exit;
