// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ExpandOSvg from '@rsuite/icon-font/lib/legacy/ExpandO';

/**
 * @deprecated Will be removed in the next major version.
 */
const ExpandO = createSvgIcon({
  as: ExpandOSvg,
  ariaLabel: 'expand o',
  category: '',
  displayName: 'ExpandO'
});

export default ExpandO;
