// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ExpandSvg from '@rsuite/icon-font/lib/legacy/Expand';

/**
 * @deprecated Will be removed in the next major version.
 */
const Expand = createSvgIcon({
  as: ExpandSvg,
  ariaLabel: 'expand',
  category: '',
  displayName: 'Expand'
});

export default Expand;
