// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ExploreSvg from '@rsuite/icon-font/lib/legacy/Explore';

/**
 * @deprecated Will be removed in the next major version.
 */
const Explore = createSvgIcon({
  as: ExploreSvg,
  ariaLabel: 'explore',
  category: '',
  displayName: 'Explore'
});

export default Explore;
