// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ExternalLinkSvg from '@rsuite/icon-font/lib/legacy/ExternalLink';

/**
 * @deprecated Will be removed in the next major version.
 */
const ExternalLink = createSvgIcon({
  as: ExternalLinkSvg,
  ariaLabel: 'external link',
  category: '',
  displayName: 'ExternalLink'
});

export default ExternalLink;
