// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import EyeSlashSvg from '@rsuite/icon-font/lib/legacy/EyeSlash';

/**
 * @deprecated Will be removed in the next major version.
 */
const EyeSlash = createSvgIcon({
  as: EyeSlashSvg,
  ariaLabel: 'eye slash',
  category: '',
  displayName: 'EyeSlash'
});

export default EyeSlash;
