// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FaSvg from '@rsuite/icon-font/lib/legacy/Fa';

/**
 * @deprecated Will be removed in the next major version.
 */
const Fa = createSvgIcon({
  as: FaSvg,
  ariaLabel: 'fa',
  category: '',
  displayName: 'Fa'
});

export default Fa;
