// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FastBackwardSvg from '@rsuite/icon-font/lib/legacy/FastBackward';

/**
 * @deprecated Will be removed in the next major version.
 */
const FastBackward = createSvgIcon({
  as: FastBackwardSvg,
  ariaLabel: 'fast backward',
  category: '',
  displayName: 'FastBackward'
});

export default FastBackward;
