// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FastForwardSvg from '@rsuite/icon-font/lib/legacy/FastForward';

/**
 * @deprecated Will be removed in the next major version.
 */
const FastForward = createSvgIcon({
  as: FastForwardSvg,
  ariaLabel: 'fast forward',
  category: '',
  displayName: 'FastForward'
});

export default FastForward;
