// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FaxSvg from '@rsuite/icon-font/lib/legacy/Fax';

/**
 * @deprecated Will be removed in the next major version.
 */
const Fax = createSvgIcon({
  as: FaxSvg,
  ariaLabel: 'fax',
  category: '',
  displayName: 'Fax'
});

export default Fax;
