// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FighterJetSvg from '@rsuite/icon-font/lib/legacy/FighterJet';

/**
 * @deprecated Will be removed in the next major version.
 */
const FighterJet = createSvgIcon({
  as: FighterJetSvg,
  ariaLabel: 'fighter jet',
  category: '',
  displayName: 'FighterJet'
});

export default FighterJet;
