// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FileWordOSvg from '@rsuite/icon-font/lib/legacy/FileWordO';

/**
 * @deprecated Will be removed in the next major version.
 */
const FileWordO = createSvgIcon({
  as: FileWordOSvg,
  ariaLabel: 'file word o',
  category: '',
  displayName: 'FileWordO'
});

export default FileWordO;
