// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FileCodeOSvg from '@rsuite/icon-font/lib/legacy/FileCodeO';

/**
 * @deprecated Will be removed in the next major version.
 */
const FileCodeO = createSvgIcon({
  as: FileCodeOSvg,
  ariaLabel: 'file code o',
  category: '',
  displayName: 'FileCodeO'
});

export default FileCodeO;
