// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FileOSvg from '@rsuite/icon-font/lib/legacy/FileO';

/**
 * @deprecated Will be removed in the next major version.
 */
const FileO = createSvgIcon({
  as: FileOSvg,
  ariaLabel: 'file o',
  category: '',
  displayName: 'FileO'
});

export default FileO;
