// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FileImageOSvg from '@rsuite/icon-font/lib/legacy/FileImageO';

/**
 * @deprecated Will be removed in the next major version.
 */
const FileImageO = createSvgIcon({
  as: FileImageOSvg,
  ariaLabel: 'file image o',
  category: '',
  displayName: 'FileImageO'
});

export default FileImageO;
