// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FileTextOSvg from '@rsuite/icon-font/lib/legacy/FileTextO';

/**
 * @deprecated Will be removed in the next major version.
 */
const FileTextO = createSvgIcon({
  as: FileTextOSvg,
  ariaLabel: 'file text o',
  category: '',
  displayName: 'FileTextO'
});

export default FileTextO;
