// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FileDownloadSvg from '@rsuite/icon-font/lib/legacy/FileDownload';

/**
 * @deprecated Will be removed in the next major version.
 */
const FileDownload = createSvgIcon({
  as: FileDownloadSvg,
  ariaLabel: 'file download',
  category: '',
  displayName: 'FileDownload'
});

export default FileDownload;
