// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FileExcelOSvg from '@rsuite/icon-font/lib/legacy/FileExcelO';

/**
 * @deprecated Will be removed in the next major version.
 */
const FileExcelO = createSvgIcon({
  as: FileExcelOSvg,
  ariaLabel: 'file excel o',
  category: '',
  displayName: 'FileExcelO'
});

export default FileExcelO;
