// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FileUploadSvg from '@rsuite/icon-font/lib/legacy/FileUpload';

/**
 * @deprecated Will be removed in the next major version.
 */
const FileUpload = createSvgIcon({
  as: FileUploadSvg,
  ariaLabel: 'file upload',
  category: '',
  displayName: 'FileUpload'
});

export default FileUpload;
