// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FileMovieOSvg from '@rsuite/icon-font/lib/legacy/FileMovieO';

/**
 * @deprecated Will be removed in the next major version.
 */
const FileMovieO = createSvgIcon({
  as: FileMovieOSvg,
  ariaLabel: 'file movie o',
  category: '',
  displayName: 'FileMovieO'
});

export default FileMovieO;
