// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FileAudioOSvg from '@rsuite/icon-font/lib/legacy/FileAudioO';

/**
 * @deprecated Will be removed in the next major version.
 */
const FileAudioO = createSvgIcon({
  as: FileAudioOSvg,
  ariaLabel: 'file audio o',
  category: '',
  displayName: 'FileAudioO'
});

export default FileAudioO;
