// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FilmSvg from '@rsuite/icon-font/lib/legacy/Film';

/**
 * @deprecated Will be removed in the next major version.
 */
const Film = createSvgIcon({
  as: FilmSvg,
  ariaLabel: 'film',
  category: '',
  displayName: 'Film'
});

export default Film;
