// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FireExtinguisherSvg from '@rsuite/icon-font/lib/legacy/FireExtinguisher';

/**
 * @deprecated Will be removed in the next major version.
 */
const FireExtinguisher = createSvgIcon({
  as: FireExtinguisherSvg,
  ariaLabel: 'fire extinguisher',
  category: '',
  displayName: 'FireExtinguisher'
});

export default FireExtinguisher;
