// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FirefoxSvg from '@rsuite/icon-font/lib/legacy/Firefox';

/**
 * @deprecated Will be removed in the next major version.
 */
const Firefox = createSvgIcon({
  as: FirefoxSvg,
  ariaLabel: 'firefox',
  category: '',
  displayName: 'Firefox'
});

export default Firefox;
