// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FirstOrderSvg from '@rsuite/icon-font/lib/legacy/FirstOrder';

/**
 * @deprecated Will be removed in the next major version.
 */
const FirstOrder = createSvgIcon({
  as: FirstOrderSvg,
  ariaLabel: 'first order',
  category: '',
  displayName: 'FirstOrder'
});

export default FirstOrder;
