// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FiveHundredPxSvg from '@rsuite/icon-font/lib/legacy/FiveHundredPx';

/**
 * @deprecated Will be removed in the next major version.
 */
const FiveHundredPx = createSvgIcon({
  as: FiveHundredPxSvg,
  ariaLabel: 'five hundred px',
  category: '',
  displayName: 'FiveHundredPx'
});

export default FiveHundredPx;
