// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FlagCheckeredSvg from '@rsuite/icon-font/lib/legacy/FlagCheckered';

/**
 * @deprecated Will be removed in the next major version.
 */
const FlagCheckered = createSvgIcon({
  as: FlagCheckeredSvg,
  ariaLabel: 'flag checkered',
  category: '',
  displayName: 'FlagCheckered'
});

export default FlagCheckered;
