// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FlaskSvg from '@rsuite/icon-font/lib/legacy/Flask';

/**
 * @deprecated Will be removed in the next major version.
 */
const Flask = createSvgIcon({
  as: FlaskSvg,
  ariaLabel: 'flask',
  category: '',
  displayName: 'Flask'
});

export default Flask;
