// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FlickrSvg from '@rsuite/icon-font/lib/legacy/Flickr';

/**
 * @deprecated Will be removed in the next major version.
 */
const Flickr = createSvgIcon({
  as: FlickrSvg,
  ariaLabel: 'flickr',
  category: '',
  displayName: 'Flickr'
});

export default Flickr;
