// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FlowSvg from '@rsuite/icon-font/lib/legacy/Flow';

/**
 * @deprecated Will be removed in the next major version.
 */
const Flow = createSvgIcon({
  as: FlowSvg,
  ariaLabel: 'flow',
  category: '',
  displayName: 'Flow'
});

export default Flow;
