// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FolderOSvg from '@rsuite/icon-font/lib/legacy/FolderO';

/**
 * @deprecated Will be removed in the next major version.
 */
const FolderO = createSvgIcon({
  as: FolderOSvg,
  ariaLabel: 'folder o',
  category: '',
  displayName: 'FolderO'
});

export default FolderO;
