// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FolderOpenOSvg from '@rsuite/icon-font/lib/legacy/FolderOpenO';

/**
 * @deprecated Will be removed in the next major version.
 */
const FolderOpenO = createSvgIcon({
  as: FolderOpenOSvg,
  ariaLabel: 'folder open o',
  category: '',
  displayName: 'FolderOpenO'
});

export default FolderOpenO;
