// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FontSvg from '@rsuite/icon-font/lib/legacy/Font';

/**
 * @deprecated Will be removed in the next major version.
 */
const Font = createSvgIcon({
  as: FontSvg,
  ariaLabel: 'font',
  category: '',
  displayName: 'Font'
});

export default Font;
