// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FortAwesomeSvg from '@rsuite/icon-font/lib/legacy/FortAwesome';

/**
 * @deprecated Will be removed in the next major version.
 */
const FortAwesome = createSvgIcon({
  as: FortAwesomeSvg,
  ariaLabel: 'fort awesome',
  category: '',
  displayName: 'FortAwesome'
});

export default FortAwesome;
