// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ForwardSvg from '@rsuite/icon-font/lib/legacy/Forward';

/**
 * @deprecated Will be removed in the next major version.
 */
const Forward = createSvgIcon({
  as: ForwardSvg,
  ariaLabel: 'forward',
  category: '',
  displayName: 'Forward'
});

export default Forward;
