// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FoursquareSvg from '@rsuite/icon-font/lib/legacy/Foursquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const Foursquare = createSvgIcon({
  as: FoursquareSvg,
  ariaLabel: 'foursquare',
  category: '',
  displayName: 'Foursquare'
});

export default Foursquare;
