// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FrownOSvg from '@rsuite/icon-font/lib/legacy/FrownO';

/**
 * @deprecated Will be removed in the next major version.
 */
const FrownO = createSvgIcon({
  as: FrownOSvg,
  ariaLabel: 'frown o',
  category: '',
  displayName: 'FrownO'
});

export default FrownO;
