// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import FutbolOSvg from '@rsuite/icon-font/lib/legacy/FutbolO';

/**
 * @deprecated Will be removed in the next major version.
 */
const FutbolO = createSvgIcon({
  as: FutbolOSvg,
  ariaLabel: 'futbol o',
  category: '',
  displayName: 'FutbolO'
});

export default FutbolO;
