// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GamepadSvg from '@rsuite/icon-font/lib/legacy/Gamepad';

/**
 * @deprecated Will be removed in the next major version.
 */
const Gamepad = createSvgIcon({
  as: GamepadSvg,
  ariaLabel: 'gamepad',
  category: '',
  displayName: 'Gamepad'
});

export default Gamepad;
