// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GavelSvg from '@rsuite/icon-font/lib/legacy/Gavel';

/**
 * @deprecated Will be removed in the next major version.
 */
const Gavel = createSvgIcon({
  as: GavelSvg,
  ariaLabel: 'gavel',
  category: '',
  displayName: 'Gavel'
});

export default Gavel;
