// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Gear2Svg from '@rsuite/icon-font/lib/legacy/Gear2';

/**
 * @deprecated Will be removed in the next major version.
 */
const Gear2 = createSvgIcon({
  as: Gear2Svg,
  ariaLabel: 'gear 2',
  category: '',
  displayName: 'Gear2'
});

export default Gear2;
