// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Gears2Svg from '@rsuite/icon-font/lib/legacy/Gears2';

/**
 * @deprecated Will be removed in the next major version.
 */
const Gears2 = createSvgIcon({
  as: Gears2Svg,
  ariaLabel: 'gears 2',
  category: '',
  displayName: 'Gears2'
});

export default Gears2;
