// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GearSvg from '@rsuite/icon-font/lib/legacy/Gear';

/**
 * @deprecated Will be removed in the next major version.
 */
const Gear = createSvgIcon({
  as: GearSvg,
  ariaLabel: 'gear',
  category: '',
  displayName: 'Gear'
});

export default Gear;
