// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GetPocketSvg from '@rsuite/icon-font/lib/legacy/GetPocket';

/**
 * @deprecated Will be removed in the next major version.
 */
const GetPocket = createSvgIcon({
  as: GetPocketSvg,
  ariaLabel: 'get pocket',
  category: '',
  displayName: 'GetPocket'
});

export default GetPocket;
