// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GgSvg from '@rsuite/icon-font/lib/legacy/Gg';

/**
 * @deprecated Will be removed in the next major version.
 */
const Gg = createSvgIcon({
  as: GgSvg,
  ariaLabel: 'gg',
  category: '',
  displayName: 'Gg'
});

export default Gg;
