// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GiftSvg from '@rsuite/icon-font/lib/legacy/Gift';

/**
 * @deprecated Will be removed in the next major version.
 */
const Gift = createSvgIcon({
  as: GiftSvg,
  ariaLabel: 'gift',
  category: '',
  displayName: 'Gift'
});

export default Gift;
