// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GitSvg from '@rsuite/icon-font/lib/legacy/Git';

/**
 * @deprecated Will be removed in the next major version.
 */
const Git = createSvgIcon({
  as: GitSvg,
  ariaLabel: 'git',
  category: '',
  displayName: 'Git'
});

export default Git;
