// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GithubSvg from '@rsuite/icon-font/lib/legacy/Github';

/**
 * @deprecated Will be removed in the next major version.
 */
const Github = createSvgIcon({
  as: GithubSvg,
  ariaLabel: 'github',
  category: '',
  displayName: 'Github'
});

export default Github;
