// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GitlabSvg from '@rsuite/icon-font/lib/legacy/Gitlab';

/**
 * @deprecated Will be removed in the next major version.
 */
const Gitlab = createSvgIcon({
  as: GitlabSvg,
  ariaLabel: 'gitlab',
  category: '',
  displayName: 'Gitlab'
});

export default Gitlab;
