// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GittipSvg from '@rsuite/icon-font/lib/legacy/Gittip';

/**
 * @deprecated Will be removed in the next major version.
 */
const Gittip = createSvgIcon({
  as: GittipSvg,
  ariaLabel: 'gittip',
  category: '',
  displayName: 'Gittip'
});

export default Gittip;
