// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GlassSvg from '@rsuite/icon-font/lib/legacy/Glass';

/**
 * @deprecated Will be removed in the next major version.
 */
const Glass = createSvgIcon({
  as: GlassSvg,
  ariaLabel: 'glass',
  category: '',
  displayName: 'Glass'
});

export default Glass;
