// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GlideGSvg from '@rsuite/icon-font/lib/legacy/GlideG';

/**
 * @deprecated Will be removed in the next major version.
 */
const GlideG = createSvgIcon({
  as: GlideGSvg,
  ariaLabel: 'glide g',
  category: '',
  displayName: 'GlideG'
});

export default GlideG;
