// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GlideSvg from '@rsuite/icon-font/lib/legacy/Glide';

/**
 * @deprecated Will be removed in the next major version.
 */
const Glide = createSvgIcon({
  as: GlideSvg,
  ariaLabel: 'glide',
  category: '',
  displayName: 'Glide'
});

export default Glide;
