// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GoodSvg from '@rsuite/icon-font/lib/legacy/Good';

/**
 * @deprecated Will be removed in the next major version.
 */
const Good = createSvgIcon({
  as: GoodSvg,
  ariaLabel: 'good',
  category: '',
  displayName: 'Good'
});

export default Good;
