// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GooglePlusSvg from '@rsuite/icon-font/lib/legacy/GooglePlus';

/**
 * @deprecated Will be removed in the next major version.
 */
const GooglePlus = createSvgIcon({
  as: GooglePlusSvg,
  ariaLabel: 'google plus',
  category: '',
  displayName: 'GooglePlus'
});

export default GooglePlus;
