// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GooglePlusCircleSvg from '@rsuite/icon-font/lib/legacy/GooglePlusCircle';

/**
 * @deprecated Will be removed in the next major version.
 */
const GooglePlusCircle = createSvgIcon({
  as: GooglePlusCircleSvg,
  ariaLabel: 'google plus circle',
  category: '',
  displayName: 'GooglePlusCircle'
});

export default GooglePlusCircle;
