// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GooglePlusSquareSvg from '@rsuite/icon-font/lib/legacy/GooglePlusSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const GooglePlusSquare = createSvgIcon({
  as: GooglePlusSquareSvg,
  ariaLabel: 'google plus square',
  category: '',
  displayName: 'GooglePlusSquare'
});

export default GooglePlusSquare;
