// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GoogleSvg from '@rsuite/icon-font/lib/legacy/Google';

/**
 * @deprecated Will be removed in the next major version.
 */
const Google = createSvgIcon({
  as: GoogleSvg,
  ariaLabel: 'google',
  category: '',
  displayName: 'Google'
});

export default Google;
