// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import GoogleWalletSvg from '@rsuite/icon-font/lib/legacy/GoogleWallet';

/**
 * @deprecated Will be removed in the next major version.
 */
const GoogleWallet = createSvgIcon({
  as: GoogleWalletSvg,
  ariaLabel: 'google wallet',
  category: '',
  displayName: 'GoogleWallet'
});

export default GoogleWallet;
