// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HandGrabOSvg from '@rsuite/icon-font/lib/legacy/HandGrabO';

/**
 * @deprecated Will be removed in the next major version.
 */
const HandGrabO = createSvgIcon({
  as: HandGrabOSvg,
  ariaLabel: 'hand grab o',
  category: '',
  displayName: 'HandGrabO'
});

export default HandGrabO;
