// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HandOLeftSvg from '@rsuite/icon-font/lib/legacy/HandOLeft';

/**
 * @deprecated Will be removed in the next major version.
 */
const HandOLeft = createSvgIcon({
  as: HandOLeftSvg,
  ariaLabel: 'hand o left',
  category: '',
  displayName: 'HandOLeft'
});

export default HandOLeft;
