// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HandORightSvg from '@rsuite/icon-font/lib/legacy/HandORight';

/**
 * @deprecated Will be removed in the next major version.
 */
const HandORight = createSvgIcon({
  as: HandORightSvg,
  ariaLabel: 'hand o right',
  category: '',
  displayName: 'HandORight'
});

export default HandORight;
