// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HandScissorsOSvg from '@rsuite/icon-font/lib/legacy/HandScissorsO';

/**
 * @deprecated Will be removed in the next major version.
 */
const HandScissorsO = createSvgIcon({
  as: HandScissorsOSvg,
  ariaLabel: 'hand scissors o',
  category: '',
  displayName: 'HandScissorsO'
});

export default HandScissorsO;
