// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HandPeaceOSvg from '@rsuite/icon-font/lib/legacy/HandPeaceO';

/**
 * @deprecated Will be removed in the next major version.
 */
const HandPeaceO = createSvgIcon({
  as: HandPeaceOSvg,
  ariaLabel: 'hand peace o',
  category: '',
  displayName: 'HandPeaceO'
});

export default HandPeaceO;
