// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HandSpockOSvg from '@rsuite/icon-font/lib/legacy/HandSpockO';

/**
 * @deprecated Will be removed in the next major version.
 */
const HandSpockO = createSvgIcon({
  as: HandSpockOSvg,
  ariaLabel: 'hand spock o',
  category: '',
  displayName: 'HandSpockO'
});

export default HandSpockO;
