// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HandODownSvg from '@rsuite/icon-font/lib/legacy/HandODown';

/**
 * @deprecated Will be removed in the next major version.
 */
const HandODown = createSvgIcon({
  as: HandODownSvg,
  ariaLabel: 'hand o down',
  category: '',
  displayName: 'HandODown'
});

export default HandODown;
