// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HandshakeOSvg from '@rsuite/icon-font/lib/legacy/HandshakeO';

/**
 * @deprecated Will be removed in the next major version.
 */
const HandshakeO = createSvgIcon({
  as: HandshakeOSvg,
  ariaLabel: 'handshake o',
  category: '',
  displayName: 'HandshakeO'
});

export default HandshakeO;
