// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HandStopOSvg from '@rsuite/icon-font/lib/legacy/HandStopO';

/**
 * @deprecated Will be removed in the next major version.
 */
const HandStopO = createSvgIcon({
  as: HandStopOSvg,
  ariaLabel: 'hand stop o',
  category: '',
  displayName: 'HandStopO'
});

export default HandStopO;
