// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HddOSvg from '@rsuite/icon-font/lib/legacy/HddO';

/**
 * @deprecated Will be removed in the next major version.
 */
const HddO = createSvgIcon({
  as: HddOSvg,
  ariaLabel: 'hdd o',
  category: '',
  displayName: 'HddO'
});

export default HddO;
