// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HeadphonesSvg from '@rsuite/icon-font/lib/legacy/Headphones';

/**
 * @deprecated Will be removed in the next major version.
 */
const Headphones = createSvgIcon({
  as: HeadphonesSvg,
  ariaLabel: 'headphones',
  category: '',
  displayName: 'Headphones'
});

export default Headphones;
