// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HeaderSvg from '@rsuite/icon-font/lib/legacy/Header';

/**
 * @deprecated Will be removed in the next major version.
 */
const Header = createSvgIcon({
  as: HeaderSvg,
  ariaLabel: 'header',
  category: '',
  displayName: 'Header'
});

export default Header;
