// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HeartSvg from '@rsuite/icon-font/lib/legacy/Heart';

/**
 * @deprecated Will be removed in the next major version.
 */
const Heart = createSvgIcon({
  as: HeartSvg,
  ariaLabel: 'heart',
  category: '',
  displayName: 'Heart'
});

export default Heart;
