// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HistorySvg from '@rsuite/icon-font/lib/legacy/History';

/**
 * @deprecated Will be removed in the next major version.
 */
const History = createSvgIcon({
  as: HistorySvg,
  ariaLabel: 'history',
  category: '',
  displayName: 'History'
});

export default History;
