// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HourglassSvg from '@rsuite/icon-font/lib/legacy/Hourglass';

/**
 * @deprecated Will be removed in the next major version.
 */
const Hourglass = createSvgIcon({
  as: HourglassSvg,
  ariaLabel: 'hourglass',
  category: '',
  displayName: 'Hourglass'
});

export default Hourglass;
