// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Hourglass2Svg from '@rsuite/icon-font/lib/legacy/Hourglass2';

/**
 * @deprecated Will be removed in the next major version.
 */
const Hourglass2 = createSvgIcon({
  as: Hourglass2Svg,
  ariaLabel: 'hourglass 2',
  category: '',
  displayName: 'Hourglass2'
});

export default Hourglass2;
