// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Hourglass3Svg from '@rsuite/icon-font/lib/legacy/Hourglass3';

/**
 * @deprecated Will be removed in the next major version.
 */
const Hourglass3 = createSvgIcon({
  as: Hourglass3Svg,
  ariaLabel: 'hourglass 3',
  category: '',
  displayName: 'Hourglass3'
});

export default Hourglass3;
