// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Hourglass1Svg from '@rsuite/icon-font/lib/legacy/Hourglass1';

/**
 * @deprecated Will be removed in the next major version.
 */
const Hourglass1 = createSvgIcon({
  as: Hourglass1Svg,
  ariaLabel: 'hourglass 1',
  category: '',
  displayName: 'Hourglass1'
});

export default Hourglass1;
