// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HouzzSvg from '@rsuite/icon-font/lib/legacy/Houzz';

/**
 * @deprecated Will be removed in the next major version.
 */
const Houzz = createSvgIcon({
  as: HouzzSvg,
  ariaLabel: 'houzz',
  category: '',
  displayName: 'Houzz'
});

export default Houzz;
