// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import HSquareSvg from '@rsuite/icon-font/lib/legacy/HSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const HSquare = createSvgIcon({
  as: HSquareSvg,
  ariaLabel: 'h square',
  category: '',
  displayName: 'HSquare'
});

export default HSquare;
