// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ICursorSvg from '@rsuite/icon-font/lib/legacy/ICursor';

/**
 * @deprecated Will be removed in the next major version.
 */
const ICursor = createSvgIcon({
  as: ICursorSvg,
  ariaLabel: 'i cursor',
  category: '',
  displayName: 'ICursor'
});

export default ICursor;
