// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import IdBadgeSvg from '@rsuite/icon-font/lib/legacy/IdBadge';

/**
 * @deprecated Will be removed in the next major version.
 */
const IdBadge = createSvgIcon({
  as: IdBadgeSvg,
  ariaLabel: 'id badge',
  category: '',
  displayName: 'IdBadge'
});

export default IdBadge;
