// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import IdCardSvg from '@rsuite/icon-font/lib/legacy/IdCard';

/**
 * @deprecated Will be removed in the next major version.
 */
const IdCard = createSvgIcon({
  as: IdCardSvg,
  ariaLabel: 'id card',
  category: '',
  displayName: 'IdCard'
});

export default IdCard;
