// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import IdMappingSvg from '@rsuite/icon-font/lib/legacy/IdMapping';

/**
 * @deprecated Will be removed in the next major version.
 */
const IdMapping = createSvgIcon({
  as: IdMappingSvg,
  ariaLabel: 'id mapping',
  category: '',
  displayName: 'IdMapping'
});

export default IdMapping;
