// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ImdbSvg from '@rsuite/icon-font/lib/legacy/Imdb';

/**
 * @deprecated Will be removed in the next major version.
 */
const Imdb = createSvgIcon({
  as: ImdbSvg,
  ariaLabel: 'imdb',
  category: '',
  displayName: 'Imdb'
});

export default Imdb;
