// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import IndentSvg from '@rsuite/icon-font/lib/legacy/Indent';

/**
 * @deprecated Will be removed in the next major version.
 */
const Indent = createSvgIcon({
  as: IndentSvg,
  ariaLabel: 'indent',
  category: '',
  displayName: 'Indent'
});

export default Indent;
