// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import IndustrySvg from '@rsuite/icon-font/lib/legacy/Industry';

/**
 * @deprecated Will be removed in the next major version.
 */
const Industry = createSvgIcon({
  as: IndustrySvg,
  ariaLabel: 'industry',
  category: '',
  displayName: 'Industry'
});

export default Industry;
