// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import InfoSvg from '@rsuite/icon-font/lib/legacy/Info';

/**
 * @deprecated Will be removed in the next major version.
 */
const Info = createSvgIcon({
  as: InfoSvg,
  ariaLabel: 'info',
  category: '',
  displayName: 'Info'
});

export default Info;
