// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import InrSvg from '@rsuite/icon-font/lib/legacy/Inr';

/**
 * @deprecated Will be removed in the next major version.
 */
const Inr = createSvgIcon({
  as: InrSvg,
  ariaLabel: 'inr',
  category: '',
  displayName: 'Inr'
});

export default Inr;
