// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import InstagramSvg from '@rsuite/icon-font/lib/legacy/Instagram';

/**
 * @deprecated Will be removed in the next major version.
 */
const Instagram = createSvgIcon({
  as: InstagramSvg,
  ariaLabel: 'instagram',
  category: '',
  displayName: 'Instagram'
});

export default Instagram;
