// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import IosSvg from '@rsuite/icon-font/lib/legacy/Ios';

/**
 * @deprecated Will be removed in the next major version.
 */
const Ios = createSvgIcon({
  as: IosSvg,
  ariaLabel: 'ios',
  category: '',
  displayName: 'Ios'
});

export default Ios;
