// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import IoxhostSvg from '@rsuite/icon-font/lib/legacy/Ioxhost';

/**
 * @deprecated Will be removed in the next major version.
 */
const Ioxhost = createSvgIcon({
  as: IoxhostSvg,
  ariaLabel: 'ioxhost',
  category: '',
  displayName: 'Ioxhost'
});

export default Ioxhost;
