// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import JoomlaSvg from '@rsuite/icon-font/lib/legacy/Joomla';

/**
 * @deprecated Will be removed in the next major version.
 */
const Joomla = createSvgIcon({
  as: JoomlaSvg,
  ariaLabel: 'joomla',
  category: '',
  displayName: 'Joomla'
});

export default Joomla;
