// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import KeyboardOSvg from '@rsuite/icon-font/lib/legacy/KeyboardO';

/**
 * @deprecated Will be removed in the next major version.
 */
const KeyboardO = createSvgIcon({
  as: KeyboardOSvg,
  ariaLabel: 'keyboard o',
  category: '',
  displayName: 'KeyboardO'
});

export default KeyboardO;
