// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import KrwSvg from '@rsuite/icon-font/lib/legacy/Krw';

/**
 * @deprecated Will be removed in the next major version.
 */
const Krw = createSvgIcon({
  as: KrwSvg,
  ariaLabel: 'krw',
  category: '',
  displayName: 'Krw'
});

export default Krw;
