// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LanguageSvg from '@rsuite/icon-font/lib/legacy/Language';

/**
 * @deprecated Will be removed in the next major version.
 */
const Language = createSvgIcon({
  as: LanguageSvg,
  ariaLabel: 'language',
  category: '',
  displayName: 'Language'
});

export default Language;
