// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LaptopSvg from '@rsuite/icon-font/lib/legacy/Laptop';

/**
 * @deprecated Will be removed in the next major version.
 */
const Laptop = createSvgIcon({
  as: LaptopSvg,
  ariaLabel: 'laptop',
  category: '',
  displayName: 'Laptop'
});

export default Laptop;
