// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LastfmSquareSvg from '@rsuite/icon-font/lib/legacy/LastfmSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const LastfmSquare = createSvgIcon({
  as: LastfmSquareSvg,
  ariaLabel: 'lastfm square',
  category: '',
  displayName: 'LastfmSquare'
});

export default LastfmSquare;
