// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LeafSvg from '@rsuite/icon-font/lib/legacy/Leaf';

/**
 * @deprecated Will be removed in the next major version.
 */
const Leaf = createSvgIcon({
  as: LeafSvg,
  ariaLabel: 'leaf',
  category: '',
  displayName: 'Leaf'
});

export default Leaf;
