// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LemonOSvg from '@rsuite/icon-font/lib/legacy/LemonO';

/**
 * @deprecated Will be removed in the next major version.
 */
const LemonO = createSvgIcon({
  as: LemonOSvg,
  ariaLabel: 'lemon o',
  category: '',
  displayName: 'LemonO'
});

export default LemonO;
