// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LevelUpSvg from '@rsuite/icon-font/lib/legacy/LevelUp';

/**
 * @deprecated Will be removed in the next major version.
 */
const LevelUp = createSvgIcon({
  as: LevelUpSvg,
  ariaLabel: 'level up',
  category: '',
  displayName: 'LevelUp'
});

export default LevelUp;
