// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LightbulbOSvg from '@rsuite/icon-font/lib/legacy/LightbulbO';

/**
 * @deprecated Will be removed in the next major version.
 */
const LightbulbO = createSvgIcon({
  as: LightbulbOSvg,
  ariaLabel: 'lightbulb o',
  category: '',
  displayName: 'LightbulbO'
});

export default LightbulbO;
