// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LineChartSvg from '@rsuite/icon-font/lib/legacy/LineChart';

/**
 * @deprecated Will be removed in the next major version.
 */
const LineChart = createSvgIcon({
  as: LineChartSvg,
  ariaLabel: 'line chart',
  category: '',
  displayName: 'LineChart'
});

export default LineChart;
