// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LinkedinSquareSvg from '@rsuite/icon-font/lib/legacy/LinkedinSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const LinkedinSquare = createSvgIcon({
  as: LinkedinSquareSvg,
  ariaLabel: 'linkedin square',
  category: '',
  displayName: 'LinkedinSquare'
});

export default LinkedinSquare;
