// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LinodeSvg from '@rsuite/icon-font/lib/legacy/Linode';

/**
 * @deprecated Will be removed in the next major version.
 */
const Linode = createSvgIcon({
  as: LinodeSvg,
  ariaLabel: 'linode',
  category: '',
  displayName: 'Linode'
});

export default Linode;
