// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ListOlSvg from '@rsuite/icon-font/lib/legacy/ListOl';

/**
 * @deprecated Will be removed in the next major version.
 */
const ListOl = createSvgIcon({
  as: ListOlSvg,
  ariaLabel: 'list ol',
  category: '',
  displayName: 'ListOl'
});

export default ListOl;
