// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LocationArrowSvg from '@rsuite/icon-font/lib/legacy/LocationArrow';

/**
 * @deprecated Will be removed in the next major version.
 */
const LocationArrow = createSvgIcon({
  as: LocationArrowSvg,
  ariaLabel: 'location arrow',
  category: '',
  displayName: 'LocationArrow'
});

export default LocationArrow;
