// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LogoDmpSvg from '@rsuite/icon-font/lib/legacy/LogoDmp';

/**
 * @deprecated Will be removed in the next major version.
 */
const LogoDmp = createSvgIcon({
  as: LogoDmpSvg,
  ariaLabel: 'logo dmp',
  category: '',
  displayName: 'LogoDmp'
});

export default LogoDmp;
