// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LogoAnalyticsSvg from '@rsuite/icon-font/lib/legacy/LogoAnalytics';

/**
 * @deprecated Will be removed in the next major version.
 */
const LogoAnalytics = createSvgIcon({
  as: LogoAnalyticsSvg,
  ariaLabel: 'logo analytics',
  category: '',
  displayName: 'LogoAnalytics'
});

export default LogoAnalytics;
