// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LogoAdsSvg from '@rsuite/icon-font/lib/legacy/LogoAds';

/**
 * @deprecated Will be removed in the next major version.
 */
const LogoAds = createSvgIcon({
  as: LogoAdsSvg,
  ariaLabel: 'logo ads',
  category: '',
  displayName: 'LogoAds'
});

export default LogoAds;
