// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LongArrowUpSvg from '@rsuite/icon-font/lib/legacy/LongArrowUp';

/**
 * @deprecated Will be removed in the next major version.
 */
const LongArrowUp = createSvgIcon({
  as: LongArrowUpSvg,
  ariaLabel: 'long arrow up',
  category: '',
  displayName: 'LongArrowUp'
});

export default LongArrowUp;
