// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LongArrowLeftSvg from '@rsuite/icon-font/lib/legacy/LongArrowLeft';

/**
 * @deprecated Will be removed in the next major version.
 */
const LongArrowLeft = createSvgIcon({
  as: LongArrowLeftSvg,
  ariaLabel: 'long arrow left',
  category: '',
  displayName: 'LongArrowLeft'
});

export default LongArrowLeft;
