// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LongArrowDownSvg from '@rsuite/icon-font/lib/legacy/LongArrowDown';

/**
 * @deprecated Will be removed in the next major version.
 */
const LongArrowDown = createSvgIcon({
  as: LongArrowDownSvg,
  ariaLabel: 'long arrow down',
  category: '',
  displayName: 'LongArrowDown'
});

export default LongArrowDown;
