// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LongArrowRightSvg from '@rsuite/icon-font/lib/legacy/LongArrowRight';

/**
 * @deprecated Will be removed in the next major version.
 */
const LongArrowRight = createSvgIcon({
  as: LongArrowRightSvg,
  ariaLabel: 'long arrow right',
  category: '',
  displayName: 'LongArrowRight'
});

export default LongArrowRight;
