// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import LowVisionSvg from '@rsuite/icon-font/lib/legacy/LowVision';

/**
 * @deprecated Will be removed in the next major version.
 */
const LowVision = createSvgIcon({
  as: LowVisionSvg,
  ariaLabel: 'low vision',
  category: '',
  displayName: 'LowVision'
});

export default LowVision;
