// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MagnetSvg from '@rsuite/icon-font/lib/legacy/Magnet';

/**
 * @deprecated Will be removed in the next major version.
 */
const Magnet = createSvgIcon({
  as: MagnetSvg,
  ariaLabel: 'magnet',
  category: '',
  displayName: 'Magnet'
});

export default Magnet;
