// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MaleSvg from '@rsuite/icon-font/lib/legacy/Male';

/**
 * @deprecated Will be removed in the next major version.
 */
const Male = createSvgIcon({
  as: MaleSvg,
  ariaLabel: 'male',
  category: '',
  displayName: 'Male'
});

export default Male;
