// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MapPinSvg from '@rsuite/icon-font/lib/legacy/MapPin';

/**
 * @deprecated Will be removed in the next major version.
 */
const MapPin = createSvgIcon({
  as: MapPinSvg,
  ariaLabel: 'map pin',
  category: '',
  displayName: 'MapPin'
});

export default MapPin;
