// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MarsStrokeSvg from '@rsuite/icon-font/lib/legacy/MarsStroke';

/**
 * @deprecated Will be removed in the next major version.
 */
const MarsStroke = createSvgIcon({
  as: MarsStrokeSvg,
  ariaLabel: 'mars stroke',
  category: '',
  displayName: 'MarsStroke'
});

export default MarsStroke;
