// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MarsSvg from '@rsuite/icon-font/lib/legacy/Mars';

/**
 * @deprecated Will be removed in the next major version.
 */
const Mars = createSvgIcon({
  as: MarsSvg,
  ariaLabel: 'mars',
  category: '',
  displayName: 'Mars'
});

export default Mars;
