// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MarsStrokeHSvg from '@rsuite/icon-font/lib/legacy/MarsStrokeH';

/**
 * @deprecated Will be removed in the next major version.
 */
const MarsStrokeH = createSvgIcon({
  as: MarsStrokeHSvg,
  ariaLabel: 'mars stroke h',
  category: '',
  displayName: 'MarsStrokeH'
});

export default MarsStrokeH;
