// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MeanpathSvg from '@rsuite/icon-font/lib/legacy/Meanpath';

/**
 * @deprecated Will be removed in the next major version.
 */
const Meanpath = createSvgIcon({
  as: MeanpathSvg,
  ariaLabel: 'meanpath',
  category: '',
  displayName: 'Meanpath'
});

export default Meanpath;
