// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MeetupSvg from '@rsuite/icon-font/lib/legacy/Meetup';

/**
 * @deprecated Will be removed in the next major version.
 */
const Meetup = createSvgIcon({
  as: MeetupSvg,
  ariaLabel: 'meetup',
  category: '',
  displayName: 'Meetup'
});

export default Meetup;
