// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MercurySvg from '@rsuite/icon-font/lib/legacy/Mercury';

/**
 * @deprecated Will be removed in the next major version.
 */
const Mercury = createSvgIcon({
  as: MercurySvg,
  ariaLabel: 'mercury',
  category: '',
  displayName: 'Mercury'
});

export default Mercury;
