// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MicrophoneSvg from '@rsuite/icon-font/lib/legacy/Microphone';

/**
 * @deprecated Will be removed in the next major version.
 */
const Microphone = createSvgIcon({
  as: MicrophoneSvg,
  ariaLabel: 'microphone',
  category: '',
  displayName: 'Microphone'
});

export default Microphone;
