// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MicrochipSvg from '@rsuite/icon-font/lib/legacy/Microchip';

/**
 * @deprecated Will be removed in the next major version.
 */
const Microchip = createSvgIcon({
  as: MicrochipSvg,
  ariaLabel: 'microchip',
  category: '',
  displayName: 'Microchip'
});

export default Microchip;
