// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MinusSquareOSvg from '@rsuite/icon-font/lib/legacy/MinusSquareO';

/**
 * @deprecated Will be removed in the next major version.
 */
const MinusSquareO = createSvgIcon({
  as: MinusSquareOSvg,
  ariaLabel: 'minus square o',
  category: '',
  displayName: 'MinusSquareO'
});

export default MinusSquareO;
