// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MinusSvg from '@rsuite/icon-font/lib/legacy/Minus';

/**
 * @deprecated Will be removed in the next major version.
 */
const Minus = createSvgIcon({
  as: MinusSvg,
  ariaLabel: 'minus',
  category: '',
  displayName: 'Minus'
});

export default Minus;
