// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MinusSquareSvg from '@rsuite/icon-font/lib/legacy/MinusSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const MinusSquare = createSvgIcon({
  as: MinusSquareSvg,
  ariaLabel: 'minus square',
  category: '',
  displayName: 'MinusSquare'
});

export default MinusSquare;
