// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MixcloudSvg from '@rsuite/icon-font/lib/legacy/Mixcloud';

/**
 * @deprecated Will be removed in the next major version.
 */
const Mixcloud = createSvgIcon({
  as: MixcloudSvg,
  ariaLabel: 'mixcloud',
  category: '',
  displayName: 'Mixcloud'
});

export default Mixcloud;
