// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MobileSvg from '@rsuite/icon-font/lib/legacy/Mobile';

/**
 * @deprecated Will be removed in the next major version.
 */
const Mobile = createSvgIcon({
  as: MobileSvg,
  ariaLabel: 'mobile',
  category: '',
  displayName: 'Mobile'
});

export default Mobile;
