// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ModxSvg from '@rsuite/icon-font/lib/legacy/Modx';

/**
 * @deprecated Will be removed in the next major version.
 */
const Modx = createSvgIcon({
  as: ModxSvg,
  ariaLabel: 'modx',
  category: '',
  displayName: 'Modx'
});

export default Modx;
