// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MoneySvg from '@rsuite/icon-font/lib/legacy/Money';

/**
 * @deprecated Will be removed in the next major version.
 */
const Money = createSvgIcon({
  as: MoneySvg,
  ariaLabel: 'money',
  category: '',
  displayName: 'Money'
});

export default Money;
