// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MoonOSvg from '@rsuite/icon-font/lib/legacy/MoonO';

/**
 * @deprecated Will be removed in the next major version.
 */
const MoonO = createSvgIcon({
  as: MoonOSvg,
  ariaLabel: 'moon o',
  category: '',
  displayName: 'MoonO'
});

export default MoonO;
