// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MoreSvg from '@rsuite/icon-font/lib/legacy/More';

/**
 * @deprecated Will be removed in the next major version.
 */
const More = createSvgIcon({
  as: MoreSvg,
  ariaLabel: 'more',
  category: '',
  displayName: 'More'
});

export default More;
