// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MotorcycleSvg from '@rsuite/icon-font/lib/legacy/Motorcycle';

/**
 * @deprecated Will be removed in the next major version.
 */
const Motorcycle = createSvgIcon({
  as: MotorcycleSvg,
  ariaLabel: 'motorcycle',
  category: '',
  displayName: 'Motorcycle'
});

export default Motorcycle;
