// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MultipleLinesChartSvg from '@rsuite/icon-font/lib/legacy/MultipleLinesChart';

/**
 * @deprecated Will be removed in the next major version.
 */
const MultipleLinesChart = createSvgIcon({
  as: MultipleLinesChartSvg,
  ariaLabel: 'multiple lines chart',
  category: '',
  displayName: 'MultipleLinesChart'
});

export default MultipleLinesChart;
