// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import MusicSvg from '@rsuite/icon-font/lib/legacy/Music';

/**
 * @deprecated Will be removed in the next major version.
 */
const Music = createSvgIcon({
  as: MusicSvg,
  ariaLabel: 'music',
  category: '',
  displayName: 'Music'
});

export default Music;
