// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import NeuterSvg from '@rsuite/icon-font/lib/legacy/Neuter';

/**
 * @deprecated Will be removed in the next major version.
 */
const Neuter = createSvgIcon({
  as: NeuterSvg,
  ariaLabel: 'neuter',
  category: '',
  displayName: 'Neuter'
});

export default Neuter;
