// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import NewspaperOSvg from '@rsuite/icon-font/lib/legacy/NewspaperO';

/**
 * @deprecated Will be removed in the next major version.
 */
const NewspaperO = createSvgIcon({
  as: NewspaperOSvg,
  ariaLabel: 'newspaper o',
  category: '',
  displayName: 'NewspaperO'
});

export default NewspaperO;
