// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ObjectGroupSvg from '@rsuite/icon-font/lib/legacy/ObjectGroup';

/**
 * @deprecated Will be removed in the next major version.
 */
const ObjectGroup = createSvgIcon({
  as: ObjectGroupSvg,
  ariaLabel: 'object group',
  category: '',
  displayName: 'ObjectGroup'
});

export default ObjectGroup;
