// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ObjectUngroupSvg from '@rsuite/icon-font/lib/legacy/ObjectUngroup';

/**
 * @deprecated Will be removed in the next major version.
 */
const ObjectUngroup = createSvgIcon({
  as: ObjectUngroupSvg,
  ariaLabel: 'object ungroup',
  category: '',
  displayName: 'ObjectUngroup'
});

export default ObjectUngroup;
