// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import OdnoklassnikiSquareSvg from '@rsuite/icon-font/lib/legacy/OdnoklassnikiSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const OdnoklassnikiSquare = createSvgIcon({
  as: OdnoklassnikiSquareSvg,
  ariaLabel: 'odnoklassniki square',
  category: '',
  displayName: 'OdnoklassnikiSquare'
});

export default OdnoklassnikiSquare;
