// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import OdnoklassnikiSvg from '@rsuite/icon-font/lib/legacy/Odnoklassniki';

/**
 * @deprecated Will be removed in the next major version.
 */
const Odnoklassniki = createSvgIcon({
  as: OdnoklassnikiSvg,
  ariaLabel: 'odnoklassniki',
  category: '',
  displayName: 'Odnoklassniki'
});

export default Odnoklassniki;
