// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import OkCircleSvg from '@rsuite/icon-font/lib/legacy/OkCircle';

/**
 * @deprecated Will be removed in the next major version.
 */
const OkCircle = createSvgIcon({
  as: OkCircleSvg,
  ariaLabel: 'ok circle',
  category: '',
  displayName: 'OkCircle'
});

export default OkCircle;
