// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import OpenidSvg from '@rsuite/icon-font/lib/legacy/Openid';

/**
 * @deprecated Will be removed in the next major version.
 */
const Openid = createSvgIcon({
  as: OpenidSvg,
  ariaLabel: 'openid',
  category: '',
  displayName: 'Openid'
});

export default Openid;
