// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import OperaSvg from '@rsuite/icon-font/lib/legacy/Opera';

/**
 * @deprecated Will be removed in the next major version.
 */
const Opera = createSvgIcon({
  as: OperaSvg,
  ariaLabel: 'opera',
  category: '',
  displayName: 'Opera'
});

export default Opera;
