// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import OptinMonsterSvg from '@rsuite/icon-font/lib/legacy/OptinMonster';

/**
 * @deprecated Will be removed in the next major version.
 */
const OptinMonster = createSvgIcon({
  as: OptinMonsterSvg,
  ariaLabel: 'optin monster',
  category: '',
  displayName: 'OptinMonster'
});

export default OptinMonster;
