// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PagelinesSvg from '@rsuite/icon-font/lib/legacy/Pagelines';

/**
 * @deprecated Will be removed in the next major version.
 */
const Pagelines = createSvgIcon({
  as: PagelinesSvg,
  ariaLabel: 'pagelines',
  category: '',
  displayName: 'Pagelines'
});

export default Pagelines;
