// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PagePreviousSvg from '@rsuite/icon-font/lib/legacy/PagePrevious';

/**
 * @deprecated Will be removed in the next major version.
 */
const PagePrevious = createSvgIcon({
  as: PagePreviousSvg,
  ariaLabel: 'page previous',
  category: '',
  displayName: 'PagePrevious'
});

export default PagePrevious;
