// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PageTopSvg from '@rsuite/icon-font/lib/legacy/PageTop';

/**
 * @deprecated Will be removed in the next major version.
 */
const PageTop = createSvgIcon({
  as: PageTopSvg,
  ariaLabel: 'page top',
  category: '',
  displayName: 'PageTop'
});

export default PageTop;
