// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ParagraphSvg from '@rsuite/icon-font/lib/legacy/Paragraph';

/**
 * @deprecated Will be removed in the next major version.
 */
const Paragraph = createSvgIcon({
  as: ParagraphSvg,
  ariaLabel: 'paragraph',
  category: '',
  displayName: 'Paragraph'
});

export default Paragraph;
