// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PasteSvg from '@rsuite/icon-font/lib/legacy/Paste';

/**
 * @deprecated Will be removed in the next major version.
 */
const Paste = createSvgIcon({
  as: PasteSvg,
  ariaLabel: 'paste',
  category: '',
  displayName: 'Paste'
});

export default Paste;
