// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PauseSvg from '@rsuite/icon-font/lib/legacy/Pause';

/**
 * @deprecated Will be removed in the next major version.
 */
const Pause = createSvgIcon({
  as: PauseSvg,
  ariaLabel: 'pause',
  category: '',
  displayName: 'Pause'
});

export default Pause;
