// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PawSvg from '@rsuite/icon-font/lib/legacy/Paw';

/**
 * @deprecated Will be removed in the next major version.
 */
const Paw = createSvgIcon({
  as: PawSvg,
  ariaLabel: 'paw',
  category: '',
  displayName: 'Paw'
});

export default Paw;
