// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PcSvg from '@rsuite/icon-font/lib/legacy/Pc';

/**
 * @deprecated Will be removed in the next major version.
 */
const Pc = createSvgIcon({
  as: PcSvg,
  ariaLabel: 'pc',
  category: '',
  displayName: 'Pc'
});

export default Pc;
