// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PencilSquareSvg from '@rsuite/icon-font/lib/legacy/PencilSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const PencilSquare = createSvgIcon({
  as: PencilSquareSvg,
  ariaLabel: 'pencil square',
  category: '',
  displayName: 'PencilSquare'
});

export default PencilSquare;
