// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PeoplesMapSvg from '@rsuite/icon-font/lib/legacy/PeoplesMap';

/**
 * @deprecated Will be removed in the next major version.
 */
const PeoplesMap = createSvgIcon({
  as: PeoplesMapSvg,
  ariaLabel: 'peoples map',
  category: '',
  displayName: 'PeoplesMap'
});

export default PeoplesMap;
