// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PeoplesSvg from '@rsuite/icon-font/lib/legacy/Peoples';

/**
 * @deprecated Will be removed in the next major version.
 */
const Peoples = createSvgIcon({
  as: PeoplesSvg,
  ariaLabel: 'peoples',
  category: '',
  displayName: 'Peoples'
});

export default Peoples;
