// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PhoneSquareSvg from '@rsuite/icon-font/lib/legacy/PhoneSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const PhoneSquare = createSvgIcon({
  as: PhoneSquareSvg,
  ariaLabel: 'phone square',
  category: '',
  displayName: 'PhoneSquare'
});

export default PhoneSquare;
