// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PiedPiperAltSvg from '@rsuite/icon-font/lib/legacy/PiedPiperAlt';

/**
 * @deprecated Will be removed in the next major version.
 */
const PiedPiperAlt = createSvgIcon({
  as: PiedPiperAltSvg,
  ariaLabel: 'pied piper alt',
  category: '',
  displayName: 'PiedPiperAlt'
});

export default PiedPiperAlt;
