// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PiedPiperPpSvg from '@rsuite/icon-font/lib/legacy/PiedPiperPp';

/**
 * @deprecated Will be removed in the next major version.
 */
const PiedPiperPp = createSvgIcon({
  as: PiedPiperPpSvg,
  ariaLabel: 'pied piper pp',
  category: '',
  displayName: 'PiedPiperPp'
});

export default PiedPiperPp;
