// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PinterestSquareSvg from '@rsuite/icon-font/lib/legacy/PinterestSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const PinterestSquare = createSvgIcon({
  as: PinterestSquareSvg,
  ariaLabel: 'pinterest square',
  category: '',
  displayName: 'PinterestSquare'
});

export default PinterestSquare;
