// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PlayCircleOSvg from '@rsuite/icon-font/lib/legacy/PlayCircleO';

/**
 * @deprecated Will be removed in the next major version.
 */
const PlayCircleO = createSvgIcon({
  as: PlayCircleOSvg,
  ariaLabel: 'play circle o',
  category: '',
  displayName: 'PlayCircleO'
});

export default PlayCircleO;
