// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Play2Svg from '@rsuite/icon-font/lib/legacy/Play2';

/**
 * @deprecated Will be removed in the next major version.
 */
const Play2 = createSvgIcon({
  as: Play2Svg,
  ariaLabel: 'play 2',
  category: '',
  displayName: 'Play2'
});

export default Play2;
