// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PlayCircleSvg from '@rsuite/icon-font/lib/legacy/PlayCircle';

/**
 * @deprecated Will be removed in the next major version.
 */
const PlayCircle = createSvgIcon({
  as: PlayCircleSvg,
  ariaLabel: 'play circle',
  category: '',
  displayName: 'PlayCircle'
});

export default PlayCircle;
