// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PlusCircleSvg from '@rsuite/icon-font/lib/legacy/PlusCircle';

/**
 * @deprecated Will be removed in the next major version.
 */
const PlusCircle = createSvgIcon({
  as: PlusCircleSvg,
  ariaLabel: 'plus circle',
  category: '',
  displayName: 'PlusCircle'
});

export default PlusCircle;
