// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PlusSquareOSvg from '@rsuite/icon-font/lib/legacy/PlusSquareO';

/**
 * @deprecated Will be removed in the next major version.
 */
const PlusSquareO = createSvgIcon({
  as: PlusSquareOSvg,
  ariaLabel: 'plus square o',
  category: '',
  displayName: 'PlusSquareO'
});

export default PlusSquareO;
