// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PlusSquareSvg from '@rsuite/icon-font/lib/legacy/PlusSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const PlusSquare = createSvgIcon({
  as: PlusSquareSvg,
  ariaLabel: 'plus square',
  category: '',
  displayName: 'PlusSquare'
});

export default PlusSquare;
