// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PrintSvg from '@rsuite/icon-font/lib/legacy/Print';

/**
 * @deprecated Will be removed in the next major version.
 */
const Print = createSvgIcon({
  as: PrintSvg,
  ariaLabel: 'print',
  category: '',
  displayName: 'Print'
});

export default Print;
