// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ProductHuntSvg from '@rsuite/icon-font/lib/legacy/ProductHunt';

/**
 * @deprecated Will be removed in the next major version.
 */
const ProductHunt = createSvgIcon({
  as: ProductHuntSvg,
  ariaLabel: 'product hunt',
  category: '',
  displayName: 'ProductHunt'
});

export default ProductHunt;
