// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ProjectSvg from '@rsuite/icon-font/lib/legacy/Project';

/**
 * @deprecated Will be removed in the next major version.
 */
const Project = createSvgIcon({
  as: ProjectSvg,
  ariaLabel: 'project',
  category: '',
  displayName: 'Project'
});

export default Project;
