// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import PublicOpinionSvg from '@rsuite/icon-font/lib/legacy/PublicOpinion';

/**
 * @deprecated Will be removed in the next major version.
 */
const PublicOpinion = createSvgIcon({
  as: PublicOpinionSvg,
  ariaLabel: 'public opinion',
  category: '',
  displayName: 'PublicOpinion'
});

export default PublicOpinion;
