// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import QqSvg from '@rsuite/icon-font/lib/legacy/Qq';

/**
 * @deprecated Will be removed in the next major version.
 */
const Qq = createSvgIcon({
  as: QqSvg,
  ariaLabel: 'qq',
  category: '',
  displayName: 'Qq'
});

export default Qq;
