// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import QuestionCircle2Svg from '@rsuite/icon-font/lib/legacy/QuestionCircle2';

/**
 * @deprecated Will be removed in the next major version.
 */
const QuestionCircle2 = createSvgIcon({
  as: QuestionCircle2Svg,
  ariaLabel: 'question circle 2',
  category: '',
  displayName: 'QuestionCircle2'
});

export default QuestionCircle2;
