// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import QuestionCircleSvg from '@rsuite/icon-font/lib/legacy/QuestionCircle';

/**
 * @deprecated Will be removed in the next major version.
 */
const QuestionCircle = createSvgIcon({
  as: QuestionCircleSvg,
  ariaLabel: 'question circle',
  category: '',
  displayName: 'QuestionCircle'
});

export default QuestionCircle;
