// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import QuoraSvg from '@rsuite/icon-font/lib/legacy/Quora';

/**
 * @deprecated Will be removed in the next major version.
 */
const Quora = createSvgIcon({
  as: QuoraSvg,
  ariaLabel: 'quora',
  category: '',
  displayName: 'Quora'
});

export default Quora;
