// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import QuoteRightSvg from '@rsuite/icon-font/lib/legacy/QuoteRight';

/**
 * @deprecated Will be removed in the next major version.
 */
const QuoteRight = createSvgIcon({
  as: QuoteRightSvg,
  ariaLabel: 'quote right',
  category: '',
  displayName: 'QuoteRight'
});

export default QuoteRight;
