// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RandomSvg from '@rsuite/icon-font/lib/legacy/Random';

/**
 * @deprecated Will be removed in the next major version.
 */
const Random = createSvgIcon({
  as: RandomSvg,
  ariaLabel: 'random',
  category: '',
  displayName: 'Random'
});

export default Random;
