// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RateSvg from '@rsuite/icon-font/lib/legacy/Rate';

/**
 * @deprecated Will be removed in the next major version.
 */
const Rate = createSvgIcon({
  as: RateSvg,
  ariaLabel: 'rate',
  category: '',
  displayName: 'Rate'
});

export default Rate;
