// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RavelrySvg from '@rsuite/icon-font/lib/legacy/Ravelry';

/**
 * @deprecated Will be removed in the next major version.
 */
const Ravelry = createSvgIcon({
  as: RavelrySvg,
  ariaLabel: 'ravelry',
  category: '',
  displayName: 'Ravelry'
});

export default Ravelry;
