// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RealtimeSvg from '@rsuite/icon-font/lib/legacy/Realtime';

/**
 * @deprecated Will be removed in the next major version.
 */
const Realtime = createSvgIcon({
  as: RealtimeSvg,
  ariaLabel: 'realtime',
  category: '',
  displayName: 'Realtime'
});

export default Realtime;
