// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RedditSvg from '@rsuite/icon-font/lib/legacy/Reddit';

/**
 * @deprecated Will be removed in the next major version.
 */
const Reddit = createSvgIcon({
  as: RedditSvg,
  ariaLabel: 'reddit',
  category: '',
  displayName: 'Reddit'
});

export default Reddit;
