// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Refresh2Svg from '@rsuite/icon-font/lib/legacy/Refresh2';

/**
 * @deprecated Will be removed in the next major version.
 */
const Refresh2 = createSvgIcon({
  as: Refresh2Svg,
  ariaLabel: 'refresh 2',
  category: '',
  displayName: 'Refresh2'
});

export default Refresh2;
