// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RefreshSvg from '@rsuite/icon-font/lib/legacy/Refresh';

/**
 * @deprecated Will be removed in the next major version.
 */
const Refresh = createSvgIcon({
  as: RefreshSvg,
  ariaLabel: 'refresh',
  category: '',
  displayName: 'Refresh'
});

export default Refresh;
