// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RegisteredSvg from '@rsuite/icon-font/lib/legacy/Registered';

/**
 * @deprecated Will be removed in the next major version.
 */
const Registered = createSvgIcon({
  as: RegisteredSvg,
  ariaLabel: 'registered',
  category: '',
  displayName: 'Registered'
});

export default Registered;
