// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RelatedMapSvg from '@rsuite/icon-font/lib/legacy/RelatedMap';

/**
 * @deprecated Will be removed in the next major version.
 */
const RelatedMap = createSvgIcon({
  as: RelatedMapSvg,
  ariaLabel: 'related map',
  category: '',
  displayName: 'RelatedMap'
});

export default RelatedMap;
