// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RemindSvg from '@rsuite/icon-font/lib/legacy/Remind';

/**
 * @deprecated Will be removed in the next major version.
 */
const Remind = createSvgIcon({
  as: RemindSvg,
  ariaLabel: 'remind',
  category: '',
  displayName: 'Remind'
});

export default Remind;
