// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RenrenSvg from '@rsuite/icon-font/lib/legacy/Renren';

/**
 * @deprecated Will be removed in the next major version.
 */
const Renren = createSvgIcon({
  as: RenrenSvg,
  ariaLabel: 'renren',
  category: '',
  displayName: 'Renren'
});

export default Renren;
