// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RepeatSvg from '@rsuite/icon-font/lib/legacy/Repeat';

/**
 * @deprecated Will be removed in the next major version.
 */
const Repeat = createSvgIcon({
  as: RepeatSvg,
  ariaLabel: 'repeat',
  category: '',
  displayName: 'Repeat'
});

export default Repeat;
