// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ReplySvg from '@rsuite/icon-font/lib/legacy/Reply';

/**
 * @deprecated Will be removed in the next major version.
 */
const Reply = createSvgIcon({
  as: ReplySvg,
  ariaLabel: 'reply',
  category: '',
  displayName: 'Reply'
});

export default Reply;
