// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RetentionSvg from '@rsuite/icon-font/lib/legacy/Retention';

/**
 * @deprecated Will be removed in the next major version.
 */
const Retention = createSvgIcon({
  as: RetentionSvg,
  ariaLabel: 'retention',
  category: '',
  displayName: 'Retention'
});

export default Retention;
