// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RetweetSvg from '@rsuite/icon-font/lib/legacy/Retweet';

/**
 * @deprecated Will be removed in the next major version.
 */
const Retweet = createSvgIcon({
  as: RetweetSvg,
  ariaLabel: 'retweet',
  category: '',
  displayName: 'Retweet'
});

export default Retweet;
