// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RightSvg from '@rsuite/icon-font/lib/legacy/Right';

/**
 * @deprecated Will be removed in the next major version.
 */
const Right = createSvgIcon({
  as: RightSvg,
  ariaLabel: 'right',
  category: '',
  displayName: 'Right'
});

export default Right;
