// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RssSvg from '@rsuite/icon-font/lib/legacy/Rss';

/**
 * @deprecated Will be removed in the next major version.
 */
const Rss = createSvgIcon({
  as: RssSvg,
  ariaLabel: 'rss',
  category: '',
  displayName: 'Rss'
});

export default Rss;
