// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import RssSquareSvg from '@rsuite/icon-font/lib/legacy/RssSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const RssSquare = createSvgIcon({
  as: RssSquareSvg,
  ariaLabel: 'rss square',
  category: '',
  displayName: 'RssSquare'
});

export default RssSquare;
