// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import S15Svg from '@rsuite/icon-font/lib/legacy/S15';

/**
 * @deprecated Will be removed in the next major version.
 */
const S15 = createSvgIcon({
  as: S15Svg,
  ariaLabel: 's 15',
  category: '',
  displayName: 'S15'
});

export default S15;
