// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SafariSvg from '@rsuite/icon-font/lib/legacy/Safari';

/**
 * @deprecated Will be removed in the next major version.
 */
const Safari = createSvgIcon({
  as: SafariSvg,
  ariaLabel: 'safari',
  category: '',
  displayName: 'Safari'
});

export default Safari;
