// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ScribdSvg from '@rsuite/icon-font/lib/legacy/Scribd';

/**
 * @deprecated Will be removed in the next major version.
 */
const Scribd = createSvgIcon({
  as: ScribdSvg,
  ariaLabel: 'scribd',
  category: '',
  displayName: 'Scribd'
});

export default Scribd;
