// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SearchPeoplesSvg from '@rsuite/icon-font/lib/legacy/SearchPeoples';

/**
 * @deprecated Will be removed in the next major version.
 */
const SearchPeoples = createSvgIcon({
  as: SearchPeoplesSvg,
  ariaLabel: 'search peoples',
  category: '',
  displayName: 'SearchPeoples'
});

export default SearchPeoples;
