// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SearchPlusSvg from '@rsuite/icon-font/lib/legacy/SearchPlus';

/**
 * @deprecated Will be removed in the next major version.
 */
const SearchPlus = createSvgIcon({
  as: SearchPlusSvg,
  ariaLabel: 'search plus',
  category: '',
  displayName: 'SearchPlus'
});

export default SearchPlus;
