// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SearchMinusSvg from '@rsuite/icon-font/lib/legacy/SearchMinus';

/**
 * @deprecated Will be removed in the next major version.
 */
const SearchMinus = createSvgIcon({
  as: SearchMinusSvg,
  ariaLabel: 'search minus',
  category: '',
  displayName: 'SearchMinus'
});

export default SearchMinus;
