// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SearchSvg from '@rsuite/icon-font/lib/legacy/Search';

/**
 * @deprecated Will be removed in the next major version.
 */
const Search = createSvgIcon({
  as: SearchSvg,
  ariaLabel: 'search',
  category: '',
  displayName: 'Search'
});

export default Search;
