// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SellsySvg from '@rsuite/icon-font/lib/legacy/Sellsy';

/**
 * @deprecated Will be removed in the next major version.
 */
const Sellsy = createSvgIcon({
  as: SellsySvg,
  ariaLabel: 'sellsy',
  category: '',
  displayName: 'Sellsy'
});

export default Sellsy;
