// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SequenceUpSvg from '@rsuite/icon-font/lib/legacy/SequenceUp';

/**
 * @deprecated Will be removed in the next major version.
 */
const SequenceUp = createSvgIcon({
  as: SequenceUpSvg,
  ariaLabel: 'sequence up',
  category: '',
  displayName: 'SequenceUp'
});

export default SequenceUp;
