// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SettingSvg from '@rsuite/icon-font/lib/legacy/Setting';

/**
 * @deprecated Will be removed in the next major version.
 */
const Setting = createSvgIcon({
  as: SettingSvg,
  ariaLabel: 'setting',
  category: '',
  displayName: 'Setting'
});

export default Setting;
