// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ShareSquareSvg from '@rsuite/icon-font/lib/legacy/ShareSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const ShareSquare = createSvgIcon({
  as: ShareSquareSvg,
  ariaLabel: 'share square',
  category: '',
  displayName: 'ShareSquare'
});

export default ShareSquare;
