// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ShareSquareOSvg from '@rsuite/icon-font/lib/legacy/ShareSquareO';

/**
 * @deprecated Will be removed in the next major version.
 */
const ShareSquareO = createSvgIcon({
  as: ShareSquareOSvg,
  ariaLabel: 'share square o',
  category: '',
  displayName: 'ShareSquareO'
});

export default ShareSquareO;
