// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ShareAltSvg from '@rsuite/icon-font/lib/legacy/ShareAlt';

/**
 * @deprecated Will be removed in the next major version.
 */
const ShareAlt = createSvgIcon({
  as: ShareAltSvg,
  ariaLabel: 'share alt',
  category: '',
  displayName: 'ShareAlt'
});

export default ShareAlt;
