// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Share2Svg from '@rsuite/icon-font/lib/legacy/Share2';

/**
 * @deprecated Will be removed in the next major version.
 */
const Share2 = createSvgIcon({
  as: Share2Svg,
  ariaLabel: 'share 2',
  category: '',
  displayName: 'Share2'
});

export default Share2;
