// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ShareAltSquareSvg from '@rsuite/icon-font/lib/legacy/ShareAltSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const ShareAltSquare = createSvgIcon({
  as: ShareAltSquareSvg,
  ariaLabel: 'share alt square',
  category: '',
  displayName: 'ShareAltSquare'
});

export default ShareAltSquare;
