// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ShoppingBagSvg from '@rsuite/icon-font/lib/legacy/ShoppingBag';

/**
 * @deprecated Will be removed in the next major version.
 */
const ShoppingBag = createSvgIcon({
  as: ShoppingBagSvg,
  ariaLabel: 'shopping bag',
  category: '',
  displayName: 'ShoppingBag'
});

export default ShoppingBag;
