// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ShoppingBasketSvg from '@rsuite/icon-font/lib/legacy/ShoppingBasket';

/**
 * @deprecated Will be removed in the next major version.
 */
const ShoppingBasket = createSvgIcon({
  as: ShoppingBasketSvg,
  ariaLabel: 'shopping basket',
  category: '',
  displayName: 'ShoppingBasket'
});

export default ShoppingBasket;
