// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SignalSvg from '@rsuite/icon-font/lib/legacy/Signal';

/**
 * @deprecated Will be removed in the next major version.
 */
const Signal = createSvgIcon({
  as: SignalSvg,
  ariaLabel: 'signal',
  category: '',
  displayName: 'Signal'
});

export default Signal;
