// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SimplybuiltSvg from '@rsuite/icon-font/lib/legacy/Simplybuilt';

/**
 * @deprecated Will be removed in the next major version.
 */
const Simplybuilt = createSvgIcon({
  as: SimplybuiltSvg,
  ariaLabel: 'simplybuilt',
  category: '',
  displayName: 'Simplybuilt'
});

export default Simplybuilt;
