// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SlackSvg from '@rsuite/icon-font/lib/legacy/Slack';

/**
 * @deprecated Will be removed in the next major version.
 */
const Slack = createSvgIcon({
  as: SlackSvg,
  ariaLabel: 'slack',
  category: '',
  displayName: 'Slack'
});

export default Slack;
