// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SlidersSvg from '@rsuite/icon-font/lib/legacy/Sliders';

/**
 * @deprecated Will be removed in the next major version.
 */
const Sliders = createSvgIcon({
  as: SlidersSvg,
  ariaLabel: 'sliders',
  category: '',
  displayName: 'Sliders'
});

export default Sliders;
