// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SlideshareSvg from '@rsuite/icon-font/lib/legacy/Slideshare';

/**
 * @deprecated Will be removed in the next major version.
 */
const Slideshare = createSvgIcon({
  as: SlideshareSvg,
  ariaLabel: 'slideshare',
  category: '',
  displayName: 'Slideshare'
});

export default Slideshare;
