// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SmileOSvg from '@rsuite/icon-font/lib/legacy/SmileO';

/**
 * @deprecated Will be removed in the next major version.
 */
const SmileO = createSvgIcon({
  as: SmileOSvg,
  ariaLabel: 'smile o',
  category: '',
  displayName: 'SmileO'
});

export default SmileO;
