// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SnapchatSquareSvg from '@rsuite/icon-font/lib/legacy/SnapchatSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const SnapchatSquare = createSvgIcon({
  as: SnapchatSquareSvg,
  ariaLabel: 'snapchat square',
  category: '',
  displayName: 'SnapchatSquare'
});

export default SnapchatSquare;
