// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SortUpSvg from '@rsuite/icon-font/lib/legacy/SortUp';

/**
 * @deprecated Will be removed in the next major version.
 */
const SortUp = createSvgIcon({
  as: SortUpSvg,
  ariaLabel: 'sort up',
  category: '',
  displayName: 'SortUp'
});

export default SortUp;
