// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SortAmountAscSvg from '@rsuite/icon-font/lib/legacy/SortAmountAsc';

/**
 * @deprecated Will be removed in the next major version.
 */
const SortAmountAsc = createSvgIcon({
  as: SortAmountAscSvg,
  ariaLabel: 'sort amount asc',
  category: '',
  displayName: 'SortAmountAsc'
});

export default SortAmountAsc;
