// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SortAlphaDescSvg from '@rsuite/icon-font/lib/legacy/SortAlphaDesc';

/**
 * @deprecated Will be removed in the next major version.
 */
const SortAlphaDesc = createSvgIcon({
  as: SortAlphaDescSvg,
  ariaLabel: 'sort alpha desc',
  category: '',
  displayName: 'SortAlphaDesc'
});

export default SortAlphaDesc;
