// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SortAlphaAscSvg from '@rsuite/icon-font/lib/legacy/SortAlphaAsc';

/**
 * @deprecated Will be removed in the next major version.
 */
const SortAlphaAsc = createSvgIcon({
  as: SortAlphaAscSvg,
  ariaLabel: 'sort alpha asc',
  category: '',
  displayName: 'SortAlphaAsc'
});

export default SortAlphaAsc;
