// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SortNumericAscSvg from '@rsuite/icon-font/lib/legacy/SortNumericAsc';

/**
 * @deprecated Will be removed in the next major version.
 */
const SortNumericAsc = createSvgIcon({
  as: SortNumericAscSvg,
  ariaLabel: 'sort numeric asc',
  category: '',
  displayName: 'SortNumericAsc'
});

export default SortNumericAsc;
