// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SortDescSvg from '@rsuite/icon-font/lib/legacy/SortDesc';

/**
 * @deprecated Will be removed in the next major version.
 */
const SortDesc = createSvgIcon({
  as: SortDescSvg,
  ariaLabel: 'sort desc',
  category: '',
  displayName: 'SortDesc'
});

export default SortDesc;
