// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SortAmountDescSvg from '@rsuite/icon-font/lib/legacy/SortAmountDesc';

/**
 * @deprecated Will be removed in the next major version.
 */
const SortAmountDesc = createSvgIcon({
  as: SortAmountDescSvg,
  ariaLabel: 'sort amount desc',
  category: '',
  displayName: 'SortAmountDesc'
});

export default SortAmountDesc;
