// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SpaceShuttleSvg from '@rsuite/icon-font/lib/legacy/SpaceShuttle';

/**
 * @deprecated Will be removed in the next major version.
 */
const SpaceShuttle = createSvgIcon({
  as: SpaceShuttleSvg,
  ariaLabel: 'space shuttle',
  category: '',
  displayName: 'SpaceShuttle'
});

export default SpaceShuttle;
