// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SpinnerSvg from '@rsuite/icon-font/lib/legacy/Spinner';

/**
 * @deprecated Will be removed in the next major version.
 */
const Spinner = createSvgIcon({
  as: SpinnerSvg,
  ariaLabel: 'spinner',
  category: '',
  displayName: 'Spinner'
});

export default Spinner;
