// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SpoonSvg from '@rsuite/icon-font/lib/legacy/Spoon';

/**
 * @deprecated Will be removed in the next major version.
 */
const Spoon = createSvgIcon({
  as: SpoonSvg,
  ariaLabel: 'spoon',
  category: '',
  displayName: 'Spoon'
});

export default Spoon;
