// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SpotifySvg from '@rsuite/icon-font/lib/legacy/Spotify';

/**
 * @deprecated Will be removed in the next major version.
 */
const Spotify = createSvgIcon({
  as: SpotifySvg,
  ariaLabel: 'spotify',
  category: '',
  displayName: 'Spotify'
});

export default Spotify;
