// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StarOSvg from '@rsuite/icon-font/lib/legacy/StarO';

/**
 * @deprecated Will be removed in the next major version.
 */
const StarO = createSvgIcon({
  as: StarOSvg,
  ariaLabel: 'star o',
  category: '',
  displayName: 'StarO'
});

export default StarO;
