// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StarSvg from '@rsuite/icon-font/lib/legacy/Star';

/**
 * @deprecated Will be removed in the next major version.
 */
const Star = createSvgIcon({
  as: StarSvg,
  ariaLabel: 'star',
  category: '',
  displayName: 'Star'
});

export default Star;
