// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StarHalfOSvg from '@rsuite/icon-font/lib/legacy/StarHalfO';

/**
 * @deprecated Will be removed in the next major version.
 */
const StarHalfO = createSvgIcon({
  as: StarHalfOSvg,
  ariaLabel: 'star half o',
  category: '',
  displayName: 'StarHalfO'
});

export default StarHalfO;
