// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SteamSquareSvg from '@rsuite/icon-font/lib/legacy/SteamSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const SteamSquare = createSvgIcon({
  as: SteamSquareSvg,
  ariaLabel: 'steam square',
  category: '',
  displayName: 'SteamSquare'
});

export default SteamSquare;
