// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SteamSvg from '@rsuite/icon-font/lib/legacy/Steam';

/**
 * @deprecated Will be removed in the next major version.
 */
const Steam = createSvgIcon({
  as: SteamSvg,
  ariaLabel: 'steam',
  category: '',
  displayName: 'Steam'
});

export default Steam;
