// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StepForwardSvg from '@rsuite/icon-font/lib/legacy/StepForward';

/**
 * @deprecated Will be removed in the next major version.
 */
const StepForward = createSvgIcon({
  as: StepForwardSvg,
  ariaLabel: 'step forward',
  category: '',
  displayName: 'StepForward'
});

export default StepForward;
