// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StepBackwardSvg from '@rsuite/icon-font/lib/legacy/StepBackward';

/**
 * @deprecated Will be removed in the next major version.
 */
const StepBackward = createSvgIcon({
  as: StepBackwardSvg,
  ariaLabel: 'step backward',
  category: '',
  displayName: 'StepBackward'
});

export default StepBackward;
