// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StethoscopeSvg from '@rsuite/icon-font/lib/legacy/Stethoscope';

/**
 * @deprecated Will be removed in the next major version.
 */
const Stethoscope = createSvgIcon({
  as: StethoscopeSvg,
  ariaLabel: 'stethoscope',
  category: '',
  displayName: 'Stethoscope'
});

export default Stethoscope;
