// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StopCircleSvg from '@rsuite/icon-font/lib/legacy/StopCircle';

/**
 * @deprecated Will be removed in the next major version.
 */
const StopCircle = createSvgIcon({
  as: StopCircleSvg,
  ariaLabel: 'stop circle',
  category: '',
  displayName: 'StopCircle'
});

export default StopCircle;
