// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StrikethroughSvg from '@rsuite/icon-font/lib/legacy/Strikethrough';

/**
 * @deprecated Will be removed in the next major version.
 */
const Strikethrough = createSvgIcon({
  as: StrikethroughSvg,
  ariaLabel: 'strikethrough',
  category: '',
  displayName: 'Strikethrough'
});

export default Strikethrough;
