// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StumbleuponCircleSvg from '@rsuite/icon-font/lib/legacy/StumbleuponCircle';

/**
 * @deprecated Will be removed in the next major version.
 */
const StumbleuponCircle = createSvgIcon({
  as: StumbleuponCircleSvg,
  ariaLabel: 'stumbleupon circle',
  category: '',
  displayName: 'StumbleuponCircle'
});

export default StumbleuponCircle;
