// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import StumbleuponSvg from '@rsuite/icon-font/lib/legacy/Stumbleupon';

/**
 * @deprecated Will be removed in the next major version.
 */
const Stumbleupon = createSvgIcon({
  as: StumbleuponSvg,
  ariaLabel: 'stumbleupon',
  category: '',
  displayName: 'Stumbleupon'
});

export default Stumbleupon;
