// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SubscriptSvg from '@rsuite/icon-font/lib/legacy/Subscript';

/**
 * @deprecated Will be removed in the next major version.
 */
const Subscript = createSvgIcon({
  as: SubscriptSvg,
  ariaLabel: 'subscript',
  category: '',
  displayName: 'Subscript'
});

export default Subscript;
