// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SubwaySvg from '@rsuite/icon-font/lib/legacy/Subway';

/**
 * @deprecated Will be removed in the next major version.
 */
const Subway = createSvgIcon({
  as: SubwaySvg,
  ariaLabel: 'subway',
  category: '',
  displayName: 'Subway'
});

export default Subway;
