// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SuperscriptSvg from '@rsuite/icon-font/lib/legacy/Superscript';

/**
 * @deprecated Will be removed in the next major version.
 */
const Superscript = createSvgIcon({
  as: SuperscriptSvg,
  ariaLabel: 'superscript',
  category: '',
  displayName: 'Superscript'
});

export default Superscript;
