// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import SupportSvg from '@rsuite/icon-font/lib/legacy/Support';

/**
 * @deprecated Will be removed in the next major version.
 */
const Support = createSvgIcon({
  as: SupportSvg,
  ariaLabel: 'support',
  category: '',
  displayName: 'Support'
});

export default Support;
