// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TableSvg from '@rsuite/icon-font/lib/legacy/Table';

/**
 * @deprecated Will be removed in the next major version.
 */
const Table = createSvgIcon({
  as: TableSvg,
  ariaLabel: 'table',
  category: '',
  displayName: 'Table'
});

export default Table;
