// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TagSvg from '@rsuite/icon-font/lib/legacy/Tag';

/**
 * @deprecated Will be removed in the next major version.
 */
const Tag = createSvgIcon({
  as: TagSvg,
  ariaLabel: 'tag',
  category: '',
  displayName: 'Tag'
});

export default Tag;
