// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TagAuthorizeSvg from '@rsuite/icon-font/lib/legacy/TagAuthorize';

/**
 * @deprecated Will be removed in the next major version.
 */
const TagAuthorize = createSvgIcon({
  as: TagAuthorizeSvg,
  ariaLabel: 'tag authorize',
  category: '',
  displayName: 'TagAuthorize'
});

export default TagAuthorize;
