// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TagAreaSvg from '@rsuite/icon-font/lib/legacy/TagArea';

/**
 * @deprecated Will be removed in the next major version.
 */
const TagArea = createSvgIcon({
  as: TagAreaSvg,
  ariaLabel: 'tag area',
  category: '',
  displayName: 'TagArea'
});

export default TagArea;
