// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TagsSvg from '@rsuite/icon-font/lib/legacy/Tags';

/**
 * @deprecated Will be removed in the next major version.
 */
const Tags = createSvgIcon({
  as: TagsSvg,
  ariaLabel: 'tags',
  category: '',
  displayName: 'Tags'
});

export default Tags;
