// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TaskSvg from '@rsuite/icon-font/lib/legacy/Task';

/**
 * @deprecated Will be removed in the next major version.
 */
const Task = createSvgIcon({
  as: TaskSvg,
  ariaLabel: 'task',
  category: '',
  displayName: 'Task'
});

export default Task;
