// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TelegramSvg from '@rsuite/icon-font/lib/legacy/Telegram';

/**
 * @deprecated Will be removed in the next major version.
 */
const Telegram = createSvgIcon({
  as: TelegramSvg,
  ariaLabel: 'telegram',
  category: '',
  displayName: 'Telegram'
});

export default Telegram;
