// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TencentWeiboSvg from '@rsuite/icon-font/lib/legacy/TencentWeibo';

/**
 * @deprecated Will be removed in the next major version.
 */
const TencentWeibo = createSvgIcon({
  as: TencentWeiboSvg,
  ariaLabel: 'tencent weibo',
  category: '',
  displayName: 'TencentWeibo'
});

export default TencentWeibo;
