// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TerminalLineSvg from '@rsuite/icon-font/lib/legacy/TerminalLine';

/**
 * @deprecated Will be removed in the next major version.
 */
const TerminalLine = createSvgIcon({
  as: TerminalLineSvg,
  ariaLabel: 'terminal line',
  category: '',
  displayName: 'TerminalLine'
});

export default TerminalLine;
