// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TerminalSvg from '@rsuite/icon-font/lib/legacy/Terminal';

/**
 * @deprecated Will be removed in the next major version.
 */
const Terminal = createSvgIcon({
  as: TerminalSvg,
  ariaLabel: 'terminal',
  category: '',
  displayName: 'Terminal'
});

export default Terminal;
