// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TextHeightSvg from '@rsuite/icon-font/lib/legacy/TextHeight';

/**
 * @deprecated Will be removed in the next major version.
 */
const TextHeight = createSvgIcon({
  as: TextHeightSvg,
  ariaLabel: 'text height',
  category: '',
  displayName: 'TextHeight'
});

export default TextHeight;
