// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ThSvg from '@rsuite/icon-font/lib/legacy/Th';

/**
 * @deprecated Will be removed in the next major version.
 */
const Th = createSvgIcon({
  as: ThSvg,
  ariaLabel: 'th',
  category: '',
  displayName: 'Th'
});

export default Th;
