// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ThemeisleSvg from '@rsuite/icon-font/lib/legacy/Themeisle';

/**
 * @deprecated Will be removed in the next major version.
 */
const Themeisle = createSvgIcon({
  as: ThemeisleSvg,
  ariaLabel: 'themeisle',
  category: '',
  displayName: 'Themeisle'
});

export default Themeisle;
