// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ThermometerSvg from '@rsuite/icon-font/lib/legacy/Thermometer';

/**
 * @deprecated Will be removed in the next major version.
 */
const Thermometer = createSvgIcon({
  as: ThermometerSvg,
  ariaLabel: 'thermometer',
  category: '',
  displayName: 'Thermometer'
});

export default Thermometer;
