// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Thermometer2Svg from '@rsuite/icon-font/lib/legacy/Thermometer2';

/**
 * @deprecated Will be removed in the next major version.
 */
const Thermometer2 = createSvgIcon({
  as: Thermometer2Svg,
  ariaLabel: 'thermometer 2',
  category: '',
  displayName: 'Thermometer2'
});

export default Thermometer2;
