// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ThLargeSvg from '@rsuite/icon-font/lib/legacy/ThLarge';

/**
 * @deprecated Will be removed in the next major version.
 */
const ThLarge = createSvgIcon({
  as: ThLargeSvg,
  ariaLabel: 'th large',
  category: '',
  displayName: 'ThLarge'
});

export default ThLarge;
