// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ThumbsODownSvg from '@rsuite/icon-font/lib/legacy/ThumbsODown';

/**
 * @deprecated Will be removed in the next major version.
 */
const ThumbsODown = createSvgIcon({
  as: ThumbsODownSvg,
  ariaLabel: 'thumbs o down',
  category: '',
  displayName: 'ThumbsODown'
});

export default ThumbsODown;
