// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ThumbTackSvg from '@rsuite/icon-font/lib/legacy/ThumbTack';

/**
 * @deprecated Will be removed in the next major version.
 */
const ThumbTack = createSvgIcon({
  as: ThumbTackSvg,
  ariaLabel: 'thumb tack',
  category: '',
  displayName: 'ThumbTack'
});

export default ThumbTack;
