// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ThumbsDownSvg from '@rsuite/icon-font/lib/legacy/ThumbsDown';

/**
 * @deprecated Will be removed in the next major version.
 */
const ThumbsDown = createSvgIcon({
  as: ThumbsDownSvg,
  ariaLabel: 'thumbs down',
  category: '',
  displayName: 'ThumbsDown'
});

export default ThumbsDown;
