// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ThumbsUpSvg from '@rsuite/icon-font/lib/legacy/ThumbsUp';

/**
 * @deprecated Will be removed in the next major version.
 */
const ThumbsUp = createSvgIcon({
  as: ThumbsUpSvg,
  ariaLabel: 'thumbs up',
  category: '',
  displayName: 'ThumbsUp'
});

export default ThumbsUp;
