// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TimesCircleSvg from '@rsuite/icon-font/lib/legacy/TimesCircle';

/**
 * @deprecated Will be removed in the next major version.
 */
const TimesCircle = createSvgIcon({
  as: TimesCircleSvg,
  ariaLabel: 'times circle',
  category: '',
  displayName: 'TimesCircle'
});

export default TimesCircle;
