// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TmallSvg from '@rsuite/icon-font/lib/legacy/Tmall';

/**
 * @deprecated Will be removed in the next major version.
 */
const Tmall = createSvgIcon({
  as: TmallSvg,
  ariaLabel: 'tmall',
  category: '',
  displayName: 'Tmall'
});

export default Tmall;
