// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ToggleOnSvg from '@rsuite/icon-font/lib/legacy/ToggleOn';

/**
 * @deprecated Will be removed in the next major version.
 */
const ToggleOn = createSvgIcon({
  as: ToggleOnSvg,
  ariaLabel: 'toggle on',
  category: '',
  displayName: 'ToggleOn'
});

export default ToggleOn;
