// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ToggleLeftSvg from '@rsuite/icon-font/lib/legacy/ToggleLeft';

/**
 * @deprecated Will be removed in the next major version.
 */
const ToggleLeft = createSvgIcon({
  as: ToggleLeftSvg,
  ariaLabel: 'toggle left',
  category: '',
  displayName: 'ToggleLeft'
});

export default ToggleLeft;
