// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TrademarkSvg from '@rsuite/icon-font/lib/legacy/Trademark';

/**
 * @deprecated Will be removed in the next major version.
 */
const Trademark = createSvgIcon({
  as: TrademarkSvg,
  ariaLabel: 'trademark',
  category: '',
  displayName: 'Trademark'
});

export default Trademark;
