// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import Trash2Svg from '@rsuite/icon-font/lib/legacy/Trash2';

/**
 * @deprecated Will be removed in the next major version.
 */
const Trash2 = createSvgIcon({
  as: Trash2Svg,
  ariaLabel: 'trash 2',
  category: '',
  displayName: 'Trash2'
});

export default Trash2;
