// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TrashSvg from '@rsuite/icon-font/lib/legacy/Trash';

/**
 * @deprecated Will be removed in the next major version.
 */
const Trash = createSvgIcon({
  as: TrashSvg,
  ariaLabel: 'trash',
  category: '',
  displayName: 'Trash'
});

export default Trash;
