// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TreeOpenSvg from '@rsuite/icon-font/lib/legacy/TreeOpen';

/**
 * @deprecated Will be removed in the next major version.
 */
const TreeOpen = createSvgIcon({
  as: TreeOpenSvg,
  ariaLabel: 'tree open',
  category: '',
  displayName: 'TreeOpen'
});

export default TreeOpen;
