// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TreeCloseSvg from '@rsuite/icon-font/lib/legacy/TreeClose';

/**
 * @deprecated Will be removed in the next major version.
 */
const TreeClose = createSvgIcon({
  as: TreeCloseSvg,
  ariaLabel: 'tree close',
  category: '',
  displayName: 'TreeClose'
});

export default TreeClose;
