// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TrelloSvg from '@rsuite/icon-font/lib/legacy/Trello';

/**
 * @deprecated Will be removed in the next major version.
 */
const Trello = createSvgIcon({
  as: TrelloSvg,
  ariaLabel: 'trello',
  category: '',
  displayName: 'Trello'
});

export default Trello;
