// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TrendSvg from '@rsuite/icon-font/lib/legacy/Trend';

/**
 * @deprecated Will be removed in the next major version.
 */
const Trend = createSvgIcon({
  as: TrendSvg,
  ariaLabel: 'trend',
  category: '',
  displayName: 'Trend'
});

export default Trend;
