// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TripadvisorSvg from '@rsuite/icon-font/lib/legacy/Tripadvisor';

/**
 * @deprecated Will be removed in the next major version.
 */
const Tripadvisor = createSvgIcon({
  as: TripadvisorSvg,
  ariaLabel: 'tripadvisor',
  category: '',
  displayName: 'Tripadvisor'
});

export default Tripadvisor;
