// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TrySvg from '@rsuite/icon-font/lib/legacy/Try';

/**
 * @deprecated Will be removed in the next major version.
 */
const Try = createSvgIcon({
  as: TrySvg,
  ariaLabel: 'try',
  category: '',
  displayName: 'Try'
});

export default Try;
