// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import TwinkleStarSvg from '@rsuite/icon-font/lib/legacy/TwinkleStar';

/**
 * @deprecated Will be removed in the next major version.
 */
const TwinkleStar = createSvgIcon({
  as: TwinkleStarSvg,
  ariaLabel: 'twinkle star',
  category: '',
  displayName: 'TwinkleStar'
});

export default TwinkleStar;
