// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UniversalAccessSvg from '@rsuite/icon-font/lib/legacy/UniversalAccess';

/**
 * @deprecated Will be removed in the next major version.
 */
const UniversalAccess = createSvgIcon({
  as: UniversalAccessSvg,
  ariaLabel: 'universal access',
  category: '',
  displayName: 'UniversalAccess'
});

export default UniversalAccess;
