// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UploadSvg from '@rsuite/icon-font/lib/legacy/Upload';

/**
 * @deprecated Will be removed in the next major version.
 */
const Upload = createSvgIcon({
  as: UploadSvg,
  ariaLabel: 'upload',
  category: '',
  displayName: 'Upload'
});

export default Upload;
