// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UsbSvg from '@rsuite/icon-font/lib/legacy/Usb';

/**
 * @deprecated Will be removed in the next major version.
 */
const Usb = createSvgIcon({
  as: UsbSvg,
  ariaLabel: 'usb',
  category: '',
  displayName: 'Usb'
});

export default Usb;
