// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UserCircleOSvg from '@rsuite/icon-font/lib/legacy/UserCircleO';

/**
 * @deprecated Will be removed in the next major version.
 */
const UserCircleO = createSvgIcon({
  as: UserCircleOSvg,
  ariaLabel: 'user circle o',
  category: '',
  displayName: 'UserCircleO'
});

export default UserCircleO;
