// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UserSecretSvg from '@rsuite/icon-font/lib/legacy/UserSecret';

/**
 * @deprecated Will be removed in the next major version.
 */
const UserSecret = createSvgIcon({
  as: UserSecretSvg,
  ariaLabel: 'user secret',
  category: '',
  displayName: 'UserSecret'
});

export default UserSecret;
