// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UserAnalysisSvg from '@rsuite/icon-font/lib/legacy/UserAnalysis';

/**
 * @deprecated Will be removed in the next major version.
 */
const UserAnalysis = createSvgIcon({
  as: UserAnalysisSvg,
  ariaLabel: 'user analysis',
  category: '',
  displayName: 'UserAnalysis'
});

export default UserAnalysis;
