// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UserTimesSvg from '@rsuite/icon-font/lib/legacy/UserTimes';

/**
 * @deprecated Will be removed in the next major version.
 */
const UserTimes = createSvgIcon({
  as: UserTimesSvg,
  ariaLabel: 'user times',
  category: '',
  displayName: 'UserTimes'
});

export default UserTimes;
