// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import UserMdSvg from '@rsuite/icon-font/lib/legacy/UserMd';

/**
 * @deprecated Will be removed in the next major version.
 */
const UserMd = createSvgIcon({
  as: UserMdSvg,
  ariaLabel: 'user md',
  category: '',
  displayName: 'UserMd'
});

export default UserMd;
