// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import VcardOSvg from '@rsuite/icon-font/lib/legacy/VcardO';

/**
 * @deprecated Will be removed in the next major version.
 */
const VcardO = createSvgIcon({
  as: VcardOSvg,
  ariaLabel: 'vcard o',
  category: '',
  displayName: 'VcardO'
});

export default VcardO;
