// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import VenusMarsSvg from '@rsuite/icon-font/lib/legacy/VenusMars';

/**
 * @deprecated Will be removed in the next major version.
 */
const VenusMars = createSvgIcon({
  as: VenusMarsSvg,
  ariaLabel: 'venus mars',
  category: '',
  displayName: 'VenusMars'
});

export default VenusMars;
