// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import VenusDoubleSvg from '@rsuite/icon-font/lib/legacy/VenusDouble';

/**
 * @deprecated Will be removed in the next major version.
 */
const VenusDouble = createSvgIcon({
  as: VenusDoubleSvg,
  ariaLabel: 'venus double',
  category: '',
  displayName: 'VenusDouble'
});

export default VenusDouble;
