// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import VenusSvg from '@rsuite/icon-font/lib/legacy/Venus';

/**
 * @deprecated Will be removed in the next major version.
 */
const Venus = createSvgIcon({
  as: VenusSvg,
  ariaLabel: 'venus',
  category: '',
  displayName: 'Venus'
});

export default Venus;
