// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ViacoinSvg from '@rsuite/icon-font/lib/legacy/Viacoin';

/**
 * @deprecated Will be removed in the next major version.
 */
const Viacoin = createSvgIcon({
  as: ViacoinSvg,
  ariaLabel: 'viacoin',
  category: '',
  displayName: 'Viacoin'
});

export default Viacoin;
