// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ViadeoSvg from '@rsuite/icon-font/lib/legacy/Viadeo';

/**
 * @deprecated Will be removed in the next major version.
 */
const Viadeo = createSvgIcon({
  as: ViadeoSvg,
  ariaLabel: 'viadeo',
  category: '',
  displayName: 'Viadeo'
});

export default Viadeo;
