// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import VideoCameraSvg from '@rsuite/icon-font/lib/legacy/VideoCamera';

/**
 * @deprecated Will be removed in the next major version.
 */
const VideoCamera = createSvgIcon({
  as: VideoCameraSvg,
  ariaLabel: 'video camera',
  category: '',
  displayName: 'VideoCamera'
});

export default VideoCamera;
