// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import ViewsAuthorizeSvg from '@rsuite/icon-font/lib/legacy/ViewsAuthorize';

/**
 * @deprecated Will be removed in the next major version.
 */
const ViewsAuthorize = createSvgIcon({
  as: ViewsAuthorizeSvg,
  ariaLabel: 'views authorize',
  category: '',
  displayName: 'ViewsAuthorize'
});

export default ViewsAuthorize;
