// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import VimeoSquareSvg from '@rsuite/icon-font/lib/legacy/VimeoSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const VimeoSquare = createSvgIcon({
  as: VimeoSquareSvg,
  ariaLabel: 'vimeo square',
  category: '',
  displayName: 'VimeoSquare'
});

export default VimeoSquare;
