// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import VimeoSvg from '@rsuite/icon-font/lib/legacy/Vimeo';

/**
 * @deprecated Will be removed in the next major version.
 */
const Vimeo = createSvgIcon({
  as: VimeoSvg,
  ariaLabel: 'vimeo',
  category: '',
  displayName: 'Vimeo'
});

export default Vimeo;
