// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import VkSvg from '@rsuite/icon-font/lib/legacy/Vk';

/**
 * @deprecated Will be removed in the next major version.
 */
const Vk = createSvgIcon({
  as: VkSvg,
  ariaLabel: 'vk',
  category: '',
  displayName: 'Vk'
});

export default Vk;
