// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import VolumeDownSvg from '@rsuite/icon-font/lib/legacy/VolumeDown';

/**
 * @deprecated Will be removed in the next major version.
 */
const VolumeDown = createSvgIcon({
  as: VolumeDownSvg,
  ariaLabel: 'volume down',
  category: '',
  displayName: 'VolumeDown'
});

export default VolumeDown;
