// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WarningSvg from '@rsuite/icon-font/lib/legacy/Warning';

/**
 * @deprecated Will be removed in the next major version.
 */
const Warning = createSvgIcon({
  as: WarningSvg,
  ariaLabel: 'warning',
  category: '',
  displayName: 'Warning'
});

export default Warning;
