// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WebSvg from '@rsuite/icon-font/lib/legacy/Web';

/**
 * @deprecated Will be removed in the next major version.
 */
const Web = createSvgIcon({
  as: WebSvg,
  ariaLabel: 'web',
  category: '',
  displayName: 'Web'
});

export default Web;
