// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WechatSvg from '@rsuite/icon-font/lib/legacy/Wechat';

/**
 * @deprecated Will be removed in the next major version.
 */
const Wechat = createSvgIcon({
  as: WechatSvg,
  ariaLabel: 'wechat',
  category: '',
  displayName: 'Wechat'
});

export default Wechat;
