// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WeiboSvg from '@rsuite/icon-font/lib/legacy/Weibo';

/**
 * @deprecated Will be removed in the next major version.
 */
const Weibo = createSvgIcon({
  as: WeiboSvg,
  ariaLabel: 'weibo',
  category: '',
  displayName: 'Weibo'
});

export default Weibo;
