// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WhatsappSvg from '@rsuite/icon-font/lib/legacy/Whatsapp';

/**
 * @deprecated Will be removed in the next major version.
 */
const Whatsapp = createSvgIcon({
  as: WhatsappSvg,
  ariaLabel: 'whatsapp',
  category: '',
  displayName: 'Whatsapp'
});

export default Whatsapp;
