// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WheelchairAltSvg from '@rsuite/icon-font/lib/legacy/WheelchairAlt';

/**
 * @deprecated Will be removed in the next major version.
 */
const WheelchairAlt = createSvgIcon({
  as: WheelchairAltSvg,
  ariaLabel: 'wheelchair alt',
  category: '',
  displayName: 'WheelchairAlt'
});

export default WheelchairAlt;
