// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WifiSvg from '@rsuite/icon-font/lib/legacy/Wifi';

/**
 * @deprecated Will be removed in the next major version.
 */
const Wifi = createSvgIcon({
  as: WifiSvg,
  ariaLabel: 'wifi',
  category: '',
  displayName: 'Wifi'
});

export default Wifi;
