// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WikipediaWSvg from '@rsuite/icon-font/lib/legacy/WikipediaW';

/**
 * @deprecated Will be removed in the next major version.
 */
const WikipediaW = createSvgIcon({
  as: WikipediaWSvg,
  ariaLabel: 'wikipedia w',
  category: '',
  displayName: 'WikipediaW'
});

export default WikipediaW;
