// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WindowCloseOSvg from '@rsuite/icon-font/lib/legacy/WindowCloseO';

/**
 * @deprecated Will be removed in the next major version.
 */
const WindowCloseO = createSvgIcon({
  as: WindowCloseOSvg,
  ariaLabel: 'window close o',
  category: '',
  displayName: 'WindowCloseO'
});

export default WindowCloseO;
