// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WindowRestoreSvg from '@rsuite/icon-font/lib/legacy/WindowRestore';

/**
 * @deprecated Will be removed in the next major version.
 */
const WindowRestore = createSvgIcon({
  as: WindowRestoreSvg,
  ariaLabel: 'window restore',
  category: '',
  displayName: 'WindowRestore'
});

export default WindowRestore;
