// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WindowCloseSvg from '@rsuite/icon-font/lib/legacy/WindowClose';

/**
 * @deprecated Will be removed in the next major version.
 */
const WindowClose = createSvgIcon({
  as: WindowCloseSvg,
  ariaLabel: 'window close',
  category: '',
  displayName: 'WindowClose'
});

export default WindowClose;
