// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WindowMinimizeSvg from '@rsuite/icon-font/lib/legacy/WindowMinimize';

/**
 * @deprecated Will be removed in the next major version.
 */
const WindowMinimize = createSvgIcon({
  as: WindowMinimizeSvg,
  ariaLabel: 'window minimize',
  category: '',
  displayName: 'WindowMinimize'
});

export default WindowMinimize;
