// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WordpressSvg from '@rsuite/icon-font/lib/legacy/Wordpress';

/**
 * @deprecated Will be removed in the next major version.
 */
const Wordpress = createSvgIcon({
  as: WordpressSvg,
  ariaLabel: 'wordpress',
  category: '',
  displayName: 'Wordpress'
});

export default Wordpress;
