// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WpbeginnerSvg from '@rsuite/icon-font/lib/legacy/Wpbeginner';

/**
 * @deprecated Will be removed in the next major version.
 */
const Wpbeginner = createSvgIcon({
  as: WpbeginnerSvg,
  ariaLabel: 'wpbeginner',
  category: '',
  displayName: 'Wpbeginner'
});

export default Wpbeginner;
