// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WpexplorerSvg from '@rsuite/icon-font/lib/legacy/Wpexplorer';

/**
 * @deprecated Will be removed in the next major version.
 */
const Wpexplorer = createSvgIcon({
  as: WpexplorerSvg,
  ariaLabel: 'wpexplorer',
  category: '',
  displayName: 'Wpexplorer'
});

export default Wpexplorer;
