// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import WrenchSvg from '@rsuite/icon-font/lib/legacy/Wrench';

/**
 * @deprecated Will be removed in the next major version.
 */
const Wrench = createSvgIcon({
  as: WrenchSvg,
  ariaLabel: 'wrench',
  category: '',
  displayName: 'Wrench'
});

export default Wrench;
