// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import XingSquareSvg from '@rsuite/icon-font/lib/legacy/XingSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const XingSquare = createSvgIcon({
  as: XingSquareSvg,
  ariaLabel: 'xing square',
  category: '',
  displayName: 'XingSquare'
});

export default XingSquare;
