// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import YahooSvg from '@rsuite/icon-font/lib/legacy/Yahoo';

/**
 * @deprecated Will be removed in the next major version.
 */
const Yahoo = createSvgIcon({
  as: YahooSvg,
  ariaLabel: 'yahoo',
  category: '',
  displayName: 'Yahoo'
});

export default Yahoo;
