// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import YcSvg from '@rsuite/icon-font/lib/legacy/Yc';

/**
 * @deprecated Will be removed in the next major version.
 */
const Yc = createSvgIcon({
  as: YcSvg,
  ariaLabel: 'yc',
  category: '',
  displayName: 'Yc'
});

export default Yc;
