// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import YcSquareSvg from '@rsuite/icon-font/lib/legacy/YcSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const YcSquare = createSvgIcon({
  as: YcSquareSvg,
  ariaLabel: 'yc square',
  category: '',
  displayName: 'YcSquare'
});

export default YcSquare;
