// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import YoastSvg from '@rsuite/icon-font/lib/legacy/Yoast';

/**
 * @deprecated Will be removed in the next major version.
 */
const Yoast = createSvgIcon({
  as: YoastSvg,
  ariaLabel: 'yoast',
  category: '',
  displayName: 'Yoast'
});

export default Yoast;
