// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import YoutubePlaySvg from '@rsuite/icon-font/lib/legacy/YoutubePlay';

/**
 * @deprecated Will be removed in the next major version.
 */
const YoutubePlay = createSvgIcon({
  as: YoutubePlaySvg,
  ariaLabel: 'youtube play',
  category: '',
  displayName: 'YoutubePlay'
});

export default YoutubePlay;
