// Generated by script, don't edit it please.
import createSvgIcon from '../../createSvgIcon';
import YoutubeSquareSvg from '@rsuite/icon-font/lib/legacy/YoutubeSquare';

/**
 * @deprecated Will be removed in the next major version.
 */
const YoutubeSquare = createSvgIcon({
  as: YoutubeSquareSvg,
  ariaLabel: 'youtube square',
  category: '',
  displayName: 'YoutubeSquare'
});

export default YoutubeSquare;
