// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const CharacterAuthorize = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M14 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v9a1 1 0 0 0 1 1h3.5a.5.5 0 0 1 0 1H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h11a2 2 0 0 1 2 2v2.5a.5.5 0 0 1-1 0z" />
    <path d="M5 6a1 1 0 1 0 0-2 1 1 0 0 0 0 2m0 1a2 2 0 1 1-.001-3.999A2 2 0 0 1 5 7" />
    <path d="M5 6c1.534 0 2.567.62 2.974 1.842a.5.5 0 1 1-.948.316C6.767 7.38 6.133 7 5 7c-1.271 0-1.938.738-1.996 1.849L3 9.01v.49a.5.5 0 0 1-.992.09L2 9.5v-.49C2 7.295 3.07 6 5 6M9.5 5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1M9.5 3h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1M16 9a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-2h-1v2H9V9z" />
    <path d="M15.175 10.12a.5.5 0 0 1 .651.759l-3.5 3a.5.5 0 0 1-.741-.102l-1-1.5a.5.5 0 1 1 .832-.554l.687 1.03z" />
  </svg>
);
const ForwardRef = forwardRef(CharacterAuthorize);
export default ForwardRef;
