// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const IdRule = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M10 15.5a.5.5 0 0 0-.5-.5H2a1 1 0 0 1-.993-.883L1 14V2a1 1 0 0 1 .883-.993L2 1h9a1 1 0 0 1 .993.883L12 2v2.5a.5.5 0 0 0 .992.09L13 4.5V2A2 2 0 0 0 11.149.005L11 0H2A2 2 0 0 0 .005 1.851L0 2v12c0 1.054.816 1.918 1.851 1.995L2 16h7.5a.5.5 0 0 0 .5-.5" />
    <path d="M6 3v3c1.105 0 2-.395 2-1.5S7.105 3 6 3M5 2h1c1.657 0 3 .843 3 2.5S7.657 7 6 7H5zM8.5 8h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1M7.5 12h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1 0-1M15.847 11.153a.523.523 0 0 1 0 .739L14.739 13l1.108 1.108a.523.523 0 0 1-.739.739L14 13.739l-1.108 1.108a.523.523 0 0 1-.739-.739L13.261 13l-1.108-1.108a.523.523 0 0 1 .739-.739L14 12.261l1.108-1.108a.523.523 0 0 1 .739 0M15.084 6.223a.5.5 0 0 1 .875.475l-.043.079-2 3a.5.5 0 0 1-.773.074l-.06-.074-1-1.5a.5.5 0 0 1 .776-.625l.057.07.584.874 1.584-2.374zM3 2h1v5H3z" />
  </svg>
);
const ForwardRef = forwardRef(IdRule);
export default ForwardRef;
