// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Location = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 3a3 3 0 1 1 0 6 3 3 0 0 1 0-6m0 1a2 2 0 1 0-.001 3.999A2 2 0 0 0 8 4" />
    <path d="M8 0c3 0 6 2.195 6 6.172q0 3.603-4.927 9.122l-.313.347a1.028 1.028 0 0 1-1.521 0Q1.999 9.888 2 6.172C2 2.195 5 0 8 0m0 1C5.217 1 3 3.061 3 6.172c0 2.167 1.639 5.128 4.979 8.796a.03.03 0 0 0 .027.009l.013-.007C11.361 11.3 13 8.339 13 6.172 13 3.062 10.783 1 8 1" />
    <path d="M8 8c2.064 0 3.413.91 3.93 2.673l.056.207.12.485-.971.24-.12-.485C10.661 9.686 9.701 9 8 9c-1.626 0-2.575.627-2.965 1.937l-.05.183-.12.485-.971-.24.12-.485C4.483 8.981 5.856 8 7.999 8z" />
  </svg>
);
const ForwardRef = forwardRef(Location);
export default ForwardRef;
