// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Member = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M14 1a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2zM5 8c-1.286 0-3 1.067-3 3v1h6v-1l-.006-.21C7.879 8.93 6.24 8 5 8m6.5 1h-1a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1M5 4a2 2 0 1 0-.001 3.999A2 2 0 0 0 5 4m8.5 3h-3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1m0-2h-3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1" />
  </svg>
);
const ForwardRef = forwardRef(Member);
export default ForwardRef;
