// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PeoplesTest = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M12.5 8a2.5 2.5 0 0 1 1.625 4.4A3.5 3.5 0 0 1 16 15.5v.5H9v-.5c0-1.347.76-2.516 1.875-3.101A2.5 2.5 0 0 1 12.5 8m0 5a2.5 2.5 0 0 0-2.45 2h4.9l-.038-.161A2.5 2.5 0 0 0 12.5 13m0-4a1.5 1.5 0 1 0 .001 3.001A1.5 1.5 0 0 0 12.5 9M7 10a2 2 0 1 1 0 4c-1.052 0-2 1.084-2 2H4c0-.99.644-2.036 1.578-2.594A2 2 0 0 1 7 10m0 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2" />
    <path d="M2.5 12A1.5 1.5 0 0 1 1 10.5v-8A1.5 1.5 0 0 1 2.5 1h8A1.5 1.5 0 0 1 12 2.5v3a.5.5 0 0 0 1 0v-3A2.5 2.5 0 0 0 10.5 0h-8A2.5 2.5 0 0 0 0 2.5v8A2.5 2.5 0 0 0 2.5 13a.5.5 0 0 0 0-1" />
    <path d="M4 6a2 2 0 1 1 .001 3.999A2 2 0 0 1 4 6m0 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m5.5 0a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zM5.812 2.11a.5.5 0 0 1 .128.628l-.05.075-2 2.5a.5.5 0 0 1-.744.042l-.062-.077-1-1.5a.5.5 0 0 1 .776-.625l.057.07.62.93 1.574-1.965a.5.5 0 0 1 .703-.078zM9.5 3a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1z" />
  </svg>
);
const ForwardRef = forwardRef(PeoplesTest);
export default ForwardRef;
