// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PeoplesCostomize = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M12.5 8a2.5 2.5 0 0 1 1.625 4.4A3.5 3.5 0 0 1 16 15.5v.5H9v-.5c0-1.347.76-2.516 1.875-3.101A2.5 2.5 0 0 1 12.5 8m0 5a2.5 2.5 0 0 0-2.45 2h4.9l-.038-.161A2.5 2.5 0 0 0 12.5 13m0-4a1.5 1.5 0 1 0 .001 3.001A1.5 1.5 0 0 0 12.5 9M7 10a2 2 0 1 1 0 4c-1.052 0-2 1.084-2 2H4c0-.99.644-2.036 1.578-2.594A2 2 0 0 1 7 10m0 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2" />
    <path d="M2.5 12A1.5 1.5 0 0 1 1 10.5v-8A1.5 1.5 0 0 1 2.5 1h8A1.5 1.5 0 0 1 12 2.5v3a.5.5 0 0 0 1 0v-3A2.5 2.5 0 0 0 10.5 0h-8A2.5 2.5 0 0 0 0 2.5v8A2.5 2.5 0 0 0 2.5 13a.5.5 0 0 0 0-1" />
    <path d="m3.839 8.161.212-.919 3.858-3.858c.122-.122.297-.128.389-.035l.354.354c.092.092.087.267-.035.389l-.943.943.707.707.943-.943c.503-.503.529-1.31.035-1.803l-.354-.354c-.493-.493-1.3-.467-1.803.035l-3.96 3.96a.5.5 0 0 0-.134.241l-.424 1.838a.5.5 0 0 0 .6.6l1.838-.424a.5.5 0 0 0 .241-.134l2.263-2.263-.707-.707-2.161 2.161z" />
  </svg>
);
const ForwardRef = forwardRef(PeoplesCostomize);
export default ForwardRef;
