// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PeoplesMap = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M12.5 9a1.5 1.5 0 1 0-.001-3.001A1.5 1.5 0 0 0 12.5 9m0 1a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5" />
    <path d="M12.5 10a2.5 2.5 0 0 0-2.5 2.5V15h5v-2.5a2.5 2.5 0 0 0-2.5-2.5m0-1a3.5 3.5 0 0 1 3.5 3.5V15a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1v-2.5A3.5 3.5 0 0 1 12.5 9M5 16a1 1 0 0 1-.993-.883L4 15v-2a3 3 0 0 1 2.824-2.995L7 10v1a2 2 0 0 0-1.995 1.851L5 13v2h1.5a.5.5 0 0 1 0 1z" />
    <path d="M7 10a1 1 0 1 0 0-2 1 1 0 0 0 0 2m0 1a2 2 0 1 1-.001-3.999A2 2 0 0 1 7 11" />
    <path d="M11 0c1.054 0 1.918.816 1.995 1.851L13 2v.5a.5.5 0 0 1-.992.09L12 2.5V2a1 1 0 0 0-.883-.993L11 1H2a1 1 0 0 0-.993.883L1 2v10a1 1 0 0 0 .883.993L2 13h.5a.5.5 0 0 1 .09.992L2.5 14H2a2 2 0 0 1-1.995-1.851L0 12V2C0 .946.816.082 1.851.005L2 0z" />
  </svg>
);
const ForwardRef = forwardRef(PeoplesMap);
export default ForwardRef;
