// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PeoplesTarget = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M12.5 8a2.5 2.5 0 0 1 1.625 4.4A3.5 3.5 0 0 1 16 15.5v.5H9v-.5c0-1.347.76-2.516 1.875-3.101A2.5 2.5 0 0 1 12.5 8m0 5a2.5 2.5 0 0 0-2.45 2h4.9l-.038-.161A2.5 2.5 0 0 0 12.5 13m0-4a1.5 1.5 0 1 0 .001 3.001A1.5 1.5 0 0 0 12.5 9M7 10a2 2 0 1 1 0 4c-1.052 0-2 1.084-2 2H4c0-.99.644-2.036 1.578-2.594A2 2 0 0 1 7 10m0 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2" />
    <path d="M2.5 12A1.5 1.5 0 0 1 1 10.5v-8A1.5 1.5 0 0 1 2.5 1h8A1.5 1.5 0 0 1 12 2.5v3a.5.5 0 0 0 1 0v-3A2.5 2.5 0 0 0 10.5 0h-8A2.5 2.5 0 0 0 0 2.5v8A2.5 2.5 0 0 0 2.5 13a.5.5 0 0 0 0-1" />
    <path d="M6.5 2a.5.5 0 0 1 .5.5l.001.536A3.5 3.5 0 0 1 9.965 6h.535a.5.5 0 0 1 0 1l-.536.001A3.5 3.5 0 0 1 8.28 9.514a.5.5 0 1 1-.509-.861A2.5 2.5 0 0 0 8.95 7L7.5 6.999a.5.5 0 0 1 0-1L8.95 6A2.5 2.5 0 0 0 7 4.05V5.5a.5.5 0 0 1-1 0l.001-1.45A2.5 2.5 0 0 0 4.05 6.001L5.5 6a.5.5 0 0 1 0 1l-1.45.001a2.5 2.5 0 0 0 1.704 1.886.499.499 0 1 1-.298.954A3.5 3.5 0 0 1 3.036 7L2.5 6.999a.5.5 0 0 1 0-1h.535A3.5 3.5 0 0 1 6 3.034v-.535a.5.5 0 0 1 .5-.5zm0 5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0v-1a.5.5 0 0 1 .5-.5" />
  </svg>
);
const ForwardRef = forwardRef(PeoplesTarget);
export default ForwardRef;
