// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Peoples = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 5a2 2 0 1 0 .001-3.999A2 2 0 0 0 8 5m0 1a3 3 0 1 1 0-6 3 3 0 0 1 0 6m5 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2m0 1a2 2 0 1 1-.001-3.999A2 2 0 0 1 13 8M3 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2m0 1a2 2 0 1 1-.001-3.999A2 2 0 0 1 3 8m5 0a3 3 0 0 0-3 3v4h6v-4a3 3 0 0 0-3-3m0-1a4 4 0 0 1 4 4v4a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-4a4 4 0 0 1 4-4m5 7a2 2 0 1 0 0-4V9a3 3 0 1 1 0 6zm0 0a2 2 0 1 0 0-4V9a3 3 0 1 1 0 6zM3 14v1a3 3 0 1 1 0-6v1a2 2 0 1 0 0 4m0 0v1a3 3 0 1 1 0-6v1a2 2 0 1 0 0 4" />
  </svg>
);
const ForwardRef = forwardRef(Peoples);
export default ForwardRef;
