// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PeoplesTime = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M12.5 8a2.5 2.5 0 0 1 1.625 4.4A3.5 3.5 0 0 1 16 15.5v.5H9v-.5c0-1.347.76-2.516 1.875-3.101A2.5 2.5 0 0 1 12.5 8m0 5a2.5 2.5 0 0 0-2.45 2h4.9l-.038-.161A2.5 2.5 0 0 0 12.5 13m0-4a1.5 1.5 0 1 0 .001 3.001A1.5 1.5 0 0 0 12.5 9M7 10a2 2 0 1 1 0 4c-1.052 0-2 1.084-2 2H4c0-.99.644-2.036 1.578-2.594A2 2 0 0 1 7 10m0 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2M11.999 5.999a.5.5 0 0 1-1 0A5 5 0 1 0 3.287 10.2a.5.5 0 1 1-.543.839 6 6 0 1 1 9.255-5.041z" />
    <path d="M5.5 7a.5.5 0 0 1-.5-.5V3a.5.5 0 0 1 1 0v3h2a.5.5 0 0 1 0 1z" />
  </svg>
);
const ForwardRef = forwardRef(PeoplesTime);
export default ForwardRef;
