// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PeopleFliter = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M7 0a3 3 0 1 1 0 6 3 3 0 0 1 0-6m0 1a2 2 0 1 0-.001 3.999A2 2 0 0 0 7 1M2 3a2 2 0 1 1 .001 3.999A2 2 0 0 1 2 3m0 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2" />
    <path d="M7 5a.5.5 0 0 1 0 1C5.641 6 4.113 7.345 4.006 8.834L4 9v3.5a.5.5 0 0 0 .41.492L4.5 13H8a.5.5 0 0 1 .09.992L8 14H4.5a1.5 1.5 0 0 1-1.493-1.356L3 12.5V9c0-2.128 2.059-4 4-4M2.474 7.342a.5.5 0 0 0-.632-.316C.681 7.413.064 8.365.005 9.774L0 10v2.5a.5.5 0 0 0 .992.09L1 12.5V10c0-1.133.38-1.766 1.158-2.026a.5.5 0 0 0 .316-.632" />
    <path d="M13.5 7a.5.5 0 0 1 .09.992L13.5 8H8.435l2.481 3.723a.5.5 0 0 1 .074.18l.01.098v2.191l1 .5v-2.691q0-.1.038-.191l.046-.086 3-4.5a.5.5 0 0 1 .875.475l-.043.079L13 12.152v3.349a.5.5 0 0 1-.646.478l-.078-.031-2-1a.5.5 0 0 1-.268-.354l-.009-.093v-2.347L7.083 7.778a.5.5 0 0 1 .333-.771L7.499 7h6z" />
  </svg>
);
const ForwardRef = forwardRef(PeopleFliter);
export default ForwardRef;
