// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PeopleFolder = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M5.947 0C6.438 0 6.9.219 7.2.579L8.253 2h4.734c1.061 0 1.931.815 2.008 1.851l.006.149v2.5a.5.5 0 0 1-.992.09l-.008-.09V4c0-.515-.394-.94-.903-.994L12.987 3H7.748L6.476 1.28a.63.63 0 0 0-.424-.271L5.947 1H2.014a1.01 1.01 0 0 0-1.008.891L1 2v9c0 .515.394.94.903.994l.111.006H3a.5.5 0 0 1 .09.992L3 13h-.986a2.01 2.01 0 0 1-2.008-1.851L0 11V2C0 .945.822.082 1.863.005L2.013 0h3.933z" />
    <path d="M10 6a2 2 0 1 1 .001 3.999A2 2 0 0 1 10 6m0 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m2 2.5a1.5 1.5 0 1 1 2.747.834 2.5 2.5 0 0 1 1.247 2.002l.005.164v2a.5.5 0 0 1-.41.492l-.09.008h-1.5a.5.5 0 0 1-.09-.992l.09-.008h1v-1.5a1.5 1.5 0 0 0-1.356-1.493L13.499 11a1.5 1.5 0 0 1-1.5-1.5zm1.5-.5a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1m-7-1a1.5 1.5 0 0 1 .144 2.993l-.289.014A1.5 1.5 0 0 0 4.999 12.5V14h1l.09.008a.5.5 0 0 1-.09.992h-1.5l-.09-.008a.5.5 0 0 1-.41-.492v-2l.005-.164a2.5 2.5 0 0 1 1.249-2.004A1.5 1.5 0 0 1 6.499 8zm0 1a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1" />
    <path d="M10 10a3 3 0 0 1 3 3v2.5a.5.5 0 0 1-.5.5h-5a.5.5 0 0 1-.5-.5V13a3 3 0 0 1 3-3m0 1a2 2 0 0 0-1.995 1.851L8 13v2h4v-2a2 2 0 0 0-1.851-1.995z" />
  </svg>
);
const ForwardRef = forwardRef(PeopleFolder);
export default ForwardRef;
