// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const SearchPeople = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M7 13A6 6 0 1 0 7 1a6 6 0 0 0 0 12m0 1A7 7 0 1 1 7 0a7 7 0 0 1 0 14" />
    <path d="M7 8a2 2 0 1 0 .001-3.999A2 2 0 0 0 7 8m0 1a3 3 0 1 1 0-6 3 3 0 0 1 0 6" />
    <path d="M10 12.5v-.49A3 3 0 0 0 7 9c-1.654 0-3 1.349-3 3.01v.49H3v-.49A4.007 4.007 0 0 1 7 8a4 4 0 0 1 4 4.01v.49zm0 0v-.49A3 3 0 0 0 7 9c-1.654 0-3 1.349-3 3.01v.49H3v-.49A4.007 4.007 0 0 1 7 8a4 4 0 0 1 4 4.01v.49zm5.854 2.646a.5.5 0 0 1-.707.707l-3.5-3.5a.5.5 0 0 1 .707-.707z" />
  </svg>
);
const ForwardRef = forwardRef(SearchPeople);
export default ForwardRef;
