const glob = require('glob');
const fs = require('fs-extra');
const path = require('path');
const lowerCase = require('lodash/lowerCase');
const changelog = require('./changelog.json');

const SRC_DIR = '../node_modules/@rsuite/icon-font/lib';
const DIST_DIR = '../src/icons';

const resolvePath = (...paths) => path.resolve(__dirname, ...paths);

/**
 * Writes the component content to a file.
 * @param {string} componentName - The name of the component.
 * @param {string} categoryName - The category of the component.
 * @param {boolean} isLegacy - Whether the component is in the legacy category.
 */
const writeComponentFile = (componentName, categoryName, isLegacy) => {
  const componentPath = resolvePath(DIST_DIR, isLegacy ? 'legacy' : '', `${componentName}.tsx`);
  const relativeSvgImport = isLegacy ? '../../createSvgIcon' : '../createSvgIcon';
  const svgImportPath = `@rsuite/icon-font/lib/${categoryName}/${componentName}`;

  const content = `// Generated by script, don't edit it please.
import createSvgIcon from '${relativeSvgImport}';
import ${componentName}Svg from '${svgImportPath}';

const ${componentName} = createSvgIcon({
  as: ${componentName}Svg,
  ariaLabel: '${lowerCase(componentName)}',
  category: '${categoryName}',
  displayName: '${componentName}'
});

export default ${componentName};
`;

  fs.outputFileSync(componentPath, content);
};

/**
 * Writes the index.ts or legacy/index.ts file with the export statements for all components.
 * @param {string[]} icons - The list of icon components to export
 * @param {boolean} isLegacy - Whether to write the legacy index file.
 */
const writeIndexFile = (icons, isLegacy = false) => {
  const content = icons
    .map(icon => `export { default as ${icon.name} } from './${icon.name}';`)
    .join('\n');

  const indexPath = resolvePath(DIST_DIR, isLegacy ? 'legacy/index.ts' : 'index.ts');
  const header = `// Generated by script, don't edit it please.\n`;

  fs.outputFileSync(indexPath, header + content + '\n');
};

/**
 * Writes the meta.json file with the icon names and categories
 * @param {Array} icons - An array of icon objects
 * @param {Array} changelog - An array of changelog items
 */
const writeMetaFile = (icons, changelog) => {
  if (!Array.isArray(changelog)) {
    throw new Error('Invalid changelog: Expected an array.');
  }

  const findVersion = name => {
    for (const item of changelog) {
      const icon = item.icons.find(icon => icon === name);
      if (icon) {
        return item.version;
      }
    }
    return null;
  };

  const iconMeta = icons.map(icon => {
    const item = {
      iconName: icon.name,
      categoryName: icon.category,
      version: findVersion(icon.name) || undefined
    };
    return item;
  });

  const metaPath = resolvePath('../src', 'meta.json');
  fs.outputFileSync(metaPath, JSON.stringify(iconMeta, null, 2));
};

/**
 * Main function to generate all icon components and index files.
 */
module.exports = function generateIconComponents() {
  const files = glob.sync(resolvePath(`${SRC_DIR}/**/*.js`));
  const icons = [];
  const legacyIcons = [];

  files.forEach((svgPath, index) => {
    const basename = path.basename(svgPath);
    const componentName = path.basename(basename, path.extname(basename));
    const categoryName = path.relative(resolvePath(SRC_DIR), path.dirname(svgPath));
    const isLegacy = categoryName === 'legacy';

    const iconProps = {
      name: componentName,
      category: categoryName,
      isLegacy
    };

    isLegacy ? legacyIcons.push(iconProps) : icons.push(iconProps);
    console.log(`(${index + 1}/${files.length}) Generating ${componentName}.tsx ...`);

    try {
      writeComponentFile(componentName, categoryName, isLegacy);
    } catch (error) {
      console.error(`Error generating ${componentName}:`, error);
    }
  });

  try {
    writeIndexFile(icons);
    writeIndexFile(legacyIcons, true);
    writeMetaFile(icons, changelog);
  } catch (error) {
    console.error('Error writing index files:', error);
  }
};
