// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const ArrowBack = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M5.854 2.146a.5.5 0 0 1 .058.638l-.058.069-4.147 4.146H15.5a.5.5 0 0 1 0 1H1.707l4.147 4.146a.5.5 0 0 1-.707.707L.11 7.81l-.042-.062-.029-.059-.021-.062-.011-.054-.004-.031-.002-.053q.001-.032.005-.063L.001 7.5l.003-.053.014-.075.021-.063.039-.076.04-.055 5.029-5.031a.5.5 0 0 1 .707 0z" />
  </svg>
);
const ForwardRef = forwardRef(ArrowBack);
export default ForwardRef;
