// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const ArrowRightLine = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M5.128 3.166a.5.5 0 0 0 .037.706L9.752 8l-4.587 4.128a.5.5 0 1 0 .669.743l5-4.5a.5.5 0 0 0 0-.744l-5-4.5a.5.5 0 0 0-.706.037z" />
  </svg>
);
const ForwardRef = forwardRef(ArrowRightLine);
export default ForwardRef;
