// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const SortDesc = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M2.5 1a.5.5 0 0 1 .5.5v11.793l1.146-1.147.069-.058a.5.5 0 0 1 .696.696l-.058.069-2.031 2.029-.072.051-.059.029-.062.021-.056.011-.072.005-.053-.003-.075-.014-.063-.021-.076-.039-.055-.04-2.031-2.029-.058-.069a.5.5 0 0 1 0-.569l.058-.069.069-.058a.5.5 0 0 1 .569 0l.069.058 1.146 1.147V1.5a.5.5 0 0 1 .5-.5zM7.5 1h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1 0-1M7.5 5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1 0-1M7.5 9h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1M7.5 13h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1" />
  </svg>
);
const ForwardRef = forwardRef(SortDesc);
export default ForwardRef;
