// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const SortAsc = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="m2.426 1.005.032-.004.054-.002q.032.001.062.005L2.5.999l.053.003.075.014.063.021.093.051.057.046 2.012 2.012a.5.5 0 0 1-.638.765l-.069-.058L3 2.705v11.794a.5.5 0 0 1-1 0V2.705L.854 3.853a.5.5 0 0 1-.638.058l-.069-.058a.5.5 0 0 1-.058-.638l.058-.069 2-2 .042-.037.062-.042.059-.029.062-.021.054-.011zM7.5 1h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1 0-1M7.5 5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1 0-1M7.5 9h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1M7.5 13h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1" />
  </svg>
);
const ForwardRef = forwardRef(SortAsc);
export default ForwardRef;
