// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const SortUp = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8.5 2a.5.5 0 0 1 .394.192l3.996 4.996a.5.5 0 1 1-.781.625l-3.11-3.887v9.575a.5.5 0 0 1-1 0V3.926l-3.11 3.887a.5.5 0 1 1-.781-.625l3.998-4.997.013-.015a.5.5 0 0 1 .38-.175z" />
  </svg>
);
const ForwardRef = forwardRef(SortUp);
export default ForwardRef;
