// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import AlipayMiniSvg from '../icons/platform/AlipayMini';

const AlipayMini = createSvgIcon({
  as: AlipayMiniSvg,
  ariaLabel: 'alipay mini',
  category: 'platform',
  displayName: 'AlipayMini'
});

export default AlipayMini;
