// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ArrowBackSvg from '../icons/direction/ArrowBack';

const ArrowBack = createSvgIcon({
  as: ArrowBackSvg,
  ariaLabel: 'arrow back',
  category: 'direction',
  displayName: 'ArrowBack'
});

export default ArrowBack;
