// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import BarChartHorizontalSvg from '../icons/charts/BarChartHorizontal';

const BarChartHorizontal = createSvgIcon({
  as: BarChartHorizontalSvg,
  ariaLabel: 'bar chart horizontal',
  category: 'charts',
  displayName: 'BarChartHorizontal'
});

export default BarChartHorizontal;
