// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import BranchLockSvg from '../icons/flow/BranchLock';

const BranchLock = createSvgIcon({
  as: BranchLockSvg,
  ariaLabel: 'branch lock',
  category: 'flow',
  displayName: 'BranchLock'
});

export default BranchLock;
