// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import BytedanceSvg from '../icons/platform/Bytedance';

const Bytedance = createSvgIcon({
  as: BytedanceSvg,
  ariaLabel: 'bytedance',
  category: 'platform',
  displayName: 'Bytedance'
});

export default Bytedance;
