// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ChangeListSvg from '../icons/file/ChangeList';

const ChangeList = createSvgIcon({
  as: ChangeListSvg,
  ariaLabel: 'change list',
  category: 'file',
  displayName: 'ChangeList'
});

export default ChangeList;
