// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import CloudReflashSvg from '../icons/network/CloudReflash';

const CloudReflash = createSvgIcon({
  as: CloudReflashSvg,
  ariaLabel: 'cloud reflash',
  category: 'network',
  displayName: 'CloudReflash'
});

export default CloudReflash;
