// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import CollaspedArrowSvg from '../icons/direction/CollaspedArrow';

const CollaspedArrow = createSvgIcon({
  as: CollaspedArrowSvg,
  ariaLabel: 'collasped arrow',
  category: 'direction',
  displayName: 'CollaspedArrow'
});

export default CollaspedArrow;
