// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import CollaspedFillSvg from '../icons/action/CollaspedFill';

const CollaspedFill = createSvgIcon({
  as: CollaspedFillSvg,
  ariaLabel: 'collasped fill',
  category: 'action',
  displayName: 'CollaspedFill'
});

export default CollaspedFill;
