// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ColumnsSvg from '../icons/layout/Columns';

const Columns = createSvgIcon({
  as: ColumnsSvg,
  ariaLabel: 'columns',
  category: 'layout',
  displayName: 'Columns'
});

export default Columns;
