// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import CombinationSvg from '../icons/action/Combination';

const Combination = createSvgIcon({
  as: CombinationSvg,
  ariaLabel: 'combination',
  category: 'action',
  displayName: 'Combination'
});

export default Combination;
