// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ConversionSvg from '../icons/action/Conversion';

const Conversion = createSvgIcon({
  as: ConversionSvg,
  ariaLabel: 'conversion',
  category: 'action',
  displayName: 'Conversion'
});

export default Conversion;
