// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import CookieSvg from '../icons/platform/Cookie';

const Cookie = createSvgIcon({
  as: CookieSvg,
  ariaLabel: 'cookie',
  category: 'platform',
  displayName: 'Cookie'
});

export default Cookie;
