// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import CopySvg from '../icons/action/Copy';

const Copy = createSvgIcon({
  as: CopySvg,
  ariaLabel: 'copy',
  category: 'action',
  displayName: 'Copy'
});

export default Copy;
