// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import CreditCardMinusSvg from '../icons/application/CreditCardMinus';

const CreditCardMinus = createSvgIcon({
  as: CreditCardMinusSvg,
  ariaLabel: 'credit card minus',
  category: 'application',
  displayName: 'CreditCardMinus'
});

export default CreditCardMinus;
