// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import DataAuthorizeSvg from '../icons/application/DataAuthorize';

const DataAuthorize = createSvgIcon({
  as: DataAuthorizeSvg,
  ariaLabel: 'data authorize',
  category: 'application',
  displayName: 'DataAuthorize'
});

export default DataAuthorize;
