// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import DateTaskSvg from '../icons/time/DateTask';

const DateTask = createSvgIcon({
  as: DateTaskSvg,
  ariaLabel: 'date task',
  category: 'time',
  displayName: 'DateTask'
});

export default DateTask;
