// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import DonutChartSvg from '../icons/charts/DonutChart';

const DonutChart = createSvgIcon({
  as: DonutChartSvg,
  ariaLabel: 'donut chart',
  category: 'charts',
  displayName: 'DonutChart'
});

export default DonutChart;
