// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import DragableSvg from '../icons/action/Dragable';

const Dragable = createSvgIcon({
  as: DragableSvg,
  ariaLabel: 'dragable',
  category: 'action',
  displayName: 'Dragable'
});

export default Dragable;
