// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import EmailFillSvg from '../icons/file/EmailFill';

const EmailFill = createSvgIcon({
  as: EmailFillSvg,
  ariaLabel: 'email fill',
  category: 'file',
  displayName: 'EmailFill'
});

export default EmailFill;
