// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ExitSvg from '../icons/action/Exit';

const Exit = createSvgIcon({
  as: ExitSvg,
  ariaLabel: 'exit',
  category: 'action',
  displayName: 'Exit'
});

export default Exit;
