// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ExploreSvg from '../icons/application/Explore';

const Explore = createSvgIcon({
  as: ExploreSvg,
  ariaLabel: 'explore',
  category: 'application',
  displayName: 'Explore'
});

export default Explore;
