// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ExportSvg from '../icons/network/Export';

const Export = createSvgIcon({
  as: ExportSvg,
  ariaLabel: 'export',
  category: 'network',
  displayName: 'Export'
});

export default Export;
