// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import EyeRoundSvg from '../icons/status/EyeRound';

const EyeRound = createSvgIcon({
  as: EyeRoundSvg,
  ariaLabel: 'eye round',
  category: 'status',
  displayName: 'EyeRound'
});

export default EyeRound;
