// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import FileUploadSvg from '../icons/action/FileUpload';

const FileUpload = createSvgIcon({
  as: FileUploadSvg,
  ariaLabel: 'file upload',
  category: 'action',
  displayName: 'FileUpload'
});

export default FileUpload;
