// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import FolderSvg from '../icons/file/Folder';

const Folder = createSvgIcon({
  as: FolderSvg,
  ariaLabel: 'folder',
  category: 'file',
  displayName: 'Folder'
});

export default Folder;
