// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import FunnelTimeSvg from '../icons/charts/FunnelTime';

const FunnelTime = createSvgIcon({
  as: FunnelTimeSvg,
  ariaLabel: 'funnel time',
  category: 'charts',
  displayName: 'FunnelTime'
});

export default FunnelTime;
