// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import FunnelTrendSvg from '../icons/charts/FunnelTrend';

const FunnelTrend = createSvgIcon({
  as: FunnelTrendSvg,
  ariaLabel: 'funnel trend',
  category: 'charts',
  displayName: 'FunnelTrend'
});

export default FunnelTrend;
