// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import GlobalSvg from '../icons/network/Global';

const Global = createSvgIcon({
  as: GlobalSvg,
  ariaLabel: 'global',
  category: 'network',
  displayName: 'Global'
});

export default Global;
