// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import GrowthSvg from '../icons/application/Growth';

const Growth = createSvgIcon({
  as: GrowthSvg,
  ariaLabel: 'growth',
  category: 'application',
  displayName: 'Growth'
});

export default Growth;
