// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import HeartSvg from '../icons/action/Heart';

const Heart = createSvgIcon({
  as: HeartSvg,
  ariaLabel: 'heart',
  category: 'action',
  displayName: 'Heart'
});

export default Heart;
