// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import HightSvg from '../icons/layout/Hight';

const Hight = createSvgIcon({
  as: HightSvg,
  ariaLabel: 'hight',
  category: 'layout',
  displayName: 'Hight'
});

export default Hight;
