// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import HistoryTaskSvg from '../icons/time/HistoryTask';

const HistoryTask = createSvgIcon({
  as: HistoryTaskSvg,
  ariaLabel: 'history task',
  category: 'time',
  displayName: 'HistoryTask'
});

export default HistoryTask;
