// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import IdInfoSvg from '../icons/people/IdInfo';

const IdInfo = createSvgIcon({
  as: IdInfoSvg,
  ariaLabel: 'id info',
  category: 'people',
  displayName: 'IdInfo'
});

export default IdInfo;
