// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ImportStorageSvg from '../icons/action/ImportStorage';

const ImportStorage = createSvgIcon({
  as: ImportStorageSvg,
  ariaLabel: 'import storage',
  category: 'action',
  displayName: 'ImportStorage'
});

export default ImportStorage;
