// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ImportSiteSvg from '../icons/action/ImportSite';

const ImportSite = createSvgIcon({
  as: ImportSiteSvg,
  ariaLabel: 'import site',
  category: 'action',
  displayName: 'ImportSite'
});

export default ImportSite;
