// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import LocationSvg from '../icons/people/Location';

const Location = createSvgIcon({
  as: LocationSvg,
  ariaLabel: 'location',
  category: 'people',
  displayName: 'Location'
});

export default Location;
