// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import LockRoundSvg from '../icons/status/LockRound';

const LockRound = createSvgIcon({
  as: LockRoundSvg,
  ariaLabel: 'lock round',
  category: 'status',
  displayName: 'LockRound'
});

export default LockRound;
