// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import MediaSvg from '../icons/av/Media';

const Media = createSvgIcon({
  as: MediaSvg,
  ariaLabel: 'media',
  category: 'av',
  displayName: 'Media'
});

export default Media;
