// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import MemberSvg from '../icons/people/Member';

const Member = createSvgIcon({
  as: MemberSvg,
  ariaLabel: 'member',
  category: 'people',
  displayName: 'Member'
});

export default Member;
