// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import MobileSvg from '../icons/device/Mobile';

const Mobile = createSvgIcon({
  as: MobileSvg,
  ariaLabel: 'mobile',
  category: 'device',
  displayName: 'Mobile'
});

export default Mobile;
