// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ModelSvg from '../icons/application/Model';

const Model = createSvgIcon({
  as: ModelSvg,
  ariaLabel: 'model',
  category: 'application',
  displayName: 'Model'
});

export default Model;
