// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import NumbersSvg from '../icons/charts/Numbers';

const Numbers = createSvgIcon({
  as: NumbersSvg,
  ariaLabel: 'numbers',
  category: 'charts',
  displayName: 'Numbers'
});

export default Numbers;
