// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import OffSvg from '../icons/action/Off';

const Off = createSvgIcon({
  as: OffSvg,
  ariaLabel: 'off',
  category: 'action',
  displayName: 'Off'
});

export default Off;
