// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import OffBranchSvg from '../icons/action/OffBranch';

const OffBranch = createSvgIcon({
  as: OffBranchSvg,
  ariaLabel: 'off branch',
  category: 'action',
  displayName: 'OffBranch'
});

export default OffBranch;
