// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import OneColumnSvg from '../icons/layout/OneColumn';

const OneColumn = createSvgIcon({
  as: OneColumnSvg,
  ariaLabel: 'one column',
  category: 'layout',
  displayName: 'OneColumn'
});

export default OneColumn;
