// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PageSvg from '../icons/file/Page';

const Page = createSvgIcon({
  as: PageSvg,
  ariaLabel: 'page',
  category: 'file',
  displayName: 'Page'
});

export default Page;
