// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ParagraphSvg from '../icons/file/Paragraph';

const Paragraph = createSvgIcon({
  as: ParagraphSvg,
  ariaLabel: 'paragraph',
  category: 'file',
  displayName: 'Paragraph'
});

export default Paragraph;
