// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PauseOutlineSvg from '../icons/av/PauseOutline';

const PauseOutline = createSvgIcon({
  as: PauseOutlineSvg,
  ariaLabel: 'pause outline',
  category: 'av',
  displayName: 'PauseOutline'
});

export default PauseOutline;
