// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PeopleBranchSvg from '../icons/people/PeopleBranch';

const PeopleBranch = createSvgIcon({
  as: PeopleBranchSvg,
  ariaLabel: 'people branch',
  category: 'people',
  displayName: 'PeopleBranch'
});

export default PeopleBranch;
