// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PeoplesCostomizeSvg from '../icons/people/PeoplesCostomize';

const PeoplesCostomize = createSvgIcon({
  as: PeoplesCostomizeSvg,
  ariaLabel: 'peoples costomize',
  category: 'people',
  displayName: 'PeoplesCostomize'
});

export default PeoplesCostomize;
