// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PeoplesPlusSvg from '../icons/people/PeoplesPlus';

const PeoplesPlus = createSvgIcon({
  as: PeoplesPlusSvg,
  ariaLabel: 'peoples plus',
  category: 'people',
  displayName: 'PeoplesPlus'
});

export default PeoplesPlus;
