// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PeopleSpeakerSvg from '../icons/people/PeopleSpeaker';

const PeopleSpeaker = createSvgIcon({
  as: PeopleSpeakerSvg,
  ariaLabel: 'people speaker',
  category: 'people',
  displayName: 'PeopleSpeaker'
});

export default PeopleSpeaker;
