// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PeopleFolderSvg from '../icons/people/PeopleFolder';

const PeopleFolder = createSvgIcon({
  as: PeopleFolderSvg,
  ariaLabel: 'people folder',
  category: 'people',
  displayName: 'PeopleFolder'
});

export default PeopleFolder;
