// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PinedSvg from '../icons/status/Pined';

const Pined = createSvgIcon({
  as: PinedSvg,
  ariaLabel: 'pined',
  category: 'status',
  displayName: 'Pined'
});

export default Pined;
