// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PlayOutlineSvg from '../icons/av/PlayOutline';

const PlayOutline = createSvgIcon({
  as: PlayOutlineSvg,
  ariaLabel: 'play outline',
  category: 'av',
  displayName: 'PlayOutline'
});

export default PlayOutline;
