// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PlusRoundSvg from '../icons/status/PlusRound';

const PlusRound = createSvgIcon({
  as: PlusRoundSvg,
  ariaLabel: 'plus round',
  category: 'status',
  displayName: 'PlusRound'
});

export default PlusRound;
