// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import PushMessageSvg from '../icons/application/PushMessage';

const PushMessage = createSvgIcon({
  as: PushMessageSvg,
  ariaLabel: 'push message',
  category: 'application',
  displayName: 'PushMessage'
});

export default PushMessage;
