// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import RandomSvg from '../icons/flow/Random';

const Random = createSvgIcon({
  as: RandomSvg,
  ariaLabel: 'random',
  category: 'flow',
  displayName: 'Random'
});

export default Random;
