// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import RemindOutlineSvg from '../icons/status/RemindOutline';

const RemindOutline = createSvgIcon({
  as: RemindOutlineSvg,
  ariaLabel: 'remind outline',
  category: 'status',
  displayName: 'RemindOutline'
});

export default RemindOutline;
