// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ReviewSvg from '../icons/flow/Review';

const Review = createSvgIcon({
  as: ReviewSvg,
  ariaLabel: 'review',
  category: 'flow',
  displayName: 'Review'
});

export default Review;
