// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import RunningRoundSvg from '../icons/status/RunningRound';

const RunningRound = createSvgIcon({
  as: RunningRoundSvg,
  ariaLabel: 'running round',
  category: 'status',
  displayName: 'RunningRound'
});

export default RunningRound;
