// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SearchPeopleSvg from '../icons/people/SearchPeople';

const SearchPeople = createSvgIcon({
  as: SearchPeopleSvg,
  ariaLabel: 'search people',
  category: 'people',
  displayName: 'SearchPeople'
});

export default SearchPeople;
