// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SendRoundSvg from '../icons/status/SendRound';

const SendRound = createSvgIcon({
  as: SendRoundSvg,
  ariaLabel: 'send round',
  category: 'status',
  displayName: 'SendRound'
});

export default SendRound;
