// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SendToDashboardSvg from '../icons/action/SendToDashboard';

const SendToDashboard = createSvgIcon({
  as: SendToDashboardSvg,
  ariaLabel: 'send to dashboard',
  category: 'action',
  displayName: 'SendToDashboard'
});

export default SendToDashboard;
