// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SettingHorizontalSvg from '../icons/action/SettingHorizontal';

const SettingHorizontal = createSvgIcon({
  as: SettingHorizontalSvg,
  ariaLabel: 'setting horizontal',
  category: 'action',
  displayName: 'SettingHorizontal'
});

export default SettingHorizontal;
