// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SignatureSvg from '../icons/action/Signature';

const Signature = createSvgIcon({
  as: SignatureSvg,
  ariaLabel: 'signature',
  category: 'action',
  displayName: 'Signature'
});

export default Signature;
