// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SortBySvg from '../icons/direction/SortBy';

const SortBy = createSvgIcon({
  as: SortBySvg,
  ariaLabel: 'sort by',
  category: 'direction',
  displayName: 'SortBy'
});

export default SortBy;
