// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SortAscSvg from '../icons/direction/SortAsc';

const SortAsc = createSvgIcon({
  as: SortAscSvg,
  ariaLabel: 'sort asc',
  category: 'direction',
  displayName: 'SortAsc'
});

export default SortAsc;
