// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import SplitSvg from '../icons/flow/Split';

const Split = createSvgIcon({
  as: SplitSvg,
  ariaLabel: 'split',
  category: 'flow',
  displayName: 'Split'
});

export default Split;
