// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import StopOutlineSvg from '../icons/av/StopOutline';

const StopOutline = createSvgIcon({
  as: StopOutlineSvg,
  ariaLabel: 'stop outline',
  category: 'av',
  displayName: 'StopOutline'
});

export default StopOutline;
