// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import TagNumberSvg from '../icons/application/TagNumber';

const TagNumber = createSvgIcon({
  as: TagNumberSvg,
  ariaLabel: 'tag number',
  category: 'application',
  displayName: 'TagNumber'
});

export default TagNumber;
