// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import TouchSvg from '../icons/action/Touch';

const Touch = createSvgIcon({
  as: TouchSvg,
  ariaLabel: 'touch',
  category: 'action',
  displayName: 'Touch'
});

export default Touch;
