// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import UnvisibleSvg from '../icons/status/Unvisible';

const Unvisible = createSvgIcon({
  as: UnvisibleSvg,
  ariaLabel: 'unvisible',
  category: 'status',
  displayName: 'Unvisible'
});

export default Unvisible;
