// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import VerifyRoundSvg from '../icons/status/VerifyRound';

const VerifyRound = createSvgIcon({
  as: VerifyRoundSvg,
  ariaLabel: 'verify round',
  category: 'status',
  displayName: 'VerifyRound'
});

export default VerifyRound;
