// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import VideoSvg from '../icons/av/Video';

const Video = createSvgIcon({
  as: VideoSvg,
  ariaLabel: 'video',
  category: 'av',
  displayName: 'Video'
});

export default Video;
