// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ViewsAuthorizeSvg from '../icons/application/ViewsAuthorize';

const ViewsAuthorize = createSvgIcon({
  as: ViewsAuthorizeSvg,
  ariaLabel: 'views authorize',
  category: 'application',
  displayName: 'ViewsAuthorize'
});

export default ViewsAuthorize;
