// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ViewsUnauthorizeSvg from '../icons/application/ViewsUnauthorize';

const ViewsUnauthorize = createSvgIcon({
  as: ViewsUnauthorizeSvg,
  ariaLabel: 'views unauthorize',
  category: 'application',
  displayName: 'ViewsUnauthorize'
});

export default ViewsUnauthorize;
