// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import WaitSvg from '../icons/flow/Wait';

const Wait = createSvgIcon({
  as: WaitSvg,
  ariaLabel: 'wait',
  category: 'flow',
  displayName: 'Wait'
});

export default Wait;
