// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import WechatSubmessageOutlineSvg from '../icons/platform/WechatSubmessageOutline';

const WechatSubmessageOutline = createSvgIcon({
  as: WechatSubmessageOutlineSvg,
  ariaLabel: 'wechat submessage outline',
  category: 'platform',
  displayName: 'WechatSubmessageOutline'
});

export default WechatSubmessageOutline;
