// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import WidthSvg from '../icons/layout/Width';

const Width = createSvgIcon({
  as: WidthSvg,
  ariaLabel: 'width',
  category: 'layout',
  displayName: 'Width'
});

export default Width;
