// Generated by script, don't edit it please.
import createSvgIcon from '../createSvgIcon';
import ZoomoutSvg from '../icons/action/Zoomout';

const Zoomout = createSvgIcon({
  as: ZoomoutSvg,
  ariaLabel: 'zoomout',
  category: 'action',
  displayName: 'Zoomout'
});

export default Zoomout;
