// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Mobile = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M11 0a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm0 1H5a1 1 0 0 0-.993.883L4 2v12a1 1 0 0 0 .883.993L5 15h6a1 1 0 0 0 .993-.883L12 14V2a1 1 0 0 0-.883-.993z" />
    <path d="M6.5 13h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1 0-1" />
  </svg>
);
const ForwardRef = forwardRef(Mobile);
export default ForwardRef;
