// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Pc = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M14 1a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2zm0 1H2a1 1 0 0 0-.993.883L1 3v8a1 1 0 0 0 .883.993L2 12h12a1 1 0 0 0 .993-.883L15 11V3a1 1 0 0 0-.883-.993zM4.5 14h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1" />
  </svg>
);
const ForwardRef = forwardRef(Pc);
export default ForwardRef;
