// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PcFill = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M6 13H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-4v1h1.5a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1H6zm8-11H2a1 1 0 0 0-.993.883L1 3v8a1 1 0 0 0 .883.993L2 12h12a1 1 0 0 0 .993-.883L15 11V3a1 1 0 0 0-.883-.993z" />
    <path d="M12.5 3c.828 0 1.5.597 1.5 1.333v5.333c0 .736-.672 1.333-1.5 1.333h-9c-.828 0-1.5-.597-1.5-1.333V4.333C2 3.597 2.672 3 3.5 3z" />
  </svg>
);
const ForwardRef = forwardRef(PcFill);
export default ForwardRef;
