// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const PhoneFill = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M.077 2.149Q.556 8.557 4 12c3.444 3.443 5.579 3.603 9.851 3.923a2 2 0 0 0 2.15-1.994v-1.757a1.5 1.5 0 0 0-1.136-1.455l-2.04-.51a1.5 1.5 0 0 0-1.424.395l-1.009 1.009a1 1 0 0 1-.957.261q-2.107-.545-3.433-1.87Q4.681 8.68 4.135 6.583a1 1 0 0 1 .275-.973l1.033-.992c.395-.38.552-.945.409-1.474l-.55-2.034A1.5 1.5 0 0 0 3.854.002h-1.78A2 2 0 0 0 .08 2.151z" />
  </svg>
);
const ForwardRef = forwardRef(PhoneFill);
export default ForwardRef;
