// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Storage = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M13 10a3 3 0 1 1 0 6H3a3 3 0 1 1 0-6zm0 1H3a2 2 0 0 0-.149 3.995L3 15h10a2 2 0 0 0 .149-3.995z" />
    <path d="M13 5a3 3 0 1 1 0 6H3a3 3 0 1 1 0-6zm0 1H3a2 2 0 0 0-.149 3.995L3 10h10a2 2 0 0 0 .149-3.995z" />
    <path d="M13 0a3 3 0 1 1 0 6H3a3 3 0 1 1 0-6zm0 1H3a2 2 0 0 0-.149 3.995L3 5h10a2 2 0 0 0 .149-3.995z" />
    <path d="M3.5 3a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1m3 0a.5.5 0 0 1 0 1h-1a.5.5 0 0 1 0-1zm-3 5a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1m3 0a.5.5 0 0 1 0 1h-1a.5.5 0 0 1 0-1zm-1 5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm7 0a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1" />
  </svg>
);
const ForwardRef = forwardRef(Storage);
export default ForwardRef;
