// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const BatchPlus = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8.5 4A1.5 1.5 0 0 1 10 5.5a.5.5 0 0 1-.992.09L9 5.5a.5.5 0 0 0-.41-.492L8.5 5h-7a.5.5 0 0 0-.492.41L1 5.5v9a.5.5 0 0 0 .41.492L1.5 15h5a.5.5 0 0 1 .09.992L6.5 16h-5a1.5 1.5 0 0 1-1.493-1.356L0 14.5v-9a1.5 1.5 0 0 1 1.356-1.493L1.5 4z" />
    <path d="M10.5 2a1.5 1.5 0 0 1 1.493 1.356L12 3.5v1a.5.5 0 0 1-.992.09L11 4.5v-1a.5.5 0 0 0-.41-.492L10.5 3h-8a.5.5 0 0 1-.09-.992L2.5 2z" />
    <path d="M12.5 0a1.5 1.5 0 0 1 1.493 1.356L14 1.5v3a.5.5 0 0 1-.992.09L13 4.5v-3a.5.5 0 0 0-.41-.492L12.5 1h-8a.5.5 0 0 1-.09-.992L4.5 0zM11.5 15a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m0 1a4.5 4.5 0 1 1 0-9 4.5 4.5 0 0 1 0 9" />
    <path d="M11.5 9a.5.5 0 0 1 .5.5V11h1.5a.5.5 0 0 1 0 1H12v1.5a.5.5 0 0 1-1 0V12H9.5a.5.5 0 0 1 0-1H11V9.5a.5.5 0 0 1 .5-.5" />
  </svg>
);
const ForwardRef = forwardRef(BatchPlus);
export default ForwardRef;
