// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Block = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0m5.291 3.416L3.417 13.29a7 7 0 0 0 9.875-9.875zM8 1a7 7 0 0 0-5.291 11.584l9.874-9.874a6.97 6.97 0 0 0-4.584-1.709z" />
  </svg>
);
const ForwardRef = forwardRef(Block);
export default ForwardRef;
