// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Combination = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M10.5 5a5.5 5.5 0 0 1 .221 10.996L10.5 16a5.5 5.5 0 0 1-5.478-6H9.2a.8.8 0 0 0 .794-.7L10 9.2V5.022l.248-.017.251-.006zm.5 1.028-.002 3.234-.012.163a1.8 1.8 0 0 1-1.636 1.569L9.2 11H6.028l.015.128a4.5 4.5 0 0 0 4.245 3.867L10.5 15a4.5 4.5 0 0 0 .628-8.957zM9.2 0a.8.8 0 0 1 .8.8v4.222A5.5 5.5 0 0 0 5.022 10H.8a.8.8 0 0 1-.8-.8V.8A.8.8 0 0 1 .8 0zM9 1H1v8h3.174l.013-.052a6.51 6.51 0 0 1 4.762-4.762l.052-.013z" />
  </svg>
);
const ForwardRef = forwardRef(Combination);
export default ForwardRef;
