// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Conversion = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M1.707 13H13.5a1.5 1.5 0 0 0 1.5-1.5V7a.5.5 0 0 1 1 0v4.5a2.5 2.5 0 0 1-2.5 2.5H1.707l1.146 1.146a.5.5 0 0 1-.707.707l-2-2a.5.5 0 0 1 0-.707l2-2a.5.5 0 0 1 .707.707zM14.293 2 13.147.854a.5.5 0 0 1 .707-.707l2 2a.5.5 0 0 1 0 .707l-2 2a.5.5 0 0 1-.707-.707l1.146-1.146H2.5a1.5 1.5 0 0 0-1.5 1.5v4.5a.5.5 0 0 1-1 0v-4.5a2.5 2.5 0 0 1 2.5-2.5h11.793z" />
  </svg>
);
const ForwardRef = forwardRef(Conversion);
export default ForwardRef;
