// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Dragable = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M11.5 7a.5.5 0 0 1 .5.5v6.632l2.004-1.965a.59.59 0 0 1 .744-.066l.081.066a.56.56 0 0 1 .068.729l-.068.079-2.917 2.859a.6.6 0 0 1-.264.149L11.55 16h-.099a.6.6 0 0 1-.363-.165l-2.917-2.859c-.228-.223-.228-.585 0-.809s.597-.223.825 0L11 14.132V7.5a.5.5 0 0 1 .5-.5M4.55 0a.6.6 0 0 1 .363.165L7.83 3.024c.228.223.228.585 0 .809s-.597.223-.825 0L5.001 1.868V8.5a.5.5 0 0 1-1 0V1.866L1.997 3.833a.59.59 0 0 1-.744.066l-.081-.066a.56.56 0 0 1-.068-.729l.067-.079L4.088.166a.6.6 0 0 1 .363-.165z" />
  </svg>
);
const ForwardRef = forwardRef(Dragable);
export default ForwardRef;
