// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const ImportStorage = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M2 12h6a2 2 0 0 1 .149 3.995L8 16H2a2 2 0 0 1-.149-3.995zm0 1a1 1 0 0 0-.117 1.993L2 15h6a1 1 0 0 0 .117-1.993L8 13z" />
    <path d="M3.5 9a.5.5 0 0 1 .09.992L3.5 10H2a1 1 0 0 0-.117 1.993L2 12h1.5a.5.5 0 0 1 .09.992L3.5 13H2a2 2 0 0 1-.149-3.995L2 9z" />
    <path d="M4.5 6a.5.5 0 0 1 .09.992L4.5 7H2a1 1 0 0 0-.117 1.993L2 9h2.5a.5.5 0 0 1 .09.992L4.5 10H2a2 2 0 0 1-.149-3.995L2 6zM2 14h1v1H2zM2 11h1v1H2z" />
    <path d="M2 8h1v1H2zM8.426 6.005l.032-.004.054-.002a.4.4 0 0 1 .062.005L8.5 5.999l.053.003.075.014.063.021.093.051.057.046 2.012 2.012a.5.5 0 0 1-.638.765l-.069-.058L9 7.705v2.794a.5.5 0 0 1-1 0V7.705L6.854 8.853a.5.5 0 0 1-.638.058l-.069-.058a.5.5 0 0 1-.058-.638l.058-.069 2-2 .042-.037.062-.042.059-.029.062-.021.054-.011z" />
    <path d="M8.5 0a3.5 3.5 0 0 1 3.495 3.308L12 3.5l-.001.028.129.015a4.5 4.5 0 0 1 3.867 4.245L16 8a4.5 4.5 0 0 1-4.5 4.5.5.5 0 0 1 0-1A3.5 3.5 0 0 0 15 8a3.5 3.5 0 0 0-3.29-3.495l-.19-.005-.042.002a.5.5 0 0 1-.513-.583 2.5 2.5 0 1 0-4.935-.803.5.5 0 0 1-.57.419 2.991 2.991 0 0 0-2.694.963.499.499 0 1 1-.744-.668 4 4 0 0 1 2.749-1.324L5 2.5l.145.004.026-.087A3.5 3.5 0 0 1 8.308.006z" />
  </svg>
);
const ForwardRef = forwardRef(ImportStorage);
export default ForwardRef;
