// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Key = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M14.854 1.146a.5.5 0 0 1 .058.638l-.058.069-.647.646 1.647 1.646a.5.5 0 0 1-.638.765l-.069-.058-1.646-1.647-.793.793 1.647 1.646a.5.5 0 0 1-.638.765l-.069-.058-1.646-1.647-5.525 5.525.353.354a3 3 0 0 1-3.949 4.501 1.5 1.5 0 1 1-1.966-1.967A3 3 0 0 1 5.416 9.17l.354.353 8.378-8.379a.5.5 0 0 1 .707 0zM1.5 14a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1m.379-4.121a2 2 0 0 0-.102 2.719l.102.109 1.414 1.414a2 2 0 0 0 2.93-2.719l-.102-.109-1.414-1.414a2 2 0 0 0-2.828 0" />
  </svg>
);
const ForwardRef = forwardRef(Key);
export default ForwardRef;
