// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const MoveUp = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="m5.707 4 2.146 2.146a.5.5 0 0 1-.707.707l-3-3a.5.5 0 0 1 0-.707l3-3a.5.5 0 0 1 .707.707L5.707 2.999H10c3.314 0 6 2.91 6 6.5s-2.686 6.5-6 6.5a.5.5 0 0 1 0-1c2.743 0 5-2.445 5-5.5s-2.257-5.5-5-5.5H5.707zM.5 15h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1" />
    <path d="M.5 9h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1 0-1M.5 3h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1" />
  </svg>
);
const ForwardRef = forwardRef(MoveUp);
export default ForwardRef;
