// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Off = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M4.825 1.491a.499.499 0 1 1 .356.934A6.5 6.5 0 0 0 .999 8.5a6.5 6.5 0 1 0 8.827-6.071.5.5 0 1 1 .358-.934 7.5 7.5 0 1 1-5.36-.004z" />
    <path d="M7.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0v-6a.5.5 0 0 1 .5-.5" />
  </svg>
);
const ForwardRef = forwardRef(Off);
export default ForwardRef;
