// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Save = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M12.172 0a2 2 0 0 1 1.414.586l1.828 1.828A2 2 0 0 1 16 3.828V14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zM11 11H5a1 1 0 0 0-.993.883L4 12v3h8v-3a1 1 0 0 0-.883-.993zM3 1H2a1 1 0 0 0-.993.883L1 2v12a1 1 0 0 0 .883.993L2 15h1v-3a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v3h1a1 1 0 0 0 .993-.883L15 14V3.828a1 1 0 0 0-.206-.608l-.087-.099L13 1.414V7H3zm7 0H9v3h1zm2 5V1h-1v4H8V1H4v5z" />
  </svg>
);
const ForwardRef = forwardRef(Save);
export default ForwardRef;
