// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Search = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M6.5 1a5.5 5.5 0 1 1 0 11 5.5 5.5 0 1 1 0-11m0 1a4.5 4.5 0 1 0 0 9 4.5 4.5 0 0 0 0-9" />
    <path d="M9.646 9.646a.5.5 0 0 1 .638-.058l.069.058 4.5 4.5a.5.5 0 0 1-.638.765l-.069-.058-4.5-4.5a.5.5 0 0 1 0-.707" />
  </svg>
);
const ForwardRef = forwardRef(Search);
export default ForwardRef;
