// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const SendToDashboard = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M2 1a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zm0-1h4a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2m9 1a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zm0-1h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-3a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2M10.902 7.51a.5.5 0 0 1 .579.627l-.028.075-3.5 7.5a.5.5 0 0 1-.711.217l-.072-.052-2.138-1.871-1.157 1.324a.5.5 0 0 1-.869-.24l-.007-.089v-2.76l-2.312-1.85a.5.5 0 0 1 .123-.854l.091-.027zm-.774 1.173-7.979 1.596 1.461 1.168 3.252-.928c.423-.121.755.31.602.671l-.037.071-.051.068-1.685 1.924 1.637 1.432zm-4.621 3.263-.987.282.42.366zM14 9c1.054 0 1.918.816 1.995 1.851L16 11v3a2 2 0 0 1-1.851 1.995L14 16h-3a.5.5 0 0 1-.09-.992L11 15h3a1 1 0 0 0 .993-.883L15 14v-3a1 1 0 0 0-.883-.993L14 10h-1a.5.5 0 0 1-.09-.992L13 9z" />
  </svg>
);
const ForwardRef = forwardRef(SendToDashboard);
export default ForwardRef;
