// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Setting = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M5.5 7a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 5.5 7m0 1a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1m5-5a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 10.5 3m0 1a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1M5.5 3a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2a.5.5 0 0 1 .5-.5M5.5 11a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0v-1a.5.5 0 0 1 .5-.5M10.5 7a.5.5 0 0 1 .5.5v5a.5.5 0 0 1-1 0v-5a.5.5 0 0 1 .5-.5" />
    <path d="M14 15a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1zm0 1H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2" />
  </svg>
);
const ForwardRef = forwardRef(Setting);
export default ForwardRef;
