// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const ShareRound = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0m2 2a2 2 0 0 0-1.996 2.128L4.887 6.207a2 2 0 1 0 0 3.586l3.117 2.078L8 12a2 2 0 1 0 1.113-1.793L5.995 8.129 6 8q0-.065-.004-.129l3.117-2.078A2 2 0 1 0 10 2" />
  </svg>
);
const ForwardRef = forwardRef(ShareRound);
export default ForwardRef;
