// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Tools = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M12.538 1.048a3 3 0 0 0-3.265 4.205l.291.633-8.15 8.15.707.707 8.182-8.182.608.237a3 3 0 0 0 4.023-3.423l-1.427 1.427a1.5 1.5 0 0 1-2.121 0l-.24-.24a1.5 1.5 0 0 1 0-2.121l1.391-1.391zM8.365 5.671A4 4 0 0 1 14.284.716l-2.431 2.431a.5.5 0 0 0 0 .707l.24.24a.5.5 0 0 0 .707 0l2.44-2.44a4 4 0 0 1-4.691 6.075L2.828 15.45a1 1 0 0 1-1.414 0l-.707-.707a1 1 0 0 1 0-1.414z" />
    <path d="m10.5 9.914-.586.586L14 14.586l.586-.586zm.707-.707 4.086 4.086a1 1 0 0 1 0 1.414l-.586.586a1 1 0 0 1-1.414 0l-4.086-4.086a1 1 0 0 1 0-1.414l.586-.586a1 1 0 0 1 1.414 0M1.27 1.144l-.126.126.543 1.629 1.212-1.212zM2 4H1L0 1l1-1 3 1v1l-.646.646 4.5 4.5-.707.707-4.5-4.5-.646.646z" />
  </svg>
);
const ForwardRef = forwardRef(Tools);
export default ForwardRef;
