// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Verify = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="m1.766 4.077.072.055 6 5.5a.5.5 0 0 1 .064.666l-.064.071-6 5.5a.499.499 0 0 1-.736-.671l.061-.067 5.598-5.132-5.598-5.13a.5.5 0 0 1-.085-.635l.055-.072a.5.5 0 0 1 .635-.085zm12.468-4a.5.5 0 0 1 .635.086l.055.072a.5.5 0 0 1-.085.635L9.241 6l5.598 5.132.061.067a.5.5 0 0 1-.736.671l-6-5.5-.064-.071a.5.5 0 0 1 .064-.666l6-5.5z" />
  </svg>
);
const ForwardRef = forwardRef(Verify);
export default ForwardRef;
