// Generated by script, please do not edit this file.
import * as React from 'react';
import type { SVGProps } from 'react';
import { Ref, forwardRef } from 'react';
const Zoomout = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    fill="currentColor"
    ref={ref}
    {...props}
  >
    <path d="M9.5 1a.5.5 0 0 1 .5.5V6h4.5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5v-5a.5.5 0 0 1 .5-.5m-4-1a.5.5 0 0 1 .5.5v5l-.003.053-.014.075-.021.063-.039.076-.04.055-.029.031-.042.037-.062.042-.059.029-.062.021-.082.014-.046.002h-5a.5.5 0 0 1 0-1h3.793L.147.852A.5.5 0 0 1 .785.087l.069.058L5 4.292V.499a.5.5 0 0 1 .5-.5zm10 10a.5.5 0 0 1 0 1h-3.793l4.147 4.146a.5.5 0 0 1-.638.765l-.069-.058-4.146-4.147v3.793a.5.5 0 0 1-1 0v-5.011q0-.032.005-.063l-.005.074.003-.053.014-.075.021-.063.039-.076.04-.055.029-.031.042-.037.062-.042.059-.029.062-.021.054-.011.032-.004zm-9-1a.5.5 0 0 1 .5.5v5a.5.5 0 0 1-1 0V10H1.5a.5.5 0 0 1 0-1z" />
  </svg>
);
const ForwardRef = forwardRef(Zoomout);
export default ForwardRef;
